// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	stdmath "math"
	"testing"

	"github.com/wow-look-at-my/testify/assert"
)

// ---------------------------------------------------------------------------
// DVec2
// ---------------------------------------------------------------------------

func TestDVec2Constructor(t *testing.T) {
	v := NewDVec2(3, 4)
	assert.Equal(t, float64(3), v.X)
	assert.Equal(t, float64(4), v.Y)
}

func TestDVec2Add(t *testing.T) {
	got := DVec2{X: 1, Y: 2}.Add(DVec2{X: 3, Y: 4})
	assert.True(t, got.Eq(DVec2{X: 4, Y: 6}))
}

func TestDVec2Sub(t *testing.T) {
	got := DVec2{X: 5, Y: 7}.Sub(DVec2{X: 2, Y: 3})
	assert.True(t, got.Eq(DVec2{X: 3, Y: 4}))
}

func TestDVec2Scale(t *testing.T) {
	got := DVec2{X: 2, Y: 3}.Scale(3)
	assert.True(t, got.Eq(DVec2{X: 6, Y: 9}))
}

func TestDVec2Dot(t *testing.T) {
	assert.Equal(t, float64(11), DVec2{X: 1, Y: 2}.Dot(DVec2{X: 3, Y: 4}))
}

func TestDVec2LenSq(t *testing.T) {
	assert.Equal(t, float64(25), DVec2{X: 3, Y: 4}.LenSq())
}

func TestDVec2Len(t *testing.T) {
	assert.Equal(t, float64(5), DVec2{X: 3, Y: 4}.Len())
}

func TestDVec2Normalize(t *testing.T) {
	got := DVec2{X: 3, Y: 4}.Normalize()
	assert.True(t, got.ApproxEq(NewDVec2(0.6, 0.8), 1e-6))
}

func TestDVec2NormalizeZero(t *testing.T) {
	assert.True(t, DVec2{}.Normalize().Eq(DVec2{}))
}

func TestDVec2Dist(t *testing.T) {
	assert.Equal(t, float64(5), DVec2{}.Dist(DVec2{X: 3, Y: 4}))
}

func TestDVec2Lerp(t *testing.T) {
	got := DVec2{X: 0, Y: 0}.Lerp(DVec2{X: 10, Y: 20}, 0.5)
	assert.True(t, got.Eq(NewDVec2(5, 10)))
}

func TestDVec2Eq(t *testing.T) {
	assert.True(t, DVec2{X: 1, Y: 2}.Eq(DVec2{X: 1, Y: 2}))
	assert.False(t, DVec2{X: 1, Y: 2}.Eq(DVec2{X: 1, Y: 3}))
}

func TestDVec2ApproxEq(t *testing.T) {
	a := NewDVec2(1.0, 2.0)
	b := NewDVec2(1.0001, 2.0001)
	assert.True(t, a.ApproxEq(b, 0.001))
	assert.False(t, a.ApproxEq(b, 0.00001))
}

func TestDVec2Float32(t *testing.T) {
	assert.True(t, DVec2{X: 3, Y: 4}.Float32().Eq(NewVec2(3, 4)))
}

// ---------------------------------------------------------------------------
// DVec3
// ---------------------------------------------------------------------------

func TestDVec3Constructor(t *testing.T) {
	v := NewDVec3(1, 2, 3)
	assert.Equal(t, float64(1), v.X)
	assert.Equal(t, float64(2), v.Y)
	assert.Equal(t, float64(3), v.Z)
}

func TestDVec3Add(t *testing.T) {
	got := DVec3{X: 1, Y: 2, Z: 3}.Add(DVec3{X: 4, Y: 5, Z: 6})
	assert.True(t, got.Eq(DVec3{X: 5, Y: 7, Z: 9}))
}

func TestDVec3Sub(t *testing.T) {
	got := DVec3{X: 5, Y: 7, Z: 9}.Sub(DVec3{X: 1, Y: 2, Z: 3})
	assert.True(t, got.Eq(DVec3{X: 4, Y: 5, Z: 6}))
}

func TestDVec3Scale(t *testing.T) {
	got := DVec3{X: 1, Y: 2, Z: 3}.Scale(2)
	assert.True(t, got.Eq(DVec3{X: 2, Y: 4, Z: 6}))
}

func TestDVec3Dot(t *testing.T) {
	assert.Equal(t, float64(32), DVec3{X: 1, Y: 2, Z: 3}.Dot(DVec3{X: 4, Y: 5, Z: 6}))
}

func TestDVec3Cross(t *testing.T) {
	got := DVec3{X: 1, Y: 0, Z: 0}.Cross(DVec3{X: 0, Y: 1, Z: 0})
	assert.True(t, got.Eq(DVec3{X: 0, Y: 0, Z: 1}))
}

func TestDVec3LenSq(t *testing.T) {
	assert.Equal(t, float64(14), DVec3{X: 1, Y: 2, Z: 3}.LenSq())
}

func TestDVec3Len(t *testing.T) {
	assert.Equal(t, float64(7), DVec3{X: 2, Y: 3, Z: 6}.Len())
}

func TestDVec3Normalize(t *testing.T) {
	got := DVec3{X: 0, Y: 0, Z: 5}.Normalize()
	assert.True(t, got.ApproxEq(NewDVec3(0, 0, 1), 1e-6))
}

func TestDVec3NormalizeZero(t *testing.T) {
	assert.True(t, DVec3{}.Normalize().Eq(DVec3{}))
}

func TestDVec3Dist(t *testing.T) {
	assert.Equal(t, float64(7), DVec3{}.Dist(DVec3{X: 2, Y: 3, Z: 6}))
}

func TestDVec3Lerp(t *testing.T) {
	got := DVec3{}.Lerp(DVec3{X: 10, Y: 20, Z: 30}, 0.5)
	assert.True(t, got.ApproxEq(NewDVec3(5, 10, 15), 1e-6))
}

func TestDVec3Eq(t *testing.T) {
	assert.True(t, DVec3{X: 1, Y: 2, Z: 3}.Eq(DVec3{X: 1, Y: 2, Z: 3}))
	assert.False(t, DVec3{X: 1, Y: 2, Z: 3}.Eq(DVec3{X: 1, Y: 2, Z: 4}))
}

func TestDVec3Float32(t *testing.T) {
	assert.True(t, DVec3{X: 1, Y: 2, Z: 3}.Float32().Eq(NewVec3(1, 2, 3)))
}
func TestDVec3XY(t *testing.T) {
	assert.True(t, DVec3{X: 1, Y: 2, Z: 3}.XY().Eq(DVec2{X: 1, Y: 2}))
}

// ---------------------------------------------------------------------------
// DVec4
// ---------------------------------------------------------------------------

func TestDVec4Constructor(t *testing.T) {
	v := NewDVec4(1, 2, 3, 4)
	assert.Equal(t, float64(1), v.X)
	assert.Equal(t, float64(4), v.W)
}

func TestDVec4Add(t *testing.T) {
	got := DVec4{X: 1, Y: 2, Z: 3, W: 4}.Add(DVec4{X: 5, Y: 6, Z: 7, W: 8})
	assert.True(t, got.Eq(DVec4{X: 6, Y: 8, Z: 10, W: 12}))
}

func TestDVec4Sub(t *testing.T) {
	got := DVec4{X: 5, Y: 7, Z: 9, W: 11}.Sub(DVec4{X: 1, Y: 2, Z: 3, W: 4})
	assert.True(t, got.Eq(DVec4{X: 4, Y: 5, Z: 6, W: 7}))
}

func TestDVec4Scale(t *testing.T) {
	got := DVec4{X: 1, Y: 2, Z: 3, W: 4}.Scale(2)
	assert.True(t, got.Eq(DVec4{X: 2, Y: 4, Z: 6, W: 8}))
}

func TestDVec4Dot(t *testing.T) {
	assert.Equal(t, float64(70), DVec4{X: 1, Y: 2, Z: 3, W: 4}.Dot(DVec4{X: 5, Y: 6, Z: 7, W: 8}))
}

func TestDVec4LenSq(t *testing.T) {
	assert.Equal(t, float64(25), DVec4{X: 1, Y: 2, Z: 2, W: 4}.LenSq())
}

func TestDVec4Len(t *testing.T) {
	assert.Equal(t, float64(5), DVec4{X: 1, Y: 2, Z: 2, W: 4}.Len())
}

func TestDVec4Normalize(t *testing.T) {
	got := DVec4{X: 0, Y: 0, Z: 0, W: 5}.Normalize()
	assert.True(t, got.ApproxEq(NewDVec4(0, 0, 0, 1), 1e-6))
}

func TestDVec4NormalizeZero(t *testing.T) {
	assert.True(t, DVec4{}.Normalize().Eq(DVec4{}))
}

func TestDVec4Dist(t *testing.T) {
	assert.Equal(t, float64(5), DVec4{}.Dist(DVec4{X: 1, Y: 2, Z: 2, W: 4}))
}

func TestDVec4Lerp(t *testing.T) {
	got := DVec4{}.Lerp(DVec4{X: 10, Y: 20, Z: 30, W: 40}, 0.5)
	assert.True(t, got.Eq(NewDVec4(5, 10, 15, 20)))
}

func TestDVec4Eq(t *testing.T) {
	assert.True(t, DVec4{X: 1, Y: 2, Z: 3, W: 4}.Eq(DVec4{X: 1, Y: 2, Z: 3, W: 4}))
	assert.False(t, DVec4{X: 1, Y: 2, Z: 3, W: 4}.Eq(DVec4{X: 1, Y: 2, Z: 3, W: 5}))
}

func TestDVec4Float32(t *testing.T) {
	assert.True(t, DVec4{X: 1, Y: 2, Z: 3, W: 4}.Float32().Eq(NewVec4(1, 2, 3, 4)))
}
func TestDVec4XYZ(t *testing.T) {
	assert.True(t, DVec4{X: 1, Y: 2, Z: 3, W: 4}.XYZ().Eq(DVec3{X: 1, Y: 2, Z: 3}))
}

func TestDVec4XY(t *testing.T) {
	assert.True(t, DVec4{X: 1, Y: 2, Z: 3, W: 4}.XY().Eq(DVec2{X: 1, Y: 2}))
}

// ---------------------------------------------------------------------------
// DMat2
// ---------------------------------------------------------------------------

func TestDMat2Constructor(t *testing.T) {
	m := NewDMat2(1, 2, 3, 4)
	assert.Equal(t, float64(1), m.At(0, 0))
	assert.Equal(t, float64(2), m.At(0, 1))
	assert.Equal(t, float64(3), m.At(1, 0))
	assert.Equal(t, float64(4), m.At(1, 1))
}

func TestDMat2Identity(t *testing.T) {
	m := DMat2Identity()
	assert.Equal(t, float64(1), m.At(0, 0))
	assert.Equal(t, float64(0), m.At(0, 1))
	assert.Equal(t, float64(0), m.At(1, 0))
	assert.Equal(t, float64(1), m.At(1, 1))
}

func TestDMat2Col(t *testing.T) {
	m := NewDMat2(1, 2, 3, 4)
	assert.True(t, m.Col(0).Eq(DVec2{X: 1, Y: 3}))
	assert.True(t, m.Col(1).Eq(DVec2{X: 2, Y: 4}))
}

func TestDMat2Row(t *testing.T) {
	m := NewDMat2(1, 2, 3, 4)
	assert.True(t, m.Row(0).Eq(DVec2{X: 1, Y: 2}))
	assert.True(t, m.Row(1).Eq(DVec2{X: 3, Y: 4}))
}

func TestDMat2Add(t *testing.T) {
	a := NewDMat2(1, 2, 3, 4)
	b := NewDMat2(5, 6, 7, 8)
	got := a.Add(b)
	assert.True(t, got.Eq(NewDMat2(6, 8, 10, 12)))
}

func TestDMat2Sub(t *testing.T) {
	a := NewDMat2(5, 6, 7, 8)
	b := NewDMat2(1, 2, 3, 4)
	got := a.Sub(b)
	assert.True(t, got.Eq(NewDMat2(4, 4, 4, 4)))
}

func TestDMat2Scale(t *testing.T) {
	got := NewDMat2(1, 2, 3, 4).Scale(2)
	assert.True(t, got.Eq(NewDMat2(2, 4, 6, 8)))
}

func TestDMat2Mul(t *testing.T) {
	a := NewDMat2(1, 2, 3, 4)
	b := NewDMat2(5, 6, 7, 8)
	got := a.Mul(b)
	assert.True(t, got.Eq(NewDMat2(19, 22, 43, 50)))
}

func TestDMat2MulIdentity(t *testing.T) {
	m := NewDMat2(1, 2, 3, 4)
	assert.True(t, m.Mul(DMat2Identity()).Eq(m))
}

func TestDMat2MulVec2(t *testing.T) {
	m := NewDMat2(1, 2, 3, 4)
	v := NewDVec2(5, 6)
	got := m.MulVec2(v)
	assert.True(t, got.Eq(NewDVec2(17, 39)))
}

func TestDMat2Transpose(t *testing.T) {
	m := NewDMat2(1, 2, 3, 4)
	assert.True(t, m.Transpose().Eq(NewDMat2(1, 3, 2, 4)))
}

func TestDMat2Det(t *testing.T) {
	assert.Equal(t, float64(-2), NewDMat2(1, 2, 3, 4).Det())
}

func TestDMat2Inverse(t *testing.T) {
	m := NewDMat2(1, 2, 3, 4)
	inv := m.Inverse()
	product := m.Mul(inv)
	identity := DMat2Identity()
	for r := 0; r < 2; r++ {
		for c := 0; c < 2; c++ {
			diff := product.At(r, c) - identity.At(r, c)
			assert.False(t, diff > 1e-5 || diff < -1e-5)
		}
	}
}

func TestDMat2InverseSingular(t *testing.T) {
	assert.Equal(t, DMat2{}, NewDMat2(1, 2, 2, 4).Inverse())
}

func TestDMat2Eq(t *testing.T) {
	a := NewDMat2(1, 2, 3, 4)
	assert.True(t, a.Eq(NewDMat2(1, 2, 3, 4)))
	assert.False(t, a.Eq(NewDMat2(1, 2, 3, 5)))
}

func TestDMat2Float32(t *testing.T) {
	got := NewDMat2(1, 2, 3, 4).Float32()
	assert.Equal(t, NewMat2(1, 2, 3, 4), got)
}

// ---------------------------------------------------------------------------
// DMat3
// ---------------------------------------------------------------------------

func TestDMat3Constructor(t *testing.T) {
	m := NewDMat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.Equal(t, float64(1), m.At(0, 0))
	assert.Equal(t, float64(9), m.At(2, 2))
}

func TestDMat3Identity(t *testing.T) {
	m := DMat3Identity()
	for r := 0; r < 3; r++ {
		for c := 0; c < 3; c++ {
			var want float64
			if r == c {
				want = 1
			}
			assert.Equal(t, want, m.At(r, c))
		}
	}
}

func TestDMat3Col(t *testing.T) {
	m := NewDMat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Col(1).Eq(DVec3{X: 2, Y: 5, Z: 8}))
}

func TestDMat3Row(t *testing.T) {
	m := NewDMat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Row(1).Eq(DVec3{X: 4, Y: 5, Z: 6}))
}

func TestDMat3Add(t *testing.T) {
	a := NewDMat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	b := NewDMat3(9, 8, 7, 6, 5, 4, 3, 2, 1)
	assert.True(t, a.Add(b).Eq(NewDMat3(10, 10, 10, 10, 10, 10, 10, 10, 10)))
}

func TestDMat3Sub(t *testing.T) {
	a := NewDMat3(9, 8, 7, 6, 5, 4, 3, 2, 1)
	b := NewDMat3(1, 2, 3, 4, 5, 4, 3, 2, 1)
	got := a.Sub(b)
	assert.True(t, got.Eq(NewDMat3(8, 6, 4, 2, 0, 0, 0, 0, 0)))
}

func TestDMat3Scale(t *testing.T) {
	got := NewDMat3(1, 2, 3, 4, 5, 6, 7, 8, 9).Scale(2)
	assert.True(t, got.Eq(NewDMat3(2, 4, 6, 8, 10, 12, 14, 16, 18)))
}

func TestDMat3Mul(t *testing.T) {
	m := NewDMat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Mul(DMat3Identity()).Eq(m))
}

func TestDMat3MulNonTrivial(t *testing.T) {
	a := NewDMat3(1, 2, 0, 0, 1, 1, 1, 0, 1)
	b := NewDMat3(1, 0, 1, 0, 1, 0, 1, 1, 0)
	assert.True(t, a.Mul(b).Eq(NewDMat3(1, 2, 1, 1, 2, 0, 2, 1, 1)))
}

func TestDMat3MulVec3(t *testing.T) {
	m := DMat3Identity()
	v := DVec3{X: 3, Y: 4, Z: 5}
	assert.True(t, m.MulVec3(v).Eq(v))
}

func TestDMat3Transpose(t *testing.T) {
	m := NewDMat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Transpose().Eq(NewDMat3(1, 4, 7, 2, 5, 8, 3, 6, 9)))
}

func TestDMat3Det(t *testing.T) {
	m := NewDMat3(1, 0, 0, 0, 2, 0, 0, 0, 3)
	assert.Equal(t, float64(6), m.Det())
}

func TestDMat3Inverse(t *testing.T) {
	m := NewDMat3(1, 0, 0, 0, 2, 0, 0, 0, 3)
	inv := m.Inverse()
	product := m.Mul(inv)
	identity := DMat3Identity()
	for r := 0; r < 3; r++ {
		for c := 0; c < 3; c++ {
			diff := product.At(r, c) - identity.At(r, c)
			assert.False(t, diff > 1e-4 || diff < -1e-4)
		}
	}
}

func TestDMat3InverseSingular(t *testing.T) {
	assert.Equal(t, DMat3{}, NewDMat3(1, 2, 3, 4, 5, 6, 7, 8, 9).Inverse())
}

func TestDMat3Eq(t *testing.T) {
	a := NewDMat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, a.Eq(NewDMat3(1, 2, 3, 4, 5, 6, 7, 8, 9)))
	assert.False(t, a.Eq(DMat3Identity()))
}

func TestDMat3Float32(t *testing.T) {
	got := NewDMat3(1, 2, 3, 4, 5, 6, 7, 8, 9).Float32()
	assert.Equal(t, NewMat3(1, 2, 3, 4, 5, 6, 7, 8, 9), got)
}

// ---------------------------------------------------------------------------
// DMat4
// ---------------------------------------------------------------------------

func TestDMat4Constructor(t *testing.T) {
	m := NewDMat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.Equal(t, float64(1), m.At(0, 0))
	assert.Equal(t, float64(16), m.At(3, 3))
}

func TestDMat4Identity(t *testing.T) {
	m := DMat4Identity()
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			var want float64
			if r == c {
				want = 1
			}
			assert.Equal(t, want, m.At(r, c))
		}
	}
}

func TestDMat4Col(t *testing.T) {
	m := NewDMat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Col(2).Eq(DVec4{X: 3, Y: 7, Z: 11, W: 15}))
}

func TestDMat4Row(t *testing.T) {
	m := NewDMat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Row(2).Eq(DVec4{X: 9, Y: 10, Z: 11, W: 12}))
}

func TestDMat4Add(t *testing.T) {
	a := DMat4Identity()
	got := a.Add(a)
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			assert.Equal(t, a.At(r, c)*2, got.At(r, c))
		}
	}
}

func TestDMat4Sub(t *testing.T) {
	a := DMat4Identity()
	assert.True(t, a.Sub(a).Eq(DMat4{}))
}

func TestDMat4Scale(t *testing.T) {
	m := DMat4Identity()
	got := m.Scale(3)
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			assert.Equal(t, m.At(r, c)*3, got.At(r, c))
		}
	}
}

func TestDMat4Mul(t *testing.T) {
	m := NewDMat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Mul(DMat4Identity()).Eq(m))
}

func TestDMat4MulVec4(t *testing.T) {
	v := DVec4{X: 1, Y: 2, Z: 3, W: 4}
	assert.True(t, DMat4Identity().MulVec4(v).Eq(v))
}

func TestDMat4Transpose(t *testing.T) {
	m := NewDMat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	want := NewDMat4(1, 5, 9, 13, 2, 6, 10, 14, 3, 7, 11, 15, 4, 8, 12, 16)
	assert.True(t, m.Transpose().Eq(want))
}

func TestDMat4TransposeDouble(t *testing.T) {
	m := NewDMat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Transpose().Transpose().Eq(m))
}

func TestDMat4Det(t *testing.T) {
	m := NewDMat4(1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4)
	assert.Equal(t, float64(24), m.Det())
}

func TestDMat4Inverse(t *testing.T) {
	m := NewDMat4(1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 1)
	inv := m.Inverse()
	product := m.Mul(inv)
	identity := DMat4Identity()
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			diff := product.At(r, c) - identity.At(r, c)
			assert.False(t, diff > 1e-4 || diff < -1e-4)
		}
	}
}

func TestDMat4InverseSingular(t *testing.T) {
	m := NewDMat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.Equal(t, DMat4{}, m.Inverse())
}

func TestDMat4Mat3(t *testing.T) {
	m := NewDMat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Mat3().Eq(NewDMat3(1, 2, 3, 5, 6, 7, 9, 10, 11)))
}

func TestDMat4Eq(t *testing.T) {
	assert.True(t, DMat4Identity().Eq(DMat4Identity()))
	assert.False(t, DMat4Identity().Eq(DMat4{}))
}

func TestDMat4Float32(t *testing.T) {
	assert.Equal(t, Mat4Identity(), DMat4Identity().Float32())
}

// ---------------------------------------------------------------------------
// D Graphics helpers
// ---------------------------------------------------------------------------

func TestDTranslation(t *testing.T) {
	m := DTranslation(NewDVec3(2, 3, 4))
	v := NewDVec4(1, 1, 1, 1)
	got := m.MulVec4(v)
	want := NewDVec4(3, 4, 5, 1)
	assert.True(t, got.Eq(want))
}

func TestDScaling(t *testing.T) {
	m := DScaling(NewDVec3(2, 3, 4))
	v := NewDVec4(1, 1, 1, 1)
	got := m.MulVec4(v)
	want := NewDVec4(2, 3, 4, 1)
	assert.True(t, got.Eq(want))
}

func TestDRotationX(t *testing.T) {
	m := DRotationX(float64(stdmath.Pi / 2))
	v := NewDVec4(0, 1, 0, 1)
	got := m.MulVec4(v)
	want := NewDVec4(0, 0, 1, 1)
	assert.True(t, got.ApproxEq(want, 1e-5))
}

func TestDRotationY(t *testing.T) {
	m := DRotationY(float64(stdmath.Pi / 2))
	v := NewDVec4(1, 0, 0, 1)
	got := m.MulVec4(v)
	want := NewDVec4(0, 0, -1, 1)
	assert.True(t, got.ApproxEq(want, 1e-5))
}

func TestDRotationZ(t *testing.T) {
	m := DRotationZ(float64(stdmath.Pi / 2))
	v := NewDVec4(1, 0, 0, 1)
	got := m.MulVec4(v)
	want := NewDVec4(0, 1, 0, 1)
	assert.True(t, got.ApproxEq(want, 1e-5))
}

func TestDLookAt(t *testing.T) {
	eye := NewDVec3(0, 0, 5)
	center := NewDVec3(0, 0, 0)
	up := NewDVec3(0, 1, 0)
	m := DLookAt(eye, center, up)
	v := m.MulVec4(NewDVec4(0, 0, 0, 1))
	assert.True(t, v.ApproxEq(NewDVec4(0, 0, -5, 1), 1e-5))
}

func TestDPerspective(t *testing.T) {
	m := DPerspective(float64(stdmath.Pi/4), 1.0, 0.1, 100.0)
	v := m.MulVec4(NewDVec4(0, 0, -0.1, 1))
	ndc := v.Scale(1.0 / v.W)
	assert.False(t, ndc.Z < -1.01 || ndc.Z > -0.99)
}

func TestDOrtho(t *testing.T) {
	m := DOrtho(-1, 1, -1, 1, -1, 1)
	v := m.MulVec4(NewDVec4(0, 0, 0, 1))
	want := NewDVec4(0, 0, 0, 1)
	assert.True(t, v.ApproxEq(want, 1e-5))
}

// ---------------------------------------------------------------------------
// DQuat
// ---------------------------------------------------------------------------

func TestDQuatConstructor(t *testing.T) {
	q := NewDQuat(1, 2, 3, 4)
	assert.Equal(t, float64(1), q.W)
	assert.Equal(t, float64(2), q.X)
	assert.Equal(t, float64(3), q.Y)
	assert.Equal(t, float64(4), q.Z)
}

func TestDQuatIdentity(t *testing.T) {
	q := DQuatIdentity()
	assert.Equal(t, float64(1), q.W)
	assert.Equal(t, float64(0), q.X)
	assert.Equal(t, float64(0), q.Y)
	assert.Equal(t, float64(0), q.Z)
}

func TestDQuatFromAxisAngle(t *testing.T) {
	q := DQuatFromAxisAngle(NewDVec3(0, 0, 1), float64(stdmath.Pi/2))
	s := float64(stdmath.Sin(stdmath.Pi / 4))
	c := float64(stdmath.Cos(stdmath.Pi / 4))
	want := NewDQuat(c, 0, 0, s)
	assert.True(t, q.ApproxEq(want, 1e-5))
}

func TestDQuatAdd(t *testing.T) {
	a := NewDQuat(1, 2, 3, 4)
	b := NewDQuat(5, 6, 7, 8)
	got := a.Add(b)
	assert.True(t, got.Eq(NewDQuat(6, 8, 10, 12)))
}

func TestDQuatSub(t *testing.T) {
	a := NewDQuat(5, 7, 9, 11)
	b := NewDQuat(1, 2, 3, 4)
	got := a.Sub(b)
	assert.True(t, got.Eq(NewDQuat(4, 5, 6, 7)))
}

func TestDQuatScale(t *testing.T) {
	got := NewDQuat(1, 2, 3, 4).Scale(2)
	assert.True(t, got.Eq(NewDQuat(2, 4, 6, 8)))
}

func TestDQuatMul(t *testing.T) {
	q := NewDQuat(1, 2, 3, 4)
	id := DQuatIdentity()
	assert.True(t, id.Mul(q).Eq(q))
}

func TestDQuatMulKnown(t *testing.T) {
	a := NewDQuat(1, 0, 1, 0)
	b := NewDQuat(1, 0.5, 0.5, 0.75)
	got := a.Mul(b)
	want := NewDQuat(0.5, 1.25, 1.5, 0.25)
	assert.True(t, got.ApproxEq(want, 1e-5))
}

func TestDQuatMulNonCommutative(t *testing.T) {
	a := NewDQuat(1, 2, 3, 4)
	b := NewDQuat(5, 6, 7, 8)
	assert.False(t, a.Mul(b).Eq(b.Mul(a)))
}

func TestDQuatDot(t *testing.T) {
	a := NewDQuat(1, 2, 3, 4)
	b := NewDQuat(5, 6, 7, 8)
	assert.Equal(t, float64(70), a.Dot(b))
}

func TestDQuatLenSq(t *testing.T) {
	assert.Equal(t, float64(30), NewDQuat(1, 2, 3, 4).LenSq())
}

func TestDQuatLen(t *testing.T) {
	q := NewDQuat(1, 0, 0, 0)
	assert.Equal(t, float64(1), q.Len())
}

func TestDQuatNormalize(t *testing.T) {
	q := NewDQuat(0, 0, 0, 5).Normalize()
	want := NewDQuat(0, 0, 0, 1)
	assert.True(t, q.ApproxEq(want, 1e-6))
}

func TestDQuatNormalizeZero(t *testing.T) {
	assert.True(t, DQuat{}.Normalize().Eq(DQuat{}))
}

func TestDQuatConjugate(t *testing.T) {
	q := NewDQuat(1, 2, 3, 4)
	c := q.Conjugate()
	assert.Equal(t, float64(1), c.W)
	assert.Equal(t, float64(-2), c.X)
	assert.Equal(t, float64(-3), c.Y)
	assert.Equal(t, float64(-4), c.Z)
}

func TestDQuatInverse(t *testing.T) {
	q := NewDQuat(1, 2, 3, 4).Normalize()
	product := q.Mul(q.Inverse())
	assert.True(t, product.ApproxEq(DQuatIdentity(), 1e-5))
}

func TestDQuatInverseZero(t *testing.T) {
	assert.True(t, DQuat{}.Inverse().Eq(DQuat{}))
}

func TestDQuatLerp(t *testing.T) {
	a := NewDQuat(0, 0, 0, 0)
	b := NewDQuat(2, 4, 6, 8)
	got := a.Lerp(b, 0.5)
	assert.True(t, got.Eq(NewDQuat(1, 2, 3, 4)))
}

func TestDQuatSlerpEndpoints(t *testing.T) {
	a := DQuatFromAxisAngle(NewDVec3(0, 0, 1), 0)
	b := DQuatFromAxisAngle(NewDVec3(0, 0, 1), float64(stdmath.Pi/2))
	assert.True(t, a.Slerp(b, 0).ApproxEq(a, 1e-5))
	assert.True(t, a.Slerp(b, 1).ApproxEq(b, 1e-5))
}

func TestDQuatSlerp(t *testing.T) {
	a := DQuatFromAxisAngle(NewDVec3(0, 0, 1), 0)
	b := DQuatFromAxisAngle(NewDVec3(0, 0, 1), float64(stdmath.Pi/2))
	mid := a.Slerp(b, 0.5)
	want := DQuatFromAxisAngle(NewDVec3(0, 0, 1), float64(stdmath.Pi/4))
	assert.True(t, mid.ApproxEq(want, 1e-5))
}

func TestDQuatRotateVec3(t *testing.T) {
	q := DQuatFromAxisAngle(NewDVec3(0, 0, 1), float64(stdmath.Pi/2))
	v := NewDVec3(1, 0, 0)
	got := q.RotateVec3(v)
	want := NewDVec3(0, 1, 0)
	assert.True(t, got.ApproxEq(want, 1e-5))
}

func TestDQuatToMat4(t *testing.T) {
	angle := float64(stdmath.Pi / 4)
	q := DQuatFromAxisAngle(NewDVec3(0, 0, 1), angle)
	got := q.ToMat4()
	want := DRotationZ(angle)
	assert.True(t, got.ApproxEq(want, 1e-5))
}

func TestDQuatEq(t *testing.T) {
	a := NewDQuat(1, 2, 3, 4)
	assert.True(t, a.Eq(NewDQuat(1, 2, 3, 4)))
	assert.False(t, a.Eq(NewDQuat(1, 2, 3, 5)))
}

func TestDQuatApproxEq(t *testing.T) {
	a := NewDQuat(1.0, 2.0, 3.0, 4.0)
	b := NewDQuat(1.0001, 2.0001, 3.0001, 4.0001)
	assert.True(t, a.ApproxEq(b, 0.001))
	assert.False(t, a.ApproxEq(b, 0.00001))
}

func TestDQuatJSON(t *testing.T) {
	q := NewDQuat(1, 2, 3, 4)
	data, err := q.MarshalJSON()
	assert.Equal(t, nil, err)
	var q2 DQuat
	err = q2.UnmarshalJSON(data)
	assert.Equal(t, nil, err)
	assert.True(t, q.Eq(q2))
}

func TestDQuatFloat32(t *testing.T) {
	got := NewDQuat(1, 2, 3, 4).Float32()
	assert.True(t, got.Eq(NewQuat(1, 2, 3, 4)))
}

// ---------------------------------------------------------------------------
// DEulerAngles
// ---------------------------------------------------------------------------

func TestDEulerAnglesConstructor(t *testing.T) {
	e := NewDEulerAngles(1, 2, 3)
	assert.Equal(t, float64(1), e.Pitch)
	assert.Equal(t, float64(2), e.Yaw)
	assert.Equal(t, float64(3), e.Roll)
}

func TestDEulerAnglesToQuatIdentity(t *testing.T) {
	e := NewDEulerAngles(0, 0, 0)
	assert.True(t, e.ToQuat().ApproxEq(DQuatIdentity(), 1e-6))
}

func TestDEulerAnglesToQuatPitchOnly(t *testing.T) {
	angle := float64(stdmath.Pi / 4)
	e := NewDEulerAngles(angle, 0, 0)
	want := DQuatFromAxisAngle(NewDVec3(1, 0, 0), angle)
	assert.True(t, e.ToQuat().ApproxEq(want, 1e-5))
}

func TestDEulerAnglesToQuatYawOnly(t *testing.T) {
	angle := float64(stdmath.Pi / 3)
	e := NewDEulerAngles(0, angle, 0)
	want := DQuatFromAxisAngle(NewDVec3(0, 1, 0), angle)
	assert.True(t, e.ToQuat().ApproxEq(want, 1e-5))
}

func TestDEulerAnglesToQuatRollOnly(t *testing.T) {
	angle := float64(stdmath.Pi / 6)
	e := NewDEulerAngles(0, 0, angle)
	want := DQuatFromAxisAngle(NewDVec3(0, 0, 1), angle)
	assert.True(t, e.ToQuat().ApproxEq(want, 1e-5))
}

func TestDEulerAnglesRoundTrip(t *testing.T) {
	e := NewDEulerAngles(0.3, 0.5, 0.7)
	got := DEulerAnglesFromQuat(e.ToQuat())
	assert.True(t, got.ApproxEq(e, 1e-5))
}

func TestDEulerAnglesFromQuatIdentity(t *testing.T) {
	got := DEulerAnglesFromQuat(DQuatIdentity())
	assert.True(t, got.ApproxEq(NewDEulerAngles(0, 0, 0), 1e-6))
}

func TestDEulerAnglesEq(t *testing.T) {
	a := NewDEulerAngles(1, 2, 3)
	assert.True(t, a.Eq(NewDEulerAngles(1, 2, 3)))
	assert.False(t, a.Eq(NewDEulerAngles(1, 2, 4)))
}

func TestDEulerAnglesApproxEq(t *testing.T) {
	a := NewDEulerAngles(1.0, 2.0, 3.0)
	b := NewDEulerAngles(1.0001, 2.0001, 3.0001)
	assert.True(t, a.ApproxEq(b, 0.001))
	assert.False(t, a.ApproxEq(b, 0.00001))
}

func TestDEulerAnglesJSON(t *testing.T) {
	e := NewDEulerAngles(1, 2, 3)
	data, err := e.MarshalJSON()
	assert.Equal(t, nil, err)
	var e2 DEulerAngles
	err = e2.UnmarshalJSON(data)
	assert.Equal(t, nil, err)
	assert.True(t, e.Eq(e2))
}

func TestDEulerAnglesFloat32(t *testing.T) {
	got := NewDEulerAngles(1, 2, 3).Float32()
	assert.True(t, got.Eq(NewEulerAngles(1, 2, 3)))
}

// ensure stdmath import is used
var _ = stdmath.Pi
