// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	"encoding/json"
	"math"
)

// DEulerAngles represents rotation as Euler angles using intrinsic XYZ convention.
// Pitch (X) is applied first, then Yaw (Y), then Roll (Z). All angles are in radians.
type DEulerAngles struct {
	Pitch float64 // rotation around X axis (applied first)
	Yaw   float64 // rotation around Y axis (applied second)
	Roll  float64 // rotation around Z axis (applied third)
}

func NewDEulerAngles(pitch, yaw, roll float64) DEulerAngles {
	return DEulerAngles{Pitch: pitch, Yaw: yaw, Roll: roll}
}

// ToQuat converts Euler angles to a quaternion.
// Composition order: Qz(roll) * Qy(yaw) * Qx(pitch).
func (e DEulerAngles) ToQuat() DQuat {
	cp := float64(math.Cos(float64(e.Pitch * 0.5)))
	sp := float64(math.Sin(float64(e.Pitch * 0.5)))
	cy := float64(math.Cos(float64(e.Yaw * 0.5)))
	sy := float64(math.Sin(float64(e.Yaw * 0.5)))
	cr := float64(math.Cos(float64(e.Roll * 0.5)))
	sr := float64(math.Sin(float64(e.Roll * 0.5)))

	return DQuat{
		W: cr*cy*cp + sr*sy*sp,
		X: cr*cy*sp - sr*sy*cp,
		Y: cr*sy*cp + sr*cy*sp,
		Z: sr*cy*cp - cr*sy*sp,
	}
}

// DEulerAnglesFromQuat extracts Euler angles from a quaternion using intrinsic XYZ convention.
func DEulerAnglesFromQuat(q DQuat) DEulerAngles {
	// Yaw (Y) — the gimbal-lock axis for XYZ intrinsic
	siny := 2 * (q.W*q.Y - q.X*q.Z)
	var yaw float64
	if siny >= 1 {
		yaw = float64(math.Pi / 2)
	} else if siny <= -1 {
		yaw = -float64(math.Pi / 2)
	} else {
		yaw = float64(math.Asin(float64(siny)))
	}

	// Pitch (X)
	pitch := float64(math.Atan2(
		float64(2*(q.Y*q.Z+q.W*q.X)),
		float64(1-2*(q.X*q.X+q.Y*q.Y)),
	))

	// Roll (Z)
	roll := float64(math.Atan2(
		float64(2*(q.X*q.Y+q.W*q.Z)),
		float64(1-2*(q.Y*q.Y+q.Z*q.Z)),
	))

	return DEulerAngles{Pitch: pitch, Yaw: yaw, Roll: roll}
}

func (a DEulerAngles) Eq(b DEulerAngles) bool {
	return a.Pitch == b.Pitch && a.Yaw == b.Yaw && a.Roll == b.Roll
}

func (a DEulerAngles) ApproxEq(b DEulerAngles, eps float64) bool {
	return abs(a.Pitch-b.Pitch) <= eps && abs(a.Yaw-b.Yaw) <= eps && abs(a.Roll-b.Roll) <= eps
}

func (e DEulerAngles) Float32() EulerAngles {
	return EulerAngles{Pitch: float32(e.Pitch), Yaw: float32(e.Yaw), Roll: float32(e.Roll)}
}

func (e DEulerAngles) MarshalJSON() ([]byte, error) {
	return json.Marshal([3]float64{e.Pitch, e.Yaw, e.Roll})
}

func (e *DEulerAngles) UnmarshalJSON(data []byte) error {
	var arr [3]float64
	if err := json.Unmarshal(data, &arr); err != nil {
		return err
	}
	e.Pitch = arr[0]
	e.Yaw = arr[1]
	e.Roll = arr[2]
	return nil
}
