// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// DMat2 is a 2x2 float64 matrix in column-major order.
type DMat2 struct {
	Data [4]float64
}

// NewDMat2 creates a 2x2 matrix from row-major arguments.
func NewDMat2(
	m00, m01 float64,
	m10, m11 float64,
) DMat2 {
	return DMat2{Data: [4]float64{
		m00, m10, // col 0
		m01, m11, // col 1
	}}
}

func DMat2Identity() DMat2 {
	return NewDMat2(1, 0, 0, 1)
}

func (m DMat2) Col(c int) DVec2 {
	i := c * 2
	return DVec2{X: m.Data[i+0], Y: m.Data[i+1]}
}

func (m DMat2) Row(r int) DVec2 {
	return DVec2{X: m.Data[r+0], Y: m.Data[r+2]}
}

func (m DMat2) At(row, col int) float64 {
	return m.Data[col*2+row]
}

func (a DMat2) Add(b DMat2) DMat2 {
	var out DMat2
	for i := range out.Data {
		out.Data[i] = a.Data[i] + b.Data[i]
	}
	return out
}

func (a DMat2) Sub(b DMat2) DMat2 {
	var out DMat2
	for i := range out.Data {
		out.Data[i] = a.Data[i] - b.Data[i]
	}
	return out
}

func (m DMat2) Scale(s float64) DMat2 {
	var out DMat2
	for i := range out.Data {
		out.Data[i] = m.Data[i] * s
	}
	return out
}

func (a DMat2) Mul(b DMat2) DMat2 {
	var out DMat2
	for c := 0; c < 2; c++ {
		bc := b.Col(c)
		for r := 0; r < 2; r++ {
			out.Data[c*2+r] = a.Row(r).Dot(bc)
		}
	}
	return out
}

func (m DMat2) MulVec2(v DVec2) DVec2 {
	return DVec2{
		X: m.Row(0).Dot(v),
		Y: m.Row(1).Dot(v),
	}
}

func (m DMat2) Transpose() DMat2 {
	var out DMat2
	for r := 0; r < 2; r++ {
		for c := 0; c < 2; c++ {
			out.Data[c*2+r] = m.Data[r*2+c]
		}
	}
	return out
}

func (m DMat2) Det() float64 {
	return m.Data[0]*m.Data[3] - m.Data[2]*m.Data[1]
}

func (m DMat2) Inverse() DMat2 {
	d := m.Det()
	if d == 0 {
		return DMat2{}
	}
	invD := 1.0 / d
	return DMat2{Data: [4]float64{
		m.Data[3] * invD, -m.Data[1] * invD,
		-m.Data[2] * invD, m.Data[0] * invD,
	}}
}
func (a DMat2) Eq(b DMat2) bool {
	for i := range a.Data {
		if a.Data[i] != b.Data[i] {
			return false
		}
	}
	return true
}

func (a DMat2) ApproxEq(b DMat2, eps float64) bool {
	for i := range a.Data {
		if abs(a.Data[i]-b.Data[i]) > eps {
			return false
		}
	}
	return true
}

func (m DMat2) Float32() Mat2 {
	var out Mat2
	for i := range m.Data {
		out.Data[i] = float32(m.Data[i])
	}
	return out
}

// ensure math import is used
var _ = math.Sqrt
