// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// DMat3 is a 3x3 float64 matrix in column-major order.
type DMat3 struct {
	Data [9]float64
}

// NewDMat3 creates a 3x3 matrix from row-major arguments.
func NewDMat3(
	m00, m01, m02 float64,
	m10, m11, m12 float64,
	m20, m21, m22 float64,
) DMat3 {
	return DMat3{Data: [9]float64{
		m00, m10, m20, // col 0
		m01, m11, m21, // col 1
		m02, m12, m22, // col 2
	}}
}

func DMat3Identity() DMat3 {
	return NewDMat3(1, 0, 0, 0, 1, 0, 0, 0, 1)
}

func (m DMat3) Col(c int) DVec3 {
	i := c * 3
	return DVec3{X: m.Data[i+0], Y: m.Data[i+1], Z: m.Data[i+2]}
}

func (m DMat3) Row(r int) DVec3 {
	return DVec3{X: m.Data[r+0], Y: m.Data[r+3], Z: m.Data[r+6]}
}

func (m DMat3) At(row, col int) float64 {
	return m.Data[col*3+row]
}

func (a DMat3) Add(b DMat3) DMat3 {
	var out DMat3
	for i := range out.Data {
		out.Data[i] = a.Data[i] + b.Data[i]
	}
	return out
}

func (a DMat3) Sub(b DMat3) DMat3 {
	var out DMat3
	for i := range out.Data {
		out.Data[i] = a.Data[i] - b.Data[i]
	}
	return out
}

func (m DMat3) Scale(s float64) DMat3 {
	var out DMat3
	for i := range out.Data {
		out.Data[i] = m.Data[i] * s
	}
	return out
}

func (a DMat3) Mul(b DMat3) DMat3 {
	var out DMat3
	for c := 0; c < 3; c++ {
		bc := b.Col(c)
		for r := 0; r < 3; r++ {
			out.Data[c*3+r] = a.Row(r).Dot(bc)
		}
	}
	return out
}

func (m DMat3) MulVec3(v DVec3) DVec3 {
	return DVec3{
		X: m.Row(0).Dot(v),
		Y: m.Row(1).Dot(v),
		Z: m.Row(2).Dot(v),
	}
}

func (m DMat3) Transpose() DMat3 {
	var out DMat3
	for r := 0; r < 3; r++ {
		for c := 0; c < 3; c++ {
			out.Data[c*3+r] = m.Data[r*3+c]
		}
	}
	return out
}

func (m DMat3) Det() float64 {
	return m.At(0, 0)*(m.At(1, 1)*m.At(2, 2)-m.At(1, 2)*m.At(2, 1)) -
		m.At(0, 1)*(m.At(1, 0)*m.At(2, 2)-m.At(1, 2)*m.At(2, 0)) +
		m.At(0, 2)*(m.At(1, 0)*m.At(2, 1)-m.At(1, 1)*m.At(2, 0))
}

func (m DMat3) Inverse() DMat3 {
	d := m.Det()
	if d == 0 {
		return DMat3{}
	}
	invD := 1.0 / d

	return NewDMat3(
		(m.At(1, 1)*m.At(2, 2)-m.At(1, 2)*m.At(2, 1))*invD,
		(m.At(0, 2)*m.At(2, 1)-m.At(0, 1)*m.At(2, 2))*invD,
		(m.At(0, 1)*m.At(1, 2)-m.At(0, 2)*m.At(1, 1))*invD,

		(m.At(1, 2)*m.At(2, 0)-m.At(1, 0)*m.At(2, 2))*invD,
		(m.At(0, 0)*m.At(2, 2)-m.At(0, 2)*m.At(2, 0))*invD,
		(m.At(0, 2)*m.At(1, 0)-m.At(0, 0)*m.At(1, 2))*invD,

		(m.At(1, 0)*m.At(2, 1)-m.At(1, 1)*m.At(2, 0))*invD,
		(m.At(0, 1)*m.At(2, 0)-m.At(0, 0)*m.At(2, 1))*invD,
		(m.At(0, 0)*m.At(1, 1)-m.At(0, 1)*m.At(1, 0))*invD,
	)
}
func (a DMat3) Eq(b DMat3) bool {
	for i := range a.Data {
		if a.Data[i] != b.Data[i] {
			return false
		}
	}
	return true
}

func (a DMat3) ApproxEq(b DMat3, eps float64) bool {
	for i := range a.Data {
		if abs(a.Data[i]-b.Data[i]) > eps {
			return false
		}
	}
	return true
}

func (m DMat3) Float32() Mat3 {
	var out Mat3
	for i := range m.Data {
		out.Data[i] = float32(m.Data[i])
	}
	return out
}

// ensure math import is used
var _ = math.Sqrt
