// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// DMat4 is a 4x4 float64 matrix in column-major order.
type DMat4 struct {
	Data [16]float64
}

// NewDMat4 creates a 4x4 matrix from row-major arguments.
func NewDMat4(
	m00, m01, m02, m03 float64,
	m10, m11, m12, m13 float64,
	m20, m21, m22, m23 float64,
	m30, m31, m32, m33 float64,
) DMat4 {
	return DMat4{Data: [16]float64{
		m00, m10, m20, m30, // col 0
		m01, m11, m21, m31, // col 1
		m02, m12, m22, m32, // col 2
		m03, m13, m23, m33, // col 3
	}}
}

func DMat4Identity() DMat4 {
	return NewDMat4(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1)
}

func (m DMat4) Col(c int) DVec4 {
	i := c * 4
	return DVec4{X: m.Data[i+0], Y: m.Data[i+1], Z: m.Data[i+2], W: m.Data[i+3]}
}

func (m DMat4) Row(r int) DVec4 {
	return DVec4{X: m.Data[r+0], Y: m.Data[r+4], Z: m.Data[r+8], W: m.Data[r+12]}
}

func (m DMat4) At(row, col int) float64 {
	return m.Data[col*4+row]
}

func (a DMat4) Add(b DMat4) DMat4 {
	var out DMat4
	for i := range out.Data {
		out.Data[i] = a.Data[i] + b.Data[i]
	}
	return out
}

func (a DMat4) Sub(b DMat4) DMat4 {
	var out DMat4
	for i := range out.Data {
		out.Data[i] = a.Data[i] - b.Data[i]
	}
	return out
}

func (m DMat4) Scale(s float64) DMat4 {
	var out DMat4
	for i := range out.Data {
		out.Data[i] = m.Data[i] * s
	}
	return out
}

func (a DMat4) Mul(b DMat4) DMat4 {
	var out DMat4
	for c := 0; c < 4; c++ {
		bc := b.Col(c)
		for r := 0; r < 4; r++ {
			out.Data[c*4+r] = a.Row(r).Dot(bc)
		}
	}
	return out
}

func (m DMat4) MulVec4(v DVec4) DVec4 {
	return DVec4{
		X: m.Row(0).Dot(v),
		Y: m.Row(1).Dot(v),
		Z: m.Row(2).Dot(v),
		W: m.Row(3).Dot(v),
	}
}

func (m DMat4) Transpose() DMat4 {
	var out DMat4
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			out.Data[c*4+r] = m.Data[r*4+c]
		}
	}
	return out
}

func (m DMat4) cofactor(row, col int) float64 {
	var sub [9]float64
	idx := 0
	for c := 0; c < 4; c++ {
		if c == col {
			continue
		}
		for r := 0; r < 4; r++ {
			if r == row {
				continue
			}
			sub[idx] = m.At(r, c)
			idx++
		}
	}
	return sub[0]*(sub[4]*sub[8]-sub[5]*sub[7]) -
		sub[3]*(sub[1]*sub[8]-sub[2]*sub[7]) +
		sub[6]*(sub[1]*sub[5]-sub[2]*sub[4])
}

func (m DMat4) Det() float64 {
	a, b, c, d := m.At(0, 0), m.At(0, 1), m.At(0, 2), m.At(0, 3)
	return a*m.cofactor(0, 0) - b*m.cofactor(0, 1) + c*m.cofactor(0, 2) - d*m.cofactor(0, 3)
}

func (m DMat4) Inverse() DMat4 {
	d := m.Det()
	if d == 0 {
		return DMat4{}
	}
	invD := 1.0 / d

	var out DMat4
	for c := 0; c < 4; c++ {
		for r := 0; r < 4; r++ {
			sign := float64(1)
			if (r+c)%2 != 0 {
				sign = -1
			}
			out.Data[c*4+r] = sign * m.cofactor(c, r) * invD
		}
	}
	return out
}

func (m DMat4) Mat3() DMat3 {
	return DMat3{Data: [9]float64{
		m.Data[0], m.Data[1], m.Data[2],
		m.Data[4], m.Data[5], m.Data[6],
		m.Data[8], m.Data[9], m.Data[10],
	}}
}
func (a DMat4) Eq(b DMat4) bool {
	for i := range a.Data {
		if a.Data[i] != b.Data[i] {
			return false
		}
	}
	return true
}

func (a DMat4) ApproxEq(b DMat4, eps float64) bool {
	for i := range a.Data {
		if abs(a.Data[i]-b.Data[i]) > eps {
			return false
		}
	}
	return true
}

func (m DMat4) Float32() Mat4 {
	var out Mat4
	for i := range m.Data {
		out.Data[i] = float32(m.Data[i])
	}
	return out
}

// ensure math import is used
var _ = math.Sqrt
