// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	"encoding/json"
	"math"
)

// DQuat is a float64 quaternion with scalar part W and vector part (X, Y, Z).
type DQuat struct {
	W float64
	X float64
	Y float64
	Z float64
}

func NewDQuat(w, x, y, z float64) DQuat {
	return DQuat{W: w, X: x, Y: y, Z: z}
}

func DQuatIdentity() DQuat {
	return DQuat{W: 1}
}

func DQuatFromAxisAngle(axis DVec3, angle float64) DQuat {
	halfAngle := angle * 0.5
	s := float64(math.Sin(float64(halfAngle)))
	c := float64(math.Cos(float64(halfAngle)))
	n := axis.Normalize()
	return DQuat{W: c, X: n.X * s, Y: n.Y * s, Z: n.Z * s}
}

func (a DQuat) Add(b DQuat) DQuat {
	return DQuat{
		W: a.W + b.W,
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
	}
}

func (a DQuat) Sub(b DQuat) DQuat {
	return DQuat{
		W: a.W - b.W,
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
	}
}

func (v DQuat) Scale(s float64) DQuat {
	return DQuat{
		W: v.W * s,
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
	}
}

func (a DQuat) Mul(b DQuat) DQuat {
	return DQuat{
		W: a.W*b.W - a.X*b.X - a.Y*b.Y - a.Z*b.Z,
		X: a.W*b.X + a.X*b.W + a.Y*b.Z - a.Z*b.Y,
		Y: a.W*b.Y - a.X*b.Z + a.Y*b.W + a.Z*b.X,
		Z: a.W*b.Z + a.X*b.Y - a.Y*b.X + a.Z*b.W,
	}
}

func (a DQuat) Dot(b DQuat) float64 {
	return a.W*b.W + a.X*b.X + a.Y*b.Y + a.Z*b.Z
}

func (v DQuat) LenSq() float64 {
	return v.Dot(v)
}

func (v DQuat) Len() float64 {
	return math.Sqrt(v.Dot(v))
}

func (v DQuat) Normalize() DQuat {
	l := v.Len()
	if l == 0 {
		return DQuat{}
	}
	return v.Scale(1.0 / l)
}

func (v DQuat) Conjugate() DQuat {
	return DQuat{W: v.W, X: -v.X, Y: -v.Y, Z: -v.Z}
}

func (v DQuat) Inverse() DQuat {
	lenSq := v.LenSq()
	if lenSq == 0 {
		return DQuat{}
	}
	return v.Conjugate().Scale(1.0 / lenSq)
}

func (a DQuat) Lerp(b DQuat, t float64) DQuat {
	return a.Add(b.Sub(a).Scale(t))
}

func (a DQuat) Slerp(b DQuat, t float64) DQuat {
	dot := a.Dot(b)
	bq := b
	if dot < 0 {
		bq = b.Scale(-1)
		dot = -dot
	}
	if dot > 0.9995 {
		return a.Lerp(bq, t).Normalize()
	}
	theta := float64(math.Acos(float64(dot)))
	sinTheta := float64(math.Sin(float64(theta)))
	wa := float64(math.Sin(float64((1-t)*theta))) / sinTheta
	wb := float64(math.Sin(float64(t*theta))) / sinTheta
	return a.Scale(wa).Add(bq.Scale(wb))
}

func (q DQuat) RotateVec3(v DVec3) DVec3 {
	u := DVec3{X: q.X, Y: q.Y, Z: q.Z}
	s := q.W
	return u.Scale(2 * u.Dot(v)).Add(v.Scale(s*s - u.Dot(u))).Add(u.Cross(v).Scale(2 * s))
}

func (q DQuat) ToMat4() DMat4 {
	xx := q.X * q.X
	yy := q.Y * q.Y
	zz := q.Z * q.Z
	xy := q.X * q.Y
	xz := q.X * q.Z
	yz := q.Y * q.Z
	wx := q.W * q.X
	wy := q.W * q.Y
	wz := q.W * q.Z

	return NewDMat4(
		1-2*(yy+zz), 2*(xy-wz), 2*(xz+wy), 0,
		2*(xy+wz), 1-2*(xx+zz), 2*(yz-wx), 0,
		2*(xz-wy), 2*(yz+wx), 1-2*(xx+yy), 0,
		0, 0, 0, 1,
	)
}

func (a DQuat) Eq(b DQuat) bool {
	return a.W == b.W && a.X == b.X && a.Y == b.Y && a.Z == b.Z
}

func (a DQuat) ApproxEq(b DQuat, eps float64) bool {
	return abs(a.W-b.W) <= eps && abs(a.X-b.X) <= eps && abs(a.Y-b.Y) <= eps && abs(a.Z-b.Z) <= eps
}

func (v DQuat) Float32() Quat {
	return Quat{W: float32(v.W), X: float32(v.X), Y: float32(v.Y), Z: float32(v.Z)}
}

func (v DQuat) MarshalJSON() ([]byte, error) {
	return json.Marshal([4]float64{v.W, v.X, v.Y, v.Z})
}

func (v *DQuat) UnmarshalJSON(data []byte) error {
	var arr [4]float64
	if err := json.Unmarshal(data, &arr); err != nil {
		return err
	}
	v.W = arr[0]
	v.X = arr[1]
	v.Y = arr[2]
	v.Z = arr[3]
	return nil
}
