// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	"encoding/json"
	"math"
)

// DVec2 is a 2-component float64 vector.
type DVec2 struct {
	X float64
	Y float64
}

func NewDVec2(x float64, y float64) DVec2 {
	return DVec2{X: x, Y: y}
}

func (a DVec2) Add(b DVec2) DVec2 {
	return DVec2{
		X: a.X + b.X,
		Y: a.Y + b.Y,
	}
}

func (a DVec2) Sub(b DVec2) DVec2 {
	return DVec2{
		X: a.X - b.X,
		Y: a.Y - b.Y,
	}
}

func (v DVec2) Scale(s float64) DVec2 {
	return DVec2{
		X: v.X * s,
		Y: v.Y * s,
	}
}

func (a DVec2) Dot(b DVec2) float64 {
	return a.X*b.X + a.Y*b.Y
}

func (v DVec2) Len() float64 {
	return math.Sqrt(v.Dot(v))
}

func (v DVec2) LenSq() float64 {
	return v.Dot(v)
}

func (v DVec2) Normalize() DVec2 {
	l := v.Len()
	if l == 0 {
		return DVec2{}
	}
	return v.Scale(1.0 / l)
}

func (a DVec2) Lerp(b DVec2, t float64) DVec2 {
	return a.Add(b.Sub(a).Scale(t))
}

func (a DVec2) Dist(b DVec2) float64 {
	return a.Sub(b).Len()
}

func (a DVec2) Eq(b DVec2) bool {
	return a.X == b.X && a.Y == b.Y
}

func (a DVec2) ApproxEq(b DVec2, eps float64) bool {
	return abs(a.X-b.X) <= eps && abs(a.Y-b.Y) <= eps
}

func (v DVec2) Float32() Vec2 {
	return Vec2{
		X: float32(v.X),
		Y: float32(v.Y),
	}
}

func (v DVec2) MarshalJSON() ([]byte, error) {
	return json.Marshal([2]float64{v.X, v.Y})
}

func (v *DVec2) UnmarshalJSON(data []byte) error {
	var arr [2]float64
	if err := json.Unmarshal(data, &arr); err != nil {
		return err
	}
	v.X = arr[0]
	v.Y = arr[1]
	return nil
}
