// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	"encoding/json"
	"math"
)

// DVec3 is a 3-component float64 vector.
type DVec3 struct {
	X float64
	Y float64
	Z float64
}

func NewDVec3(x float64, y float64, z float64) DVec3 {
	return DVec3{X: x, Y: y, Z: z}
}

func (a DVec3) Add(b DVec3) DVec3 {
	return DVec3{
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
	}
}

func (a DVec3) Sub(b DVec3) DVec3 {
	return DVec3{
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
	}
}

func (v DVec3) Scale(s float64) DVec3 {
	return DVec3{
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
	}
}

func (a DVec3) Dot(b DVec3) float64 {
	return a.X*b.X + a.Y*b.Y + a.Z*b.Z
}

func (a DVec3) Cross(b DVec3) DVec3 {
	return DVec3{
		X: a.Y*b.Z - a.Z*b.Y,
		Y: a.Z*b.X - a.X*b.Z,
		Z: a.X*b.Y - a.Y*b.X,
	}
}

func (v DVec3) Len() float64 {
	return math.Sqrt(v.Dot(v))
}

func (v DVec3) LenSq() float64 {
	return v.Dot(v)
}

func (v DVec3) Normalize() DVec3 {
	l := v.Len()
	if l == 0 {
		return DVec3{}
	}
	return v.Scale(1.0 / l)
}

func (a DVec3) Lerp(b DVec3, t float64) DVec3 {
	return a.Add(b.Sub(a).Scale(t))
}

func (a DVec3) Dist(b DVec3) float64 {
	return a.Sub(b).Len()
}

func (a DVec3) Eq(b DVec3) bool {
	return a.X == b.X && a.Y == b.Y && a.Z == b.Z
}

func (a DVec3) ApproxEq(b DVec3, eps float64) bool {
	return abs(a.X-b.X) <= eps && abs(a.Y-b.Y) <= eps && abs(a.Z-b.Z) <= eps
}

func (v DVec3) Float32() Vec3 {
	return Vec3{
		X: float32(v.X),
		Y: float32(v.Y),
		Z: float32(v.Z),
	}
}

func (v DVec3) XY() DVec2 {
	return DVec2{X: v.X, Y: v.Y}
}

func (v DVec3) MarshalJSON() ([]byte, error) {
	return json.Marshal([3]float64{v.X, v.Y, v.Z})
}

func (v *DVec3) UnmarshalJSON(data []byte) error {
	var arr [3]float64
	if err := json.Unmarshal(data, &arr); err != nil {
		return err
	}
	v.X = arr[0]
	v.Y = arr[1]
	v.Z = arr[2]
	return nil
}
