// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// DVec4 is a 4-component float64 vector.
type DVec4 struct {
	X float64
	Y float64
	Z float64
	W float64
}

func NewDVec4(x float64, y float64, z float64, w float64) DVec4 {
	return DVec4{X: x, Y: y, Z: z, W: w}
}

func (a DVec4) Add(b DVec4) DVec4 {
	return DVec4{
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
		W: a.W + b.W,
	}
}

func (a DVec4) Sub(b DVec4) DVec4 {
	return DVec4{
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
		W: a.W - b.W,
	}
}

func (v DVec4) Scale(s float64) DVec4 {
	return DVec4{
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
		W: v.W * s,
	}
}

func (a DVec4) Dot(b DVec4) float64 {
	return a.X*b.X + a.Y*b.Y + a.Z*b.Z + a.W*b.W
}

func (v DVec4) Len() float64 {
	return math.Sqrt(v.Dot(v))
}

func (v DVec4) LenSq() float64 {
	return v.Dot(v)
}

func (v DVec4) Normalize() DVec4 {
	l := v.Len()
	if l == 0 {
		return DVec4{}
	}
	return v.Scale(1.0 / l)
}

func (a DVec4) Lerp(b DVec4, t float64) DVec4 {
	return a.Add(b.Sub(a).Scale(t))
}

func (a DVec4) Dist(b DVec4) float64 {
	return a.Sub(b).Len()
}

func (a DVec4) Eq(b DVec4) bool {
	return a.X == b.X && a.Y == b.Y && a.Z == b.Z && a.W == b.W
}

func (a DVec4) ApproxEq(b DVec4, eps float64) bool {
	return abs(a.X-b.X) <= eps && abs(a.Y-b.Y) <= eps && abs(a.Z-b.Z) <= eps && abs(a.W-b.W) <= eps
}

func (v DVec4) Float32() Vec4 {
	return Vec4{
		X: float32(v.X),
		Y: float32(v.Y),
		Z: float32(v.Z),
		W: float32(v.W),
	}
}

func (v DVec4) XY() DVec2 {
	return DVec2{X: v.X, Y: v.Y}
}

func (v DVec4) XYZ() DVec3 {
	return DVec3{X: v.X, Y: v.Y, Z: v.Z}
}
