// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	stdmath "math"
	"testing"

	"github.com/wow-look-at-my/testify/assert"
)

// ---------------------------------------------------------------------------
// Vec2
// ---------------------------------------------------------------------------

func TestVec2Constructor(t *testing.T) {
	v := NewVec2(3, 4)
	assert.Equal(t, float32(3), v.X)
	assert.Equal(t, float32(4), v.Y)
}

func TestVec2Add(t *testing.T) {
	got := Vec2{X: 1, Y: 2}.Add(Vec2{X: 3, Y: 4})
	assert.True(t, got.Eq(Vec2{X: 4, Y: 6}))
}

func TestVec2Sub(t *testing.T) {
	got := Vec2{X: 5, Y: 7}.Sub(Vec2{X: 2, Y: 3})
	assert.True(t, got.Eq(Vec2{X: 3, Y: 4}))
}

func TestVec2Scale(t *testing.T) {
	got := Vec2{X: 2, Y: 3}.Scale(3)
	assert.True(t, got.Eq(Vec2{X: 6, Y: 9}))
}

func TestVec2Dot(t *testing.T) {
	assert.Equal(t, float32(11), Vec2{X: 1, Y: 2}.Dot(Vec2{X: 3, Y: 4}))
}

func TestVec2LenSq(t *testing.T) {
	assert.Equal(t, float32(25), Vec2{X: 3, Y: 4}.LenSq())
}

func TestVec2Len(t *testing.T) {
	assert.Equal(t, float32(5), Vec2{X: 3, Y: 4}.Len())
}

func TestVec2Normalize(t *testing.T) {
	got := Vec2{X: 3, Y: 4}.Normalize()
	assert.True(t, got.ApproxEq(NewVec2(0.6, 0.8), 1e-6))
}

func TestVec2NormalizeZero(t *testing.T) {
	assert.True(t, Vec2{}.Normalize().Eq(Vec2{}))
}

func TestVec2Dist(t *testing.T) {
	assert.Equal(t, float32(5), Vec2{}.Dist(Vec2{X: 3, Y: 4}))
}

func TestVec2Lerp(t *testing.T) {
	got := Vec2{X: 0, Y: 0}.Lerp(Vec2{X: 10, Y: 20}, 0.5)
	assert.True(t, got.Eq(NewVec2(5, 10)))
}

func TestVec2Eq(t *testing.T) {
	assert.True(t, Vec2{X: 1, Y: 2}.Eq(Vec2{X: 1, Y: 2}))
	assert.False(t, Vec2{X: 1, Y: 2}.Eq(Vec2{X: 1, Y: 3}))
}

func TestVec2ApproxEq(t *testing.T) {
	a := NewVec2(1.0, 2.0)
	b := NewVec2(1.0001, 2.0001)
	assert.True(t, a.ApproxEq(b, 0.001))
	assert.False(t, a.ApproxEq(b, 0.00001))
}

// ---------------------------------------------------------------------------
// Vec3
// ---------------------------------------------------------------------------

func TestVec3Constructor(t *testing.T) {
	v := NewVec3(1, 2, 3)
	assert.Equal(t, float32(1), v.X)
	assert.Equal(t, float32(2), v.Y)
	assert.Equal(t, float32(3), v.Z)
}

func TestVec3Add(t *testing.T) {
	got := Vec3{X: 1, Y: 2, Z: 3}.Add(Vec3{X: 4, Y: 5, Z: 6})
	assert.True(t, got.Eq(Vec3{X: 5, Y: 7, Z: 9}))
}

func TestVec3Sub(t *testing.T) {
	got := Vec3{X: 5, Y: 7, Z: 9}.Sub(Vec3{X: 1, Y: 2, Z: 3})
	assert.True(t, got.Eq(Vec3{X: 4, Y: 5, Z: 6}))
}

func TestVec3Scale(t *testing.T) {
	got := Vec3{X: 1, Y: 2, Z: 3}.Scale(2)
	assert.True(t, got.Eq(Vec3{X: 2, Y: 4, Z: 6}))
}

func TestVec3Dot(t *testing.T) {
	assert.Equal(t, float32(32), Vec3{X: 1, Y: 2, Z: 3}.Dot(Vec3{X: 4, Y: 5, Z: 6}))
}

func TestVec3Cross(t *testing.T) {
	got := Vec3{X: 1, Y: 0, Z: 0}.Cross(Vec3{X: 0, Y: 1, Z: 0})
	assert.True(t, got.Eq(Vec3{X: 0, Y: 0, Z: 1}))
}

func TestVec3LenSq(t *testing.T) {
	assert.Equal(t, float32(14), Vec3{X: 1, Y: 2, Z: 3}.LenSq())
}

func TestVec3Len(t *testing.T) {
	assert.Equal(t, float32(7), Vec3{X: 2, Y: 3, Z: 6}.Len())
}

func TestVec3Normalize(t *testing.T) {
	got := Vec3{X: 0, Y: 0, Z: 5}.Normalize()
	assert.True(t, got.ApproxEq(NewVec3(0, 0, 1), 1e-6))
}

func TestVec3NormalizeZero(t *testing.T) {
	assert.True(t, Vec3{}.Normalize().Eq(Vec3{}))
}

func TestVec3Dist(t *testing.T) {
	assert.Equal(t, float32(7), Vec3{}.Dist(Vec3{X: 2, Y: 3, Z: 6}))
}

func TestVec3Lerp(t *testing.T) {
	got := Vec3{}.Lerp(Vec3{X: 10, Y: 20, Z: 30}, 0.5)
	assert.True(t, got.ApproxEq(NewVec3(5, 10, 15), 1e-6))
}

func TestVec3Eq(t *testing.T) {
	assert.True(t, Vec3{X: 1, Y: 2, Z: 3}.Eq(Vec3{X: 1, Y: 2, Z: 3}))
	assert.False(t, Vec3{X: 1, Y: 2, Z: 3}.Eq(Vec3{X: 1, Y: 2, Z: 4}))
}

func TestVec3XY(t *testing.T) {
	assert.True(t, Vec3{X: 1, Y: 2, Z: 3}.XY().Eq(Vec2{X: 1, Y: 2}))
}

// ---------------------------------------------------------------------------
// Vec4
// ---------------------------------------------------------------------------

func TestVec4Constructor(t *testing.T) {
	v := NewVec4(1, 2, 3, 4)
	assert.Equal(t, float32(1), v.X)
	assert.Equal(t, float32(4), v.W)
}

func TestVec4Add(t *testing.T) {
	got := Vec4{X: 1, Y: 2, Z: 3, W: 4}.Add(Vec4{X: 5, Y: 6, Z: 7, W: 8})
	assert.True(t, got.Eq(Vec4{X: 6, Y: 8, Z: 10, W: 12}))
}

func TestVec4Sub(t *testing.T) {
	got := Vec4{X: 5, Y: 7, Z: 9, W: 11}.Sub(Vec4{X: 1, Y: 2, Z: 3, W: 4})
	assert.True(t, got.Eq(Vec4{X: 4, Y: 5, Z: 6, W: 7}))
}

func TestVec4Scale(t *testing.T) {
	got := Vec4{X: 1, Y: 2, Z: 3, W: 4}.Scale(2)
	assert.True(t, got.Eq(Vec4{X: 2, Y: 4, Z: 6, W: 8}))
}

func TestVec4Dot(t *testing.T) {
	assert.Equal(t, float32(70), Vec4{X: 1, Y: 2, Z: 3, W: 4}.Dot(Vec4{X: 5, Y: 6, Z: 7, W: 8}))
}

func TestVec4LenSq(t *testing.T) {
	assert.Equal(t, float32(25), Vec4{X: 1, Y: 2, Z: 2, W: 4}.LenSq())
}

func TestVec4Len(t *testing.T) {
	assert.Equal(t, float32(5), Vec4{X: 1, Y: 2, Z: 2, W: 4}.Len())
}

func TestVec4Normalize(t *testing.T) {
	got := Vec4{X: 0, Y: 0, Z: 0, W: 5}.Normalize()
	assert.True(t, got.ApproxEq(NewVec4(0, 0, 0, 1), 1e-6))
}

func TestVec4NormalizeZero(t *testing.T) {
	assert.True(t, Vec4{}.Normalize().Eq(Vec4{}))
}

func TestVec4Dist(t *testing.T) {
	assert.Equal(t, float32(5), Vec4{}.Dist(Vec4{X: 1, Y: 2, Z: 2, W: 4}))
}

func TestVec4Lerp(t *testing.T) {
	got := Vec4{}.Lerp(Vec4{X: 10, Y: 20, Z: 30, W: 40}, 0.5)
	assert.True(t, got.Eq(NewVec4(5, 10, 15, 20)))
}

func TestVec4Eq(t *testing.T) {
	assert.True(t, Vec4{X: 1, Y: 2, Z: 3, W: 4}.Eq(Vec4{X: 1, Y: 2, Z: 3, W: 4}))
	assert.False(t, Vec4{X: 1, Y: 2, Z: 3, W: 4}.Eq(Vec4{X: 1, Y: 2, Z: 3, W: 5}))
}

func TestVec4XYZ(t *testing.T) {
	assert.True(t, Vec4{X: 1, Y: 2, Z: 3, W: 4}.XYZ().Eq(Vec3{X: 1, Y: 2, Z: 3}))
}

func TestVec4XY(t *testing.T) {
	assert.True(t, Vec4{X: 1, Y: 2, Z: 3, W: 4}.XY().Eq(Vec2{X: 1, Y: 2}))
}

// ---------------------------------------------------------------------------
// Mat2
// ---------------------------------------------------------------------------

func TestMat2Constructor(t *testing.T) {
	m := NewMat2(1, 2, 3, 4)
	assert.Equal(t, float32(1), m.At(0, 0))
	assert.Equal(t, float32(2), m.At(0, 1))
	assert.Equal(t, float32(3), m.At(1, 0))
	assert.Equal(t, float32(4), m.At(1, 1))
}

func TestMat2Identity(t *testing.T) {
	m := Mat2Identity()
	assert.Equal(t, float32(1), m.At(0, 0))
	assert.Equal(t, float32(0), m.At(0, 1))
	assert.Equal(t, float32(0), m.At(1, 0))
	assert.Equal(t, float32(1), m.At(1, 1))
}

func TestMat2Col(t *testing.T) {
	m := NewMat2(1, 2, 3, 4)
	assert.True(t, m.Col(0).Eq(Vec2{X: 1, Y: 3}))
	assert.True(t, m.Col(1).Eq(Vec2{X: 2, Y: 4}))
}

func TestMat2Row(t *testing.T) {
	m := NewMat2(1, 2, 3, 4)
	assert.True(t, m.Row(0).Eq(Vec2{X: 1, Y: 2}))
	assert.True(t, m.Row(1).Eq(Vec2{X: 3, Y: 4}))
}

func TestMat2Add(t *testing.T) {
	a := NewMat2(1, 2, 3, 4)
	b := NewMat2(5, 6, 7, 8)
	got := a.Add(b)
	assert.True(t, got.Eq(NewMat2(6, 8, 10, 12)))
}

func TestMat2Sub(t *testing.T) {
	a := NewMat2(5, 6, 7, 8)
	b := NewMat2(1, 2, 3, 4)
	got := a.Sub(b)
	assert.True(t, got.Eq(NewMat2(4, 4, 4, 4)))
}

func TestMat2Scale(t *testing.T) {
	got := NewMat2(1, 2, 3, 4).Scale(2)
	assert.True(t, got.Eq(NewMat2(2, 4, 6, 8)))
}

func TestMat2Mul(t *testing.T) {
	a := NewMat2(1, 2, 3, 4)
	b := NewMat2(5, 6, 7, 8)
	got := a.Mul(b)
	assert.True(t, got.Eq(NewMat2(19, 22, 43, 50)))
}

func TestMat2MulIdentity(t *testing.T) {
	m := NewMat2(1, 2, 3, 4)
	assert.True(t, m.Mul(Mat2Identity()).Eq(m))
}

func TestMat2MulVec2(t *testing.T) {
	m := NewMat2(1, 2, 3, 4)
	v := NewVec2(5, 6)
	got := m.MulVec2(v)
	assert.True(t, got.Eq(NewVec2(17, 39)))
}

func TestMat2Transpose(t *testing.T) {
	m := NewMat2(1, 2, 3, 4)
	assert.True(t, m.Transpose().Eq(NewMat2(1, 3, 2, 4)))
}

func TestMat2Det(t *testing.T) {
	assert.Equal(t, float32(-2), NewMat2(1, 2, 3, 4).Det())
}

func TestMat2Inverse(t *testing.T) {
	m := NewMat2(1, 2, 3, 4)
	inv := m.Inverse()
	product := m.Mul(inv)
	identity := Mat2Identity()
	for r := 0; r < 2; r++ {
		for c := 0; c < 2; c++ {
			diff := product.At(r, c) - identity.At(r, c)
			assert.False(t, diff > 1e-5 || diff < -1e-5)
		}
	}
}

func TestMat2InverseSingular(t *testing.T) {
	assert.Equal(t, Mat2{}, NewMat2(1, 2, 2, 4).Inverse())
}

func TestMat2Eq(t *testing.T) {
	a := NewMat2(1, 2, 3, 4)
	assert.True(t, a.Eq(NewMat2(1, 2, 3, 4)))
	assert.False(t, a.Eq(NewMat2(1, 2, 3, 5)))
}

// ---------------------------------------------------------------------------
// Mat3
// ---------------------------------------------------------------------------

func TestMat3Constructor(t *testing.T) {
	m := NewMat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.Equal(t, float32(1), m.At(0, 0))
	assert.Equal(t, float32(9), m.At(2, 2))
}

func TestMat3Identity(t *testing.T) {
	m := Mat3Identity()
	for r := 0; r < 3; r++ {
		for c := 0; c < 3; c++ {
			var want float32
			if r == c {
				want = 1
			}
			assert.Equal(t, want, m.At(r, c))
		}
	}
}

func TestMat3Col(t *testing.T) {
	m := NewMat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Col(1).Eq(Vec3{X: 2, Y: 5, Z: 8}))
}

func TestMat3Row(t *testing.T) {
	m := NewMat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Row(1).Eq(Vec3{X: 4, Y: 5, Z: 6}))
}

func TestMat3Add(t *testing.T) {
	a := NewMat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	b := NewMat3(9, 8, 7, 6, 5, 4, 3, 2, 1)
	assert.True(t, a.Add(b).Eq(NewMat3(10, 10, 10, 10, 10, 10, 10, 10, 10)))
}

func TestMat3Sub(t *testing.T) {
	a := NewMat3(9, 8, 7, 6, 5, 4, 3, 2, 1)
	b := NewMat3(1, 2, 3, 4, 5, 4, 3, 2, 1)
	got := a.Sub(b)
	assert.True(t, got.Eq(NewMat3(8, 6, 4, 2, 0, 0, 0, 0, 0)))
}

func TestMat3Scale(t *testing.T) {
	got := NewMat3(1, 2, 3, 4, 5, 6, 7, 8, 9).Scale(2)
	assert.True(t, got.Eq(NewMat3(2, 4, 6, 8, 10, 12, 14, 16, 18)))
}

func TestMat3Mul(t *testing.T) {
	m := NewMat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Mul(Mat3Identity()).Eq(m))
}

func TestMat3MulNonTrivial(t *testing.T) {
	a := NewMat3(1, 2, 0, 0, 1, 1, 1, 0, 1)
	b := NewMat3(1, 0, 1, 0, 1, 0, 1, 1, 0)
	assert.True(t, a.Mul(b).Eq(NewMat3(1, 2, 1, 1, 2, 0, 2, 1, 1)))
}

func TestMat3MulVec3(t *testing.T) {
	m := Mat3Identity()
	v := Vec3{X: 3, Y: 4, Z: 5}
	assert.True(t, m.MulVec3(v).Eq(v))
}

func TestMat3Transpose(t *testing.T) {
	m := NewMat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Transpose().Eq(NewMat3(1, 4, 7, 2, 5, 8, 3, 6, 9)))
}

func TestMat3Det(t *testing.T) {
	m := NewMat3(1, 0, 0, 0, 2, 0, 0, 0, 3)
	assert.Equal(t, float32(6), m.Det())
}

func TestMat3Inverse(t *testing.T) {
	m := NewMat3(1, 0, 0, 0, 2, 0, 0, 0, 3)
	inv := m.Inverse()
	product := m.Mul(inv)
	identity := Mat3Identity()
	for r := 0; r < 3; r++ {
		for c := 0; c < 3; c++ {
			diff := product.At(r, c) - identity.At(r, c)
			assert.False(t, diff > 1e-4 || diff < -1e-4)
		}
	}
}

func TestMat3InverseSingular(t *testing.T) {
	assert.Equal(t, Mat3{}, NewMat3(1, 2, 3, 4, 5, 6, 7, 8, 9).Inverse())
}

func TestMat3Eq(t *testing.T) {
	a := NewMat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, a.Eq(NewMat3(1, 2, 3, 4, 5, 6, 7, 8, 9)))
	assert.False(t, a.Eq(Mat3Identity()))
}

// ---------------------------------------------------------------------------
// Mat4
// ---------------------------------------------------------------------------

func TestMat4Constructor(t *testing.T) {
	m := NewMat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.Equal(t, float32(1), m.At(0, 0))
	assert.Equal(t, float32(16), m.At(3, 3))
}

func TestMat4Identity(t *testing.T) {
	m := Mat4Identity()
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			var want float32
			if r == c {
				want = 1
			}
			assert.Equal(t, want, m.At(r, c))
		}
	}
}

func TestMat4Col(t *testing.T) {
	m := NewMat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Col(2).Eq(Vec4{X: 3, Y: 7, Z: 11, W: 15}))
}

func TestMat4Row(t *testing.T) {
	m := NewMat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Row(2).Eq(Vec4{X: 9, Y: 10, Z: 11, W: 12}))
}

func TestMat4Add(t *testing.T) {
	a := Mat4Identity()
	got := a.Add(a)
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			assert.Equal(t, a.At(r, c)*2, got.At(r, c))
		}
	}
}

func TestMat4Sub(t *testing.T) {
	a := Mat4Identity()
	assert.True(t, a.Sub(a).Eq(Mat4{}))
}

func TestMat4Scale(t *testing.T) {
	m := Mat4Identity()
	got := m.Scale(3)
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			assert.Equal(t, m.At(r, c)*3, got.At(r, c))
		}
	}
}

func TestMat4Mul(t *testing.T) {
	m := NewMat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Mul(Mat4Identity()).Eq(m))
}

func TestMat4MulVec4(t *testing.T) {
	v := Vec4{X: 1, Y: 2, Z: 3, W: 4}
	assert.True(t, Mat4Identity().MulVec4(v).Eq(v))
}

func TestMat4Transpose(t *testing.T) {
	m := NewMat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	want := NewMat4(1, 5, 9, 13, 2, 6, 10, 14, 3, 7, 11, 15, 4, 8, 12, 16)
	assert.True(t, m.Transpose().Eq(want))
}

func TestMat4TransposeDouble(t *testing.T) {
	m := NewMat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Transpose().Transpose().Eq(m))
}

func TestMat4Det(t *testing.T) {
	m := NewMat4(1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4)
	assert.Equal(t, float32(24), m.Det())
}

func TestMat4Inverse(t *testing.T) {
	m := NewMat4(1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 1)
	inv := m.Inverse()
	product := m.Mul(inv)
	identity := Mat4Identity()
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			diff := product.At(r, c) - identity.At(r, c)
			assert.False(t, diff > 1e-4 || diff < -1e-4)
		}
	}
}

func TestMat4InverseSingular(t *testing.T) {
	m := NewMat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.Equal(t, Mat4{}, m.Inverse())
}

func TestMat4Mat3(t *testing.T) {
	m := NewMat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Mat3().Eq(NewMat3(1, 2, 3, 5, 6, 7, 9, 10, 11)))
}

func TestMat4Eq(t *testing.T) {
	assert.True(t, Mat4Identity().Eq(Mat4Identity()))
	assert.False(t, Mat4Identity().Eq(Mat4{}))
}

// ---------------------------------------------------------------------------
//  Graphics helpers
// ---------------------------------------------------------------------------

func TestTranslation(t *testing.T) {
	m := Translation(NewVec3(2, 3, 4))
	v := NewVec4(1, 1, 1, 1)
	got := m.MulVec4(v)
	want := NewVec4(3, 4, 5, 1)
	assert.True(t, got.Eq(want))
}

func TestScaling(t *testing.T) {
	m := Scaling(NewVec3(2, 3, 4))
	v := NewVec4(1, 1, 1, 1)
	got := m.MulVec4(v)
	want := NewVec4(2, 3, 4, 1)
	assert.True(t, got.Eq(want))
}

func TestRotationX(t *testing.T) {
	m := RotationX(float32(stdmath.Pi / 2))
	v := NewVec4(0, 1, 0, 1)
	got := m.MulVec4(v)
	want := NewVec4(0, 0, 1, 1)
	assert.True(t, got.ApproxEq(want, 1e-5))
}

func TestRotationY(t *testing.T) {
	m := RotationY(float32(stdmath.Pi / 2))
	v := NewVec4(1, 0, 0, 1)
	got := m.MulVec4(v)
	want := NewVec4(0, 0, -1, 1)
	assert.True(t, got.ApproxEq(want, 1e-5))
}

func TestRotationZ(t *testing.T) {
	m := RotationZ(float32(stdmath.Pi / 2))
	v := NewVec4(1, 0, 0, 1)
	got := m.MulVec4(v)
	want := NewVec4(0, 1, 0, 1)
	assert.True(t, got.ApproxEq(want, 1e-5))
}

func TestLookAt(t *testing.T) {
	eye := NewVec3(0, 0, 5)
	center := NewVec3(0, 0, 0)
	up := NewVec3(0, 1, 0)
	m := LookAt(eye, center, up)
	v := m.MulVec4(NewVec4(0, 0, 0, 1))
	assert.True(t, v.ApproxEq(NewVec4(0, 0, -5, 1), 1e-5))
}

func TestPerspective(t *testing.T) {
	m := Perspective(float32(stdmath.Pi/4), 1.0, 0.1, 100.0)
	v := m.MulVec4(NewVec4(0, 0, -0.1, 1))
	ndc := v.Scale(1.0 / v.W)
	assert.False(t, ndc.Z < -1.01 || ndc.Z > -0.99)
}

func TestOrtho(t *testing.T) {
	m := Ortho(-1, 1, -1, 1, -1, 1)
	v := m.MulVec4(NewVec4(0, 0, 0, 1))
	want := NewVec4(0, 0, 0, 1)
	assert.True(t, v.ApproxEq(want, 1e-5))
}

// ---------------------------------------------------------------------------
// Quat
// ---------------------------------------------------------------------------

func TestQuatConstructor(t *testing.T) {
	q := NewQuat(1, 2, 3, 4)
	assert.Equal(t, float32(1), q.W)
	assert.Equal(t, float32(2), q.X)
	assert.Equal(t, float32(3), q.Y)
	assert.Equal(t, float32(4), q.Z)
}

func TestQuatIdentity(t *testing.T) {
	q := QuatIdentity()
	assert.Equal(t, float32(1), q.W)
	assert.Equal(t, float32(0), q.X)
	assert.Equal(t, float32(0), q.Y)
	assert.Equal(t, float32(0), q.Z)
}

func TestQuatFromAxisAngle(t *testing.T) {
	q := QuatFromAxisAngle(NewVec3(0, 0, 1), float32(stdmath.Pi/2))
	s := float32(stdmath.Sin(stdmath.Pi / 4))
	c := float32(stdmath.Cos(stdmath.Pi / 4))
	want := NewQuat(c, 0, 0, s)
	assert.True(t, q.ApproxEq(want, 1e-5))
}

func TestQuatAdd(t *testing.T) {
	a := NewQuat(1, 2, 3, 4)
	b := NewQuat(5, 6, 7, 8)
	got := a.Add(b)
	assert.True(t, got.Eq(NewQuat(6, 8, 10, 12)))
}

func TestQuatSub(t *testing.T) {
	a := NewQuat(5, 7, 9, 11)
	b := NewQuat(1, 2, 3, 4)
	got := a.Sub(b)
	assert.True(t, got.Eq(NewQuat(4, 5, 6, 7)))
}

func TestQuatScale(t *testing.T) {
	got := NewQuat(1, 2, 3, 4).Scale(2)
	assert.True(t, got.Eq(NewQuat(2, 4, 6, 8)))
}

func TestQuatMul(t *testing.T) {
	q := NewQuat(1, 2, 3, 4)
	id := QuatIdentity()
	assert.True(t, id.Mul(q).Eq(q))
}

func TestQuatMulKnown(t *testing.T) {
	a := NewQuat(1, 0, 1, 0)
	b := NewQuat(1, 0.5, 0.5, 0.75)
	got := a.Mul(b)
	want := NewQuat(0.5, 1.25, 1.5, 0.25)
	assert.True(t, got.ApproxEq(want, 1e-5))
}

func TestQuatMulNonCommutative(t *testing.T) {
	a := NewQuat(1, 2, 3, 4)
	b := NewQuat(5, 6, 7, 8)
	assert.False(t, a.Mul(b).Eq(b.Mul(a)))
}

func TestQuatDot(t *testing.T) {
	a := NewQuat(1, 2, 3, 4)
	b := NewQuat(5, 6, 7, 8)
	assert.Equal(t, float32(70), a.Dot(b))
}

func TestQuatLenSq(t *testing.T) {
	assert.Equal(t, float32(30), NewQuat(1, 2, 3, 4).LenSq())
}

func TestQuatLen(t *testing.T) {
	q := NewQuat(1, 0, 0, 0)
	assert.Equal(t, float32(1), q.Len())
}

func TestQuatNormalize(t *testing.T) {
	q := NewQuat(0, 0, 0, 5).Normalize()
	want := NewQuat(0, 0, 0, 1)
	assert.True(t, q.ApproxEq(want, 1e-6))
}

func TestQuatNormalizeZero(t *testing.T) {
	assert.True(t, Quat{}.Normalize().Eq(Quat{}))
}

func TestQuatConjugate(t *testing.T) {
	q := NewQuat(1, 2, 3, 4)
	c := q.Conjugate()
	assert.Equal(t, float32(1), c.W)
	assert.Equal(t, float32(-2), c.X)
	assert.Equal(t, float32(-3), c.Y)
	assert.Equal(t, float32(-4), c.Z)
}

func TestQuatInverse(t *testing.T) {
	q := NewQuat(1, 2, 3, 4).Normalize()
	product := q.Mul(q.Inverse())
	assert.True(t, product.ApproxEq(QuatIdentity(), 1e-5))
}

func TestQuatInverseZero(t *testing.T) {
	assert.True(t, Quat{}.Inverse().Eq(Quat{}))
}

func TestQuatLerp(t *testing.T) {
	a := NewQuat(0, 0, 0, 0)
	b := NewQuat(2, 4, 6, 8)
	got := a.Lerp(b, 0.5)
	assert.True(t, got.Eq(NewQuat(1, 2, 3, 4)))
}

func TestQuatSlerpEndpoints(t *testing.T) {
	a := QuatFromAxisAngle(NewVec3(0, 0, 1), 0)
	b := QuatFromAxisAngle(NewVec3(0, 0, 1), float32(stdmath.Pi/2))
	assert.True(t, a.Slerp(b, 0).ApproxEq(a, 1e-5))
	assert.True(t, a.Slerp(b, 1).ApproxEq(b, 1e-5))
}

func TestQuatSlerp(t *testing.T) {
	a := QuatFromAxisAngle(NewVec3(0, 0, 1), 0)
	b := QuatFromAxisAngle(NewVec3(0, 0, 1), float32(stdmath.Pi/2))
	mid := a.Slerp(b, 0.5)
	want := QuatFromAxisAngle(NewVec3(0, 0, 1), float32(stdmath.Pi/4))
	assert.True(t, mid.ApproxEq(want, 1e-5))
}

func TestQuatRotateVec3(t *testing.T) {
	q := QuatFromAxisAngle(NewVec3(0, 0, 1), float32(stdmath.Pi/2))
	v := NewVec3(1, 0, 0)
	got := q.RotateVec3(v)
	want := NewVec3(0, 1, 0)
	assert.True(t, got.ApproxEq(want, 1e-5))
}

func TestQuatToMat4(t *testing.T) {
	angle := float32(stdmath.Pi / 4)
	q := QuatFromAxisAngle(NewVec3(0, 0, 1), angle)
	got := q.ToMat4()
	want := RotationZ(angle)
	assert.True(t, got.ApproxEq(want, 1e-5))
}

func TestQuatEq(t *testing.T) {
	a := NewQuat(1, 2, 3, 4)
	assert.True(t, a.Eq(NewQuat(1, 2, 3, 4)))
	assert.False(t, a.Eq(NewQuat(1, 2, 3, 5)))
}

func TestQuatApproxEq(t *testing.T) {
	a := NewQuat(1.0, 2.0, 3.0, 4.0)
	b := NewQuat(1.0001, 2.0001, 3.0001, 4.0001)
	assert.True(t, a.ApproxEq(b, 0.001))
	assert.False(t, a.ApproxEq(b, 0.00001))
}

func TestQuatJSON(t *testing.T) {
	q := NewQuat(1, 2, 3, 4)
	data, err := q.MarshalJSON()
	assert.Equal(t, nil, err)
	var q2 Quat
	err = q2.UnmarshalJSON(data)
	assert.Equal(t, nil, err)
	assert.True(t, q.Eq(q2))
}

// ensure stdmath import is used
var _ = stdmath.Pi
