// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	"encoding/json"
	"math"
)

// EulerAngles represents rotation as Euler angles using intrinsic XYZ convention.
// Pitch (X) is applied first, then Yaw (Y), then Roll (Z). All angles are in radians.
type EulerAngles struct {
	Pitch float32 // rotation around X axis (applied first)
	Yaw   float32 // rotation around Y axis (applied second)
	Roll  float32 // rotation around Z axis (applied third)
}

func NewEulerAngles(pitch, yaw, roll float32) EulerAngles {
	return EulerAngles{Pitch: pitch, Yaw: yaw, Roll: roll}
}

// ToQuat converts Euler angles to a quaternion.
// Composition order: Qz(roll) * Qy(yaw) * Qx(pitch).
func (e EulerAngles) ToQuat() Quat {
	cp := float32(math.Cos(float64(e.Pitch * 0.5)))
	sp := float32(math.Sin(float64(e.Pitch * 0.5)))
	cy := float32(math.Cos(float64(e.Yaw * 0.5)))
	sy := float32(math.Sin(float64(e.Yaw * 0.5)))
	cr := float32(math.Cos(float64(e.Roll * 0.5)))
	sr := float32(math.Sin(float64(e.Roll * 0.5)))

	return Quat{
		W: cr*cy*cp + sr*sy*sp,
		X: cr*cy*sp - sr*sy*cp,
		Y: cr*sy*cp + sr*cy*sp,
		Z: sr*cy*cp - cr*sy*sp,
	}
}

// EulerAnglesFromQuat extracts Euler angles from a quaternion using intrinsic XYZ convention.
func EulerAnglesFromQuat(q Quat) EulerAngles {
	// Yaw (Y) — the gimbal-lock axis for XYZ intrinsic
	siny := 2 * (q.W*q.Y - q.X*q.Z)
	var yaw float32
	if siny >= 1 {
		yaw = float32(math.Pi / 2)
	} else if siny <= -1 {
		yaw = -float32(math.Pi / 2)
	} else {
		yaw = float32(math.Asin(float64(siny)))
	}

	// Pitch (X)
	pitch := float32(math.Atan2(
		float64(2*(q.Y*q.Z+q.W*q.X)),
		float64(1-2*(q.X*q.X+q.Y*q.Y)),
	))

	// Roll (Z)
	roll := float32(math.Atan2(
		float64(2*(q.X*q.Y+q.W*q.Z)),
		float64(1-2*(q.Y*q.Y+q.Z*q.Z)),
	))

	return EulerAngles{Pitch: pitch, Yaw: yaw, Roll: roll}
}

func (a EulerAngles) Eq(b EulerAngles) bool {
	return a.Pitch == b.Pitch && a.Yaw == b.Yaw && a.Roll == b.Roll
}

func (a EulerAngles) ApproxEq(b EulerAngles, eps float32) bool {
	return abs(a.Pitch-b.Pitch) <= eps && abs(a.Yaw-b.Yaw) <= eps && abs(a.Roll-b.Roll) <= eps
}

func (e EulerAngles) MarshalJSON() ([]byte, error) {
	return json.Marshal([3]float32{e.Pitch, e.Yaw, e.Roll})
}

func (e *EulerAngles) UnmarshalJSON(data []byte) error {
	var arr [3]float32
	if err := json.Unmarshal(data, &arr); err != nil {
		return err
	}
	e.Pitch = arr[0]
	e.Yaw = arr[1]
	e.Roll = arr[2]
	return nil
}
