// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// Mat3 is a 3x3 float32 matrix in column-major order.
type Mat3 struct {
	Data [9]float32
}

// NewMat3 creates a 3x3 matrix from row-major arguments.
func NewMat3(
	m00, m01, m02 float32,
	m10, m11, m12 float32,
	m20, m21, m22 float32,
) Mat3 {
	return Mat3{Data: [9]float32{
		m00, m10, m20, // col 0
		m01, m11, m21, // col 1
		m02, m12, m22, // col 2
	}}
}

func Mat3Identity() Mat3 {
	return NewMat3(1, 0, 0, 0, 1, 0, 0, 0, 1)
}

func (m Mat3) Col(c int) Vec3 {
	i := c * 3
	return Vec3{X: m.Data[i+0], Y: m.Data[i+1], Z: m.Data[i+2]}
}

func (m Mat3) Row(r int) Vec3 {
	return Vec3{X: m.Data[r+0], Y: m.Data[r+3], Z: m.Data[r+6]}
}

func (m Mat3) At(row, col int) float32 {
	return m.Data[col*3+row]
}

func (a Mat3) Add(b Mat3) Mat3 {
	var out Mat3
	for i := range out.Data {
		out.Data[i] = a.Data[i] + b.Data[i]
	}
	return out
}

func (a Mat3) Sub(b Mat3) Mat3 {
	var out Mat3
	for i := range out.Data {
		out.Data[i] = a.Data[i] - b.Data[i]
	}
	return out
}

func (m Mat3) Scale(s float32) Mat3 {
	var out Mat3
	for i := range out.Data {
		out.Data[i] = m.Data[i] * s
	}
	return out
}

func (a Mat3) Mul(b Mat3) Mat3 {
	var out Mat3
	for c := 0; c < 3; c++ {
		bc := b.Col(c)
		for r := 0; r < 3; r++ {
			out.Data[c*3+r] = a.Row(r).Dot(bc)
		}
	}
	return out
}

func (m Mat3) MulVec3(v Vec3) Vec3 {
	return Vec3{
		X: m.Row(0).Dot(v),
		Y: m.Row(1).Dot(v),
		Z: m.Row(2).Dot(v),
	}
}

func (m Mat3) Transpose() Mat3 {
	var out Mat3
	for r := 0; r < 3; r++ {
		for c := 0; c < 3; c++ {
			out.Data[c*3+r] = m.Data[r*3+c]
		}
	}
	return out
}

func (m Mat3) Det() float32 {
	return m.At(0, 0)*(m.At(1, 1)*m.At(2, 2)-m.At(1, 2)*m.At(2, 1)) -
		m.At(0, 1)*(m.At(1, 0)*m.At(2, 2)-m.At(1, 2)*m.At(2, 0)) +
		m.At(0, 2)*(m.At(1, 0)*m.At(2, 1)-m.At(1, 1)*m.At(2, 0))
}

func (m Mat3) Inverse() Mat3 {
	d := m.Det()
	if d == 0 {
		return Mat3{}
	}
	invD := 1.0 / d

	return NewMat3(
		(m.At(1, 1)*m.At(2, 2)-m.At(1, 2)*m.At(2, 1))*invD,
		(m.At(0, 2)*m.At(2, 1)-m.At(0, 1)*m.At(2, 2))*invD,
		(m.At(0, 1)*m.At(1, 2)-m.At(0, 2)*m.At(1, 1))*invD,

		(m.At(1, 2)*m.At(2, 0)-m.At(1, 0)*m.At(2, 2))*invD,
		(m.At(0, 0)*m.At(2, 2)-m.At(0, 2)*m.At(2, 0))*invD,
		(m.At(0, 2)*m.At(1, 0)-m.At(0, 0)*m.At(1, 2))*invD,

		(m.At(1, 0)*m.At(2, 1)-m.At(1, 1)*m.At(2, 0))*invD,
		(m.At(0, 1)*m.At(2, 0)-m.At(0, 0)*m.At(2, 1))*invD,
		(m.At(0, 0)*m.At(1, 1)-m.At(0, 1)*m.At(1, 0))*invD,
	)
}
func (a Mat3) Eq(b Mat3) bool {
	for i := range a.Data {
		if a.Data[i] != b.Data[i] {
			return false
		}
	}
	return true
}

func (a Mat3) ApproxEq(b Mat3, eps float32) bool {
	for i := range a.Data {
		if abs(a.Data[i]-b.Data[i]) > eps {
			return false
		}
	}
	return true
}

// ensure math import is used
var _ = math.Sqrt
