// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	"encoding/json"
	"math"
)

// Quat is a float32 quaternion with scalar part W and vector part (X, Y, Z).
type Quat struct {
	W float32
	X float32
	Y float32
	Z float32
}

func NewQuat(w, x, y, z float32) Quat {
	return Quat{W: w, X: x, Y: y, Z: z}
}

func QuatIdentity() Quat {
	return Quat{W: 1}
}

func QuatFromAxisAngle(axis Vec3, angle float32) Quat {
	halfAngle := angle * 0.5
	s := float32(math.Sin(float64(halfAngle)))
	c := float32(math.Cos(float64(halfAngle)))
	n := axis.Normalize()
	return Quat{W: c, X: n.X * s, Y: n.Y * s, Z: n.Z * s}
}

func (a Quat) Add(b Quat) Quat {
	return Quat{
		W: a.W + b.W,
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
	}
}

func (a Quat) Sub(b Quat) Quat {
	return Quat{
		W: a.W - b.W,
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
	}
}

func (v Quat) Scale(s float32) Quat {
	return Quat{
		W: v.W * s,
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
	}
}

func (a Quat) Mul(b Quat) Quat {
	return Quat{
		W: a.W*b.W - a.X*b.X - a.Y*b.Y - a.Z*b.Z,
		X: a.W*b.X + a.X*b.W + a.Y*b.Z - a.Z*b.Y,
		Y: a.W*b.Y - a.X*b.Z + a.Y*b.W + a.Z*b.X,
		Z: a.W*b.Z + a.X*b.Y - a.Y*b.X + a.Z*b.W,
	}
}

func (a Quat) Dot(b Quat) float32 {
	return a.W*b.W + a.X*b.X + a.Y*b.Y + a.Z*b.Z
}

func (v Quat) LenSq() float32 {
	return v.Dot(v)
}

func (v Quat) Len() float32 {
	return float32(math.Sqrt(float64(v.Dot(v))))
}

func (v Quat) Normalize() Quat {
	l := v.Len()
	if l == 0 {
		return Quat{}
	}
	return v.Scale(1.0 / l)
}

func (v Quat) Conjugate() Quat {
	return Quat{W: v.W, X: -v.X, Y: -v.Y, Z: -v.Z}
}

func (v Quat) Inverse() Quat {
	lenSq := v.LenSq()
	if lenSq == 0 {
		return Quat{}
	}
	return v.Conjugate().Scale(1.0 / lenSq)
}

func (a Quat) Lerp(b Quat, t float32) Quat {
	return a.Add(b.Sub(a).Scale(t))
}

func (a Quat) Slerp(b Quat, t float32) Quat {
	dot := a.Dot(b)
	bq := b
	if dot < 0 {
		bq = b.Scale(-1)
		dot = -dot
	}
	if dot > 0.9995 {
		return a.Lerp(bq, t).Normalize()
	}
	theta := float32(math.Acos(float64(dot)))
	sinTheta := float32(math.Sin(float64(theta)))
	wa := float32(math.Sin(float64((1-t)*theta))) / sinTheta
	wb := float32(math.Sin(float64(t*theta))) / sinTheta
	return a.Scale(wa).Add(bq.Scale(wb))
}

func (q Quat) RotateVec3(v Vec3) Vec3 {
	u := Vec3{X: q.X, Y: q.Y, Z: q.Z}
	s := q.W
	return u.Scale(2 * u.Dot(v)).Add(v.Scale(s*s - u.Dot(u))).Add(u.Cross(v).Scale(2 * s))
}

func (q Quat) ToMat4() Mat4 {
	xx := q.X * q.X
	yy := q.Y * q.Y
	zz := q.Z * q.Z
	xy := q.X * q.Y
	xz := q.X * q.Z
	yz := q.Y * q.Z
	wx := q.W * q.X
	wy := q.W * q.Y
	wz := q.W * q.Z

	return NewMat4(
		1-2*(yy+zz), 2*(xy-wz), 2*(xz+wy), 0,
		2*(xy+wz), 1-2*(xx+zz), 2*(yz-wx), 0,
		2*(xz-wy), 2*(yz+wx), 1-2*(xx+yy), 0,
		0, 0, 0, 1,
	)
}

func (a Quat) Eq(b Quat) bool {
	return a.W == b.W && a.X == b.X && a.Y == b.Y && a.Z == b.Z
}

func (a Quat) ApproxEq(b Quat, eps float32) bool {
	return abs(a.W-b.W) <= eps && abs(a.X-b.X) <= eps && abs(a.Y-b.Y) <= eps && abs(a.Z-b.Z) <= eps
}

func (v Quat) MarshalJSON() ([]byte, error) {
	return json.Marshal([4]float32{v.W, v.X, v.Y, v.Z})
}

func (v *Quat) UnmarshalJSON(data []byte) error {
	var arr [4]float32
	if err := json.Unmarshal(data, &arr); err != nil {
		return err
	}
	v.W = arr[0]
	v.X = arr[1]
	v.Y = arr[2]
	v.Z = arr[3]
	return nil
}
