// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// I16Vec3 is a 3-component int16 vector.
type I16Vec3 struct {
	X int16
	Y int16
	Z int16
}

func NewI16Vec3(x int16, y int16, z int16) I16Vec3 {
	return I16Vec3{X: x, Y: y, Z: z}
}

func (a I16Vec3) Add(b I16Vec3) I16Vec3 {
	return I16Vec3{
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
	}
}

func (a I16Vec3) Sub(b I16Vec3) I16Vec3 {
	return I16Vec3{
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
	}
}

func (v I16Vec3) Scale(s int16) I16Vec3 {
	return I16Vec3{
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
	}
}

func (a I16Vec3) Dot(b I16Vec3) int16 {
	return a.X*b.X + a.Y*b.Y + a.Z*b.Z
}

func (a I16Vec3) Cross(b I16Vec3) I16Vec3 {
	return I16Vec3{
		X: a.Y*b.Z - a.Z*b.Y,
		Y: a.Z*b.X - a.X*b.Z,
		Z: a.X*b.Y - a.Y*b.X,
	}
}

func (v I16Vec3) LenSq() int16 {
	return v.Dot(v)
}

func (v I16Vec3) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y) + float64(v.Z)*float64(v.Z)))
}

func (v I16Vec3) Normalize() Vec3 {
	l := v.Len()
	if l == 0 {
		return Vec3{}
	}
	return Vec3{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
		Z: float32(v.Z) / l,
	}
}

func (a I16Vec3) Lerp(b I16Vec3, t float32) Vec3 {
	return Vec3{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
		Z: float32(a.Z) + (float32(b.Z)-float32(a.Z))*t,
	}
}

func (a I16Vec3) Dist(b I16Vec3) float32 {
	d := a.Sub(b)
	return d.Len()
}

func (a I16Vec3) Eq(b I16Vec3) bool {
	return a.X == b.X && a.Y == b.Y && a.Z == b.Z
}

func (v I16Vec3) Float32() Vec3 {
	return Vec3{
		X: float32(v.X),
		Y: float32(v.Y),
		Z: float32(v.Z),
	}
}

func (v I16Vec3) XY() I16Vec2 {
	return I16Vec2{X: v.X, Y: v.Y}
}
