// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// I16Vec2 is a 2-component int16 vector.
type I16Vec2 struct {
	X int16
	Y int16
}

func NewI16Vec2(x int16, y int16) I16Vec2 {
	return I16Vec2{X: x, Y: y}
}

func (a I16Vec2) Add(b I16Vec2) I16Vec2 {
	return I16Vec2{
		X: a.X + b.X,
		Y: a.Y + b.Y,
	}
}

func (a I16Vec2) Sub(b I16Vec2) I16Vec2 {
	return I16Vec2{
		X: a.X - b.X,
		Y: a.Y - b.Y,
	}
}

func (v I16Vec2) Scale(s int16) I16Vec2 {
	return I16Vec2{
		X: v.X * s,
		Y: v.Y * s,
	}
}

func (a I16Vec2) Dot(b I16Vec2) int16 {
	return a.X*b.X + a.Y*b.Y
}

func (v I16Vec2) LenSq() int16 {
	return v.Dot(v)
}

func (v I16Vec2) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y)))
}

func (v I16Vec2) Normalize() Vec2 {
	l := v.Len()
	if l == 0 {
		return Vec2{}
	}
	return Vec2{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
	}
}

func (a I16Vec2) Lerp(b I16Vec2, t float32) Vec2 {
	return Vec2{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
	}
}

func (a I16Vec2) Dist(b I16Vec2) float32 {
	d := a.Sub(b)
	return d.Len()
}

func (a I16Vec2) Eq(b I16Vec2) bool {
	return a.X == b.X && a.Y == b.Y
}

func (v I16Vec2) Float32() Vec2 {
	return Vec2{
		X: float32(v.X),
		Y: float32(v.Y),
	}
}
