// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	"encoding/json"
	"math"
)

// I32Vec2 is a 2-component int32 vector.
type I32Vec2 struct {
	X int32
	Y int32
}

func NewI32Vec2(x int32, y int32) I32Vec2 {
	return I32Vec2{X: x, Y: y}
}

func (a I32Vec2) Add(b I32Vec2) I32Vec2 {
	return I32Vec2{
		X: a.X + b.X,
		Y: a.Y + b.Y,
	}
}

func (a I32Vec2) Sub(b I32Vec2) I32Vec2 {
	return I32Vec2{
		X: a.X - b.X,
		Y: a.Y - b.Y,
	}
}

func (v I32Vec2) Scale(s int32) I32Vec2 {
	return I32Vec2{
		X: v.X * s,
		Y: v.Y * s,
	}
}

func (a I32Vec2) Dot(b I32Vec2) int32 {
	return a.X*b.X + a.Y*b.Y
}

func (v I32Vec2) LenSq() int32 {
	return v.Dot(v)
}

func (v I32Vec2) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y)))
}

func (v I32Vec2) Normalize() Vec2 {
	l := v.Len()
	if l == 0 {
		return Vec2{}
	}
	return Vec2{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
	}
}

func (a I32Vec2) Lerp(b I32Vec2, t float32) Vec2 {
	return Vec2{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
	}
}

func (a I32Vec2) Dist(b I32Vec2) float32 {
	return float32(math.Sqrt((float64(a.X)-float64(b.X))*(float64(a.X)-float64(b.X)) + (float64(a.Y)-float64(b.Y))*(float64(a.Y)-float64(b.Y))))
}

func (a I32Vec2) Eq(b I32Vec2) bool {
	return a.X == b.X && a.Y == b.Y
}

func (v I32Vec2) Float32() Vec2 {
	return Vec2{
		X: float32(v.X),
		Y: float32(v.Y),
	}
}

func (v I32Vec2) MarshalJSON() ([]byte, error) {
	return json.Marshal([2]int32{v.X, v.Y})
}

func (v *I32Vec2) UnmarshalJSON(data []byte) error {
	var arr [2]int32
	if err := json.Unmarshal(data, &arr); err != nil {
		return err
	}
	v.X = arr[0]
	v.Y = arr[1]
	return nil
}
