// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	"testing"

	"github.com/wow-look-at-my/testify/assert"
)

// ---------------------------------------------------------------------------
// I64Vec2
// ---------------------------------------------------------------------------

func TestI64Vec2Constructor(t *testing.T) {
	v := NewI64Vec2(3, 4)
	assert.Equal(t, int64(3), v.X)
	assert.Equal(t, int64(4), v.Y)
}

func TestI64Vec2Add(t *testing.T) {
	got := I64Vec2{X: 1, Y: 2}.Add(I64Vec2{X: 3, Y: 4})
	assert.True(t, got.Eq(I64Vec2{X: 4, Y: 6}))
}

func TestI64Vec2Sub(t *testing.T) {
	got := I64Vec2{X: 5, Y: 7}.Sub(I64Vec2{X: 2, Y: 3})
	assert.True(t, got.Eq(I64Vec2{X: 3, Y: 4}))
}

func TestI64Vec2Scale(t *testing.T) {
	got := I64Vec2{X: 2, Y: 3}.Scale(3)
	assert.True(t, got.Eq(I64Vec2{X: 6, Y: 9}))
}

func TestI64Vec2Dot(t *testing.T) {
	assert.Equal(t, int64(11), I64Vec2{X: 1, Y: 2}.Dot(I64Vec2{X: 3, Y: 4}))
}

func TestI64Vec2LenSq(t *testing.T) {
	assert.Equal(t, int64(25), I64Vec2{X: 3, Y: 4}.LenSq())
}

func TestI64Vec2Len(t *testing.T) {
	assert.Equal(t, float32(5), I64Vec2{X: 3, Y: 4}.Len())
}

func TestI64Vec2Normalize(t *testing.T) {
	got := I64Vec2{X: 3, Y: 4}.Normalize()
	assert.True(t, got.ApproxEq(NewVec2(0.6, 0.8), 1e-6))
}

func TestI64Vec2NormalizeZero(t *testing.T) {
	assert.True(t, I64Vec2{}.Normalize().Eq(Vec2{}))
}

func TestI64Vec2Dist(t *testing.T) {
	assert.Equal(t, float32(5), I64Vec2{}.Dist(I64Vec2{X: 3, Y: 4}))
}

func TestI64Vec2Lerp(t *testing.T) {
	got := I64Vec2{X: 0, Y: 0}.Lerp(I64Vec2{X: 10, Y: 20}, 0.5)
	assert.True(t, got.Eq(NewVec2(5, 10)))
}

func TestI64Vec2Eq(t *testing.T) {
	assert.True(t, I64Vec2{X: 1, Y: 2}.Eq(I64Vec2{X: 1, Y: 2}))
	assert.False(t, I64Vec2{X: 1, Y: 2}.Eq(I64Vec2{X: 1, Y: 3}))
}

func TestI64Vec2Float32(t *testing.T) {
	assert.True(t, I64Vec2{X: 3, Y: 4}.Float32().Eq(NewVec2(3, 4)))
}

// ---------------------------------------------------------------------------
// I64Vec3
// ---------------------------------------------------------------------------

func TestI64Vec3Constructor(t *testing.T) {
	v := NewI64Vec3(1, 2, 3)
	assert.Equal(t, int64(1), v.X)
	assert.Equal(t, int64(2), v.Y)
	assert.Equal(t, int64(3), v.Z)
}

func TestI64Vec3Add(t *testing.T) {
	got := I64Vec3{X: 1, Y: 2, Z: 3}.Add(I64Vec3{X: 4, Y: 5, Z: 6})
	assert.True(t, got.Eq(I64Vec3{X: 5, Y: 7, Z: 9}))
}

func TestI64Vec3Sub(t *testing.T) {
	got := I64Vec3{X: 5, Y: 7, Z: 9}.Sub(I64Vec3{X: 1, Y: 2, Z: 3})
	assert.True(t, got.Eq(I64Vec3{X: 4, Y: 5, Z: 6}))
}

func TestI64Vec3Scale(t *testing.T) {
	got := I64Vec3{X: 1, Y: 2, Z: 3}.Scale(2)
	assert.True(t, got.Eq(I64Vec3{X: 2, Y: 4, Z: 6}))
}

func TestI64Vec3Dot(t *testing.T) {
	assert.Equal(t, int64(32), I64Vec3{X: 1, Y: 2, Z: 3}.Dot(I64Vec3{X: 4, Y: 5, Z: 6}))
}

func TestI64Vec3Cross(t *testing.T) {
	got := I64Vec3{X: 1, Y: 0, Z: 0}.Cross(I64Vec3{X: 0, Y: 1, Z: 0})
	assert.True(t, got.Eq(I64Vec3{X: 0, Y: 0, Z: 1}))
}

func TestI64Vec3LenSq(t *testing.T) {
	assert.Equal(t, int64(14), I64Vec3{X: 1, Y: 2, Z: 3}.LenSq())
}

func TestI64Vec3Len(t *testing.T) {
	assert.Equal(t, float32(7), I64Vec3{X: 2, Y: 3, Z: 6}.Len())
}

func TestI64Vec3Normalize(t *testing.T) {
	got := I64Vec3{X: 0, Y: 0, Z: 5}.Normalize()
	assert.True(t, got.ApproxEq(NewVec3(0, 0, 1), 1e-6))
}

func TestI64Vec3NormalizeZero(t *testing.T) {
	assert.True(t, I64Vec3{}.Normalize().Eq(Vec3{}))
}

func TestI64Vec3Dist(t *testing.T) {
	assert.Equal(t, float32(7), I64Vec3{}.Dist(I64Vec3{X: 2, Y: 3, Z: 6}))
}

func TestI64Vec3Lerp(t *testing.T) {
	got := I64Vec3{}.Lerp(I64Vec3{X: 10, Y: 20, Z: 30}, 0.5)
	assert.True(t, got.ApproxEq(NewVec3(5, 10, 15), 1e-6))
}

func TestI64Vec3Eq(t *testing.T) {
	assert.True(t, I64Vec3{X: 1, Y: 2, Z: 3}.Eq(I64Vec3{X: 1, Y: 2, Z: 3}))
	assert.False(t, I64Vec3{X: 1, Y: 2, Z: 3}.Eq(I64Vec3{X: 1, Y: 2, Z: 4}))
}

func TestI64Vec3Float32(t *testing.T) {
	assert.True(t, I64Vec3{X: 1, Y: 2, Z: 3}.Float32().Eq(NewVec3(1, 2, 3)))
}

func TestI64Vec3XY(t *testing.T) {
	assert.True(t, I64Vec3{X: 1, Y: 2, Z: 3}.XY().Eq(I64Vec2{X: 1, Y: 2}))
}

// ---------------------------------------------------------------------------
// I64Vec4
// ---------------------------------------------------------------------------

func TestI64Vec4Constructor(t *testing.T) {
	v := NewI64Vec4(1, 2, 3, 4)
	assert.Equal(t, int64(1), v.X)
	assert.Equal(t, int64(4), v.W)
}

func TestI64Vec4Add(t *testing.T) {
	got := I64Vec4{X: 1, Y: 2, Z: 3, W: 4}.Add(I64Vec4{X: 5, Y: 6, Z: 7, W: 8})
	assert.True(t, got.Eq(I64Vec4{X: 6, Y: 8, Z: 10, W: 12}))
}

func TestI64Vec4Sub(t *testing.T) {
	got := I64Vec4{X: 5, Y: 7, Z: 9, W: 11}.Sub(I64Vec4{X: 1, Y: 2, Z: 3, W: 4})
	assert.True(t, got.Eq(I64Vec4{X: 4, Y: 5, Z: 6, W: 7}))
}

func TestI64Vec4Scale(t *testing.T) {
	got := I64Vec4{X: 1, Y: 2, Z: 3, W: 4}.Scale(2)
	assert.True(t, got.Eq(I64Vec4{X: 2, Y: 4, Z: 6, W: 8}))
}

func TestI64Vec4Dot(t *testing.T) {
	assert.Equal(t, int64(70), I64Vec4{X: 1, Y: 2, Z: 3, W: 4}.Dot(I64Vec4{X: 5, Y: 6, Z: 7, W: 8}))
}

func TestI64Vec4LenSq(t *testing.T) {
	assert.Equal(t, int64(25), I64Vec4{X: 1, Y: 2, Z: 2, W: 4}.LenSq())
}

func TestI64Vec4Len(t *testing.T) {
	assert.Equal(t, float32(5), I64Vec4{X: 1, Y: 2, Z: 2, W: 4}.Len())
}

func TestI64Vec4Normalize(t *testing.T) {
	got := I64Vec4{X: 0, Y: 0, Z: 0, W: 5}.Normalize()
	assert.True(t, got.ApproxEq(NewVec4(0, 0, 0, 1), 1e-6))
}

func TestI64Vec4NormalizeZero(t *testing.T) {
	assert.True(t, I64Vec4{}.Normalize().Eq(Vec4{}))
}

func TestI64Vec4Dist(t *testing.T) {
	assert.Equal(t, float32(5), I64Vec4{}.Dist(I64Vec4{X: 1, Y: 2, Z: 2, W: 4}))
}

func TestI64Vec4Lerp(t *testing.T) {
	got := I64Vec4{}.Lerp(I64Vec4{X: 10, Y: 20, Z: 30, W: 40}, 0.5)
	assert.True(t, got.Eq(NewVec4(5, 10, 15, 20)))
}

func TestI64Vec4Eq(t *testing.T) {
	assert.True(t, I64Vec4{X: 1, Y: 2, Z: 3, W: 4}.Eq(I64Vec4{X: 1, Y: 2, Z: 3, W: 4}))
	assert.False(t, I64Vec4{X: 1, Y: 2, Z: 3, W: 4}.Eq(I64Vec4{X: 1, Y: 2, Z: 3, W: 5}))
}

func TestI64Vec4Float32(t *testing.T) {
	assert.True(t, I64Vec4{X: 1, Y: 2, Z: 3, W: 4}.Float32().Eq(NewVec4(1, 2, 3, 4)))
}

func TestI64Vec4XYZ(t *testing.T) {
	assert.True(t, I64Vec4{X: 1, Y: 2, Z: 3, W: 4}.XYZ().Eq(I64Vec3{X: 1, Y: 2, Z: 3}))
}

func TestI64Vec4XY(t *testing.T) {
	assert.True(t, I64Vec4{X: 1, Y: 2, Z: 3, W: 4}.XY().Eq(I64Vec2{X: 1, Y: 2}))
}

// ---------------------------------------------------------------------------
// I64Mat2
// ---------------------------------------------------------------------------

func TestI64Mat2Constructor(t *testing.T) {
	m := NewI64Mat2(1, 2, 3, 4)
	assert.Equal(t, int64(1), m.At(0, 0))
	assert.Equal(t, int64(2), m.At(0, 1))
	assert.Equal(t, int64(3), m.At(1, 0))
	assert.Equal(t, int64(4), m.At(1, 1))
}

func TestI64Mat2Identity(t *testing.T) {
	m := I64Mat2Identity()
	assert.Equal(t, int64(1), m.At(0, 0))
	assert.Equal(t, int64(0), m.At(0, 1))
	assert.Equal(t, int64(0), m.At(1, 0))
	assert.Equal(t, int64(1), m.At(1, 1))
}

func TestI64Mat2Col(t *testing.T) {
	m := NewI64Mat2(1, 2, 3, 4)
	assert.True(t, m.Col(0).Eq(I64Vec2{X: 1, Y: 3}))
	assert.True(t, m.Col(1).Eq(I64Vec2{X: 2, Y: 4}))
}

func TestI64Mat2Row(t *testing.T) {
	m := NewI64Mat2(1, 2, 3, 4)
	assert.True(t, m.Row(0).Eq(I64Vec2{X: 1, Y: 2}))
	assert.True(t, m.Row(1).Eq(I64Vec2{X: 3, Y: 4}))
}

func TestI64Mat2Add(t *testing.T) {
	a := NewI64Mat2(1, 2, 3, 4)
	b := NewI64Mat2(5, 6, 7, 8)
	got := a.Add(b)
	assert.True(t, got.Eq(NewI64Mat2(6, 8, 10, 12)))
}

func TestI64Mat2Sub(t *testing.T) {
	a := NewI64Mat2(5, 6, 7, 8)
	b := NewI64Mat2(1, 2, 3, 4)
	got := a.Sub(b)
	assert.True(t, got.Eq(NewI64Mat2(4, 4, 4, 4)))
}

func TestI64Mat2Scale(t *testing.T) {
	got := NewI64Mat2(1, 2, 3, 4).Scale(2)
	assert.True(t, got.Eq(NewI64Mat2(2, 4, 6, 8)))
}

func TestI64Mat2Mul(t *testing.T) {
	a := NewI64Mat2(1, 2, 3, 4)
	b := NewI64Mat2(5, 6, 7, 8)
	got := a.Mul(b)
	assert.True(t, got.Eq(NewI64Mat2(19, 22, 43, 50)))
}

func TestI64Mat2MulIdentity(t *testing.T) {
	m := NewI64Mat2(1, 2, 3, 4)
	assert.True(t, m.Mul(I64Mat2Identity()).Eq(m))
}

func TestI64Mat2MulVec2(t *testing.T) {
	m := NewI64Mat2(1, 2, 3, 4)
	v := NewI64Vec2(5, 6)
	got := m.MulVec2(v)
	assert.True(t, got.Eq(NewI64Vec2(17, 39)))
}

func TestI64Mat2Transpose(t *testing.T) {
	m := NewI64Mat2(1, 2, 3, 4)
	assert.True(t, m.Transpose().Eq(NewI64Mat2(1, 3, 2, 4)))
}

func TestI64Mat2Det(t *testing.T) {
	// Use 1*4 - 2*3 = -2
	assert.Equal(t, int64(-2), NewI64Mat2(1, 2, 3, 4).Det())
}

func TestI64Mat2Inverse(t *testing.T) {
	m := NewI64Mat2(1, 2, 3, 4)
	inv := m.Inverse()
	product := m.Float32().Mul(inv)
	identity := Mat2Identity()
	for r := 0; r < 2; r++ {
		for c := 0; c < 2; c++ {
			diff := product.At(r, c) - identity.At(r, c)
			assert.False(t, diff > 1e-5 || diff < -1e-5)
		}
	}
}

func TestI64Mat2InverseSingular(t *testing.T) {
	assert.Equal(t, Mat2{}, NewI64Mat2(1, 2, 2, 4).Inverse())
}

func TestI64Mat2Eq(t *testing.T) {
	a := NewI64Mat2(1, 2, 3, 4)
	assert.True(t, a.Eq(NewI64Mat2(1, 2, 3, 4)))
	assert.False(t, a.Eq(NewI64Mat2(1, 2, 3, 5)))
}

func TestI64Mat2Float32(t *testing.T) {
	got := NewI64Mat2(1, 2, 3, 4).Float32()
	assert.Equal(t, NewMat2(1, 2, 3, 4), got)
}

// ---------------------------------------------------------------------------
// I64Mat3
// ---------------------------------------------------------------------------

func TestI64Mat3Constructor(t *testing.T) {
	m := NewI64Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.Equal(t, int64(1), m.At(0, 0))
	assert.Equal(t, int64(9), m.At(2, 2))
}

func TestI64Mat3Identity(t *testing.T) {
	m := I64Mat3Identity()
	for r := 0; r < 3; r++ {
		for c := 0; c < 3; c++ {
			var want int64
			if r == c {
				want = 1
			}
			assert.Equal(t, want, m.At(r, c))
		}
	}
}

func TestI64Mat3Col(t *testing.T) {
	m := NewI64Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Col(1).Eq(I64Vec3{X: 2, Y: 5, Z: 8}))
}

func TestI64Mat3Row(t *testing.T) {
	m := NewI64Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Row(1).Eq(I64Vec3{X: 4, Y: 5, Z: 6}))
}

func TestI64Mat3Add(t *testing.T) {
	a := NewI64Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	b := NewI64Mat3(9, 8, 7, 6, 5, 4, 3, 2, 1)
	assert.True(t, a.Add(b).Eq(NewI64Mat3(10, 10, 10, 10, 10, 10, 10, 10, 10)))
}

func TestI64Mat3Sub(t *testing.T) {
	a := NewI64Mat3(9, 8, 7, 6, 5, 4, 3, 2, 1)
	b := NewI64Mat3(1, 2, 3, 4, 5, 4, 3, 2, 1)
	got := a.Sub(b)
	assert.True(t, got.Eq(NewI64Mat3(8, 6, 4, 2, 0, 0, 0, 0, 0)))
}

func TestI64Mat3Scale(t *testing.T) {
	got := NewI64Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9).Scale(2)
	assert.True(t, got.Eq(NewI64Mat3(2, 4, 6, 8, 10, 12, 14, 16, 18)))
}

func TestI64Mat3Mul(t *testing.T) {
	m := NewI64Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Mul(I64Mat3Identity()).Eq(m))
}

func TestI64Mat3MulNonTrivial(t *testing.T) {
	a := NewI64Mat3(1, 2, 0, 0, 1, 1, 1, 0, 1)
	b := NewI64Mat3(1, 0, 1, 0, 1, 0, 1, 1, 0)
	assert.True(t, a.Mul(b).Eq(NewI64Mat3(1, 2, 1, 1, 2, 0, 2, 1, 1)))
}

func TestI64Mat3MulVec3(t *testing.T) {
	m := I64Mat3Identity()
	v := I64Vec3{X: 3, Y: 4, Z: 5}
	assert.True(t, m.MulVec3(v).Eq(v))
}

func TestI64Mat3Transpose(t *testing.T) {
	m := NewI64Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Transpose().Eq(NewI64Mat3(1, 4, 7, 2, 5, 8, 3, 6, 9)))
}

func TestI64Mat3Det(t *testing.T) {
	// Diagonal: det = 1*2*3 = 6
	m := NewI64Mat3(1, 0, 0, 0, 2, 0, 0, 0, 3)
	assert.Equal(t, int64(6), m.Det())
}

func TestI64Mat3Inverse(t *testing.T) {
	m := NewI64Mat3(1, 0, 0, 0, 2, 0, 0, 0, 3)
	inv := m.Inverse()
	product := m.Float32().Mul(inv)
	identity := Mat3Identity()
	for r := 0; r < 3; r++ {
		for c := 0; c < 3; c++ {
			diff := product.At(r, c) - identity.At(r, c)
			assert.False(t, diff > 1e-4 || diff < -1e-4)
		}
	}
}

func TestI64Mat3InverseSingular(t *testing.T) {
	assert.Equal(t, Mat3{}, NewI64Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9).Inverse())
}

func TestI64Mat3Eq(t *testing.T) {
	a := NewI64Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, a.Eq(NewI64Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)))
	assert.False(t, a.Eq(I64Mat3Identity()))
}

func TestI64Mat3Float32(t *testing.T) {
	got := NewI64Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9).Float32()
	assert.Equal(t, NewMat3(1, 2, 3, 4, 5, 6, 7, 8, 9), got)
}

// ---------------------------------------------------------------------------
// I64Mat4
// ---------------------------------------------------------------------------

func TestI64Mat4Constructor(t *testing.T) {
	m := NewI64Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.Equal(t, int64(1), m.At(0, 0))
	assert.Equal(t, int64(16), m.At(3, 3))
}

func TestI64Mat4Identity(t *testing.T) {
	m := I64Mat4Identity()
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			var want int64
			if r == c {
				want = 1
			}
			assert.Equal(t, want, m.At(r, c))
		}
	}
}

func TestI64Mat4Col(t *testing.T) {
	m := NewI64Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Col(2).Eq(I64Vec4{X: 3, Y: 7, Z: 11, W: 15}))
}

func TestI64Mat4Row(t *testing.T) {
	m := NewI64Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Row(2).Eq(I64Vec4{X: 9, Y: 10, Z: 11, W: 12}))
}

func TestI64Mat4Add(t *testing.T) {
	a := I64Mat4Identity()
	got := a.Add(a)
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			assert.Equal(t, a.At(r, c)*2, got.At(r, c))
		}
	}
}

func TestI64Mat4Sub(t *testing.T) {
	a := I64Mat4Identity()
	assert.True(t, a.Sub(a).Eq(I64Mat4{}))
}

func TestI64Mat4Scale(t *testing.T) {
	m := I64Mat4Identity()
	got := m.Scale(3)
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			assert.Equal(t, m.At(r, c)*3, got.At(r, c))
		}
	}
}

func TestI64Mat4Mul(t *testing.T) {
	m := NewI64Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Mul(I64Mat4Identity()).Eq(m))
}

func TestI64Mat4MulVec4(t *testing.T) {
	v := I64Vec4{X: 1, Y: 2, Z: 3, W: 4}
	assert.True(t, I64Mat4Identity().MulVec4(v).Eq(v))
}

func TestI64Mat4Transpose(t *testing.T) {
	m := NewI64Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	want := NewI64Mat4(1, 5, 9, 13, 2, 6, 10, 14, 3, 7, 11, 15, 4, 8, 12, 16)
	assert.True(t, m.Transpose().Eq(want))
}

func TestI64Mat4TransposeDouble(t *testing.T) {
	m := NewI64Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Transpose().Transpose().Eq(m))
}

func TestI64Mat4Det(t *testing.T) {
	m := NewI64Mat4(1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4)
	assert.Equal(t, int64(24), m.Det())
}

func TestI64Mat4Inverse(t *testing.T) {
	m := NewI64Mat4(1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 1)
	inv := m.Inverse()
	product := m.Float32().Mul(inv)
	identity := Mat4Identity()
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			diff := product.At(r, c) - identity.At(r, c)
			assert.False(t, diff > 1e-4 || diff < -1e-4)
		}
	}
}

func TestI64Mat4InverseSingular(t *testing.T) {
	m := NewI64Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.Equal(t, Mat4{}, m.Inverse())
}

func TestI64Mat4Mat3(t *testing.T) {
	m := NewI64Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Mat3().Eq(NewI64Mat3(1, 2, 3, 5, 6, 7, 9, 10, 11)))
}

func TestI64Mat4Eq(t *testing.T) {
	assert.True(t, I64Mat4Identity().Eq(I64Mat4Identity()))
	assert.False(t, I64Mat4Identity().Eq(I64Mat4{}))
}

func TestI64Mat4Float32(t *testing.T) {
	assert.Equal(t, Mat4Identity(), I64Mat4Identity().Float32())
}
