// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// I64Mat2 is a 2x2 int64 matrix in column-major order.
type I64Mat2 struct {
	Data [4]int64
}

// NewI64Mat2 creates a 2x2 matrix from row-major arguments.
func NewI64Mat2(
	m00, m01 int64,
	m10, m11 int64,
) I64Mat2 {
	return I64Mat2{Data: [4]int64{
		m00, m10, // col 0
		m01, m11, // col 1
	}}
}

func I64Mat2Identity() I64Mat2 {
	return NewI64Mat2(1, 0, 0, 1)
}

func (m I64Mat2) Col(c int) I64Vec2 {
	i := c * 2
	return I64Vec2{X: m.Data[i+0], Y: m.Data[i+1]}
}

func (m I64Mat2) Row(r int) I64Vec2 {
	return I64Vec2{X: m.Data[r+0], Y: m.Data[r+2]}
}

func (m I64Mat2) At(row, col int) int64 {
	return m.Data[col*2+row]
}

func (a I64Mat2) Add(b I64Mat2) I64Mat2 {
	var out I64Mat2
	for i := range out.Data {
		out.Data[i] = a.Data[i] + b.Data[i]
	}
	return out
}

func (a I64Mat2) Sub(b I64Mat2) I64Mat2 {
	var out I64Mat2
	for i := range out.Data {
		out.Data[i] = a.Data[i] - b.Data[i]
	}
	return out
}

func (m I64Mat2) Scale(s int64) I64Mat2 {
	var out I64Mat2
	for i := range out.Data {
		out.Data[i] = m.Data[i] * s
	}
	return out
}

func (a I64Mat2) Mul(b I64Mat2) I64Mat2 {
	var out I64Mat2
	for c := 0; c < 2; c++ {
		bc := b.Col(c)
		for r := 0; r < 2; r++ {
			out.Data[c*2+r] = a.Row(r).Dot(bc)
		}
	}
	return out
}

func (m I64Mat2) MulVec2(v I64Vec2) I64Vec2 {
	return I64Vec2{
		X: m.Row(0).Dot(v),
		Y: m.Row(1).Dot(v),
	}
}

func (m I64Mat2) Transpose() I64Mat2 {
	var out I64Mat2
	for r := 0; r < 2; r++ {
		for c := 0; c < 2; c++ {
			out.Data[c*2+r] = m.Data[r*2+c]
		}
	}
	return out
}

func (m I64Mat2) Det() int64 {
	return m.Data[0]*m.Data[3] - m.Data[2]*m.Data[1]
}

func (m I64Mat2) Inverse() Mat2 {
	d := float32(m.Det())
	if d == 0 {
		return Mat2{}
	}
	invD := 1.0 / d
	return Mat2{Data: [4]float32{
		float32(m.Data[3]) * invD, -float32(m.Data[1]) * invD,
		-float32(m.Data[2]) * invD, float32(m.Data[0]) * invD,
	}}
}
func (a I64Mat2) Eq(b I64Mat2) bool {
	for i := range a.Data {
		if a.Data[i] != b.Data[i] {
			return false
		}
	}
	return true
}

func (m I64Mat2) Float32() Mat2 {
	var out Mat2
	for i := range m.Data {
		out.Data[i] = float32(m.Data[i])
	}
	return out
}

// ensure math import is used
var _ = math.Sqrt
