// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// I64Vec4 is a 4-component int64 vector.
type I64Vec4 struct {
	X int64
	Y int64
	Z int64
	W int64
}

func NewI64Vec4(x int64, y int64, z int64, w int64) I64Vec4 {
	return I64Vec4{X: x, Y: y, Z: z, W: w}
}

func (a I64Vec4) Add(b I64Vec4) I64Vec4 {
	return I64Vec4{
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
		W: a.W + b.W,
	}
}

func (a I64Vec4) Sub(b I64Vec4) I64Vec4 {
	return I64Vec4{
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
		W: a.W - b.W,
	}
}

func (v I64Vec4) Scale(s int64) I64Vec4 {
	return I64Vec4{
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
		W: v.W * s,
	}
}

func (a I64Vec4) Dot(b I64Vec4) int64 {
	return a.X*b.X + a.Y*b.Y + a.Z*b.Z + a.W*b.W
}

func (v I64Vec4) LenSq() int64 {
	return v.Dot(v)
}

func (v I64Vec4) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y) + float64(v.Z)*float64(v.Z) + float64(v.W)*float64(v.W)))
}

func (v I64Vec4) Normalize() Vec4 {
	l := v.Len()
	if l == 0 {
		return Vec4{}
	}
	return Vec4{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
		Z: float32(v.Z) / l,
		W: float32(v.W) / l,
	}
}

func (a I64Vec4) Lerp(b I64Vec4, t float32) Vec4 {
	return Vec4{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
		Z: float32(a.Z) + (float32(b.Z)-float32(a.Z))*t,
		W: float32(a.W) + (float32(b.W)-float32(a.W))*t,
	}
}

func (a I64Vec4) Dist(b I64Vec4) float32 {
	d := a.Sub(b)
	return d.Len()
}

func (a I64Vec4) Eq(b I64Vec4) bool {
	return a.X == b.X && a.Y == b.Y && a.Z == b.Z && a.W == b.W
}

func (v I64Vec4) Float32() Vec4 {
	return Vec4{
		X: float32(v.X),
		Y: float32(v.Y),
		Z: float32(v.Z),
		W: float32(v.W),
	}
}

func (v I64Vec4) XY() I64Vec2 {
	return I64Vec2{X: v.X, Y: v.Y}
}

func (v I64Vec4) XYZ() I64Vec3 {
	return I64Vec3{X: v.X, Y: v.Y, Z: v.Z}
}
