// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// I64Vec2 is a 2-component int64 vector.
type I64Vec2 struct {
	X int64
	Y int64
}

func NewI64Vec2(x int64, y int64) I64Vec2 {
	return I64Vec2{X: x, Y: y}
}

func (a I64Vec2) Add(b I64Vec2) I64Vec2 {
	return I64Vec2{
		X: a.X + b.X,
		Y: a.Y + b.Y,
	}
}

func (a I64Vec2) Sub(b I64Vec2) I64Vec2 {
	return I64Vec2{
		X: a.X - b.X,
		Y: a.Y - b.Y,
	}
}

func (v I64Vec2) Scale(s int64) I64Vec2 {
	return I64Vec2{
		X: v.X * s,
		Y: v.Y * s,
	}
}

func (a I64Vec2) Dot(b I64Vec2) int64 {
	return a.X*b.X + a.Y*b.Y
}

func (v I64Vec2) LenSq() int64 {
	return v.Dot(v)
}

func (v I64Vec2) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y)))
}

func (v I64Vec2) Normalize() Vec2 {
	l := v.Len()
	if l == 0 {
		return Vec2{}
	}
	return Vec2{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
	}
}

func (a I64Vec2) Lerp(b I64Vec2, t float32) Vec2 {
	return Vec2{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
	}
}

func (a I64Vec2) Dist(b I64Vec2) float32 {
	return float32(math.Sqrt((float64(a.X)-float64(b.X))*(float64(a.X)-float64(b.X)) + (float64(a.Y)-float64(b.Y))*(float64(a.Y)-float64(b.Y))))
}

func (a I64Vec2) Eq(b I64Vec2) bool {
	return a.X == b.X && a.Y == b.Y
}

func (v I64Vec2) Float32() Vec2 {
	return Vec2{
		X: float32(v.X),
		Y: float32(v.Y),
	}
}
