// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	"encoding/json"
	"math"
)

// I64Vec3 is a 3-component int64 vector.
type I64Vec3 struct {
	X int64
	Y int64
	Z int64
}

func NewI64Vec3(x int64, y int64, z int64) I64Vec3 {
	return I64Vec3{X: x, Y: y, Z: z}
}

func (a I64Vec3) Add(b I64Vec3) I64Vec3 {
	return I64Vec3{
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
	}
}

func (a I64Vec3) Sub(b I64Vec3) I64Vec3 {
	return I64Vec3{
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
	}
}

func (v I64Vec3) Scale(s int64) I64Vec3 {
	return I64Vec3{
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
	}
}

func (a I64Vec3) Dot(b I64Vec3) int64 {
	return a.X*b.X + a.Y*b.Y + a.Z*b.Z
}

func (a I64Vec3) Cross(b I64Vec3) I64Vec3 {
	return I64Vec3{
		X: a.Y*b.Z - a.Z*b.Y,
		Y: a.Z*b.X - a.X*b.Z,
		Z: a.X*b.Y - a.Y*b.X,
	}
}

func (v I64Vec3) LenSq() int64 {
	return v.Dot(v)
}

func (v I64Vec3) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y) + float64(v.Z)*float64(v.Z)))
}

func (v I64Vec3) Normalize() Vec3 {
	l := v.Len()
	if l == 0 {
		return Vec3{}
	}
	return Vec3{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
		Z: float32(v.Z) / l,
	}
}

func (a I64Vec3) Lerp(b I64Vec3, t float32) Vec3 {
	return Vec3{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
		Z: float32(a.Z) + (float32(b.Z)-float32(a.Z))*t,
	}
}

func (a I64Vec3) Dist(b I64Vec3) float32 {
	return float32(math.Sqrt((float64(a.X)-float64(b.X))*(float64(a.X)-float64(b.X)) + (float64(a.Y)-float64(b.Y))*(float64(a.Y)-float64(b.Y)) + (float64(a.Z)-float64(b.Z))*(float64(a.Z)-float64(b.Z))))
}

func (a I64Vec3) Eq(b I64Vec3) bool {
	return a.X == b.X && a.Y == b.Y && a.Z == b.Z
}

func (v I64Vec3) Float32() Vec3 {
	return Vec3{
		X: float32(v.X),
		Y: float32(v.Y),
		Z: float32(v.Z),
	}
}

func (v I64Vec3) XY() I64Vec2 {
	return I64Vec2{X: v.X, Y: v.Y}
}

func (v I64Vec3) MarshalJSON() ([]byte, error) {
	return json.Marshal([3]int64{v.X, v.Y, v.Z})
}

func (v *I64Vec3) UnmarshalJSON(data []byte) error {
	var arr [3]int64
	if err := json.Unmarshal(data, &arr); err != nil {
		return err
	}
	v.X = arr[0]
	v.Y = arr[1]
	v.Z = arr[2]
	return nil
}
