// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	"testing"

	"github.com/wow-look-at-my/testify/assert"
)

// ---------------------------------------------------------------------------
// I8Vec2
// ---------------------------------------------------------------------------

func TestI8Vec2Constructor(t *testing.T) {
	v := NewI8Vec2(3, 4)
	assert.Equal(t, int8(3), v.X)
	assert.Equal(t, int8(4), v.Y)
}

func TestI8Vec2Add(t *testing.T) {
	got := I8Vec2{X: 1, Y: 2}.Add(I8Vec2{X: 3, Y: 4})
	assert.True(t, got.Eq(I8Vec2{X: 4, Y: 6}))
}

func TestI8Vec2Sub(t *testing.T) {
	got := I8Vec2{X: 5, Y: 7}.Sub(I8Vec2{X: 2, Y: 3})
	assert.True(t, got.Eq(I8Vec2{X: 3, Y: 4}))
}

func TestI8Vec2Scale(t *testing.T) {
	got := I8Vec2{X: 2, Y: 3}.Scale(3)
	assert.True(t, got.Eq(I8Vec2{X: 6, Y: 9}))
}

func TestI8Vec2Dot(t *testing.T) {
	assert.Equal(t, int8(11), I8Vec2{X: 1, Y: 2}.Dot(I8Vec2{X: 3, Y: 4}))
}

func TestI8Vec2LenSq(t *testing.T) {
	assert.Equal(t, int8(25), I8Vec2{X: 3, Y: 4}.LenSq())
}

func TestI8Vec2Len(t *testing.T) {
	assert.Equal(t, float32(5), I8Vec2{X: 3, Y: 4}.Len())
}

func TestI8Vec2Normalize(t *testing.T) {
	got := I8Vec2{X: 3, Y: 4}.Normalize()
	assert.True(t, got.ApproxEq(NewVec2(0.6, 0.8), 1e-6))
}

func TestI8Vec2NormalizeZero(t *testing.T) {
	assert.True(t, I8Vec2{}.Normalize().Eq(Vec2{}))
}

func TestI8Vec2Dist(t *testing.T) {
	assert.Equal(t, float32(5), I8Vec2{}.Dist(I8Vec2{X: 3, Y: 4}))
}

func TestI8Vec2Lerp(t *testing.T) {
	got := I8Vec2{X: 0, Y: 0}.Lerp(I8Vec2{X: 10, Y: 20}, 0.5)
	assert.True(t, got.Eq(NewVec2(5, 10)))
}

func TestI8Vec2Eq(t *testing.T) {
	assert.True(t, I8Vec2{X: 1, Y: 2}.Eq(I8Vec2{X: 1, Y: 2}))
	assert.False(t, I8Vec2{X: 1, Y: 2}.Eq(I8Vec2{X: 1, Y: 3}))
}

func TestI8Vec2Float32(t *testing.T) {
	assert.True(t, I8Vec2{X: 3, Y: 4}.Float32().Eq(NewVec2(3, 4)))
}

// ---------------------------------------------------------------------------
// I8Vec3
// ---------------------------------------------------------------------------

func TestI8Vec3Constructor(t *testing.T) {
	v := NewI8Vec3(1, 2, 3)
	assert.Equal(t, int8(1), v.X)
	assert.Equal(t, int8(2), v.Y)
	assert.Equal(t, int8(3), v.Z)
}

func TestI8Vec3Add(t *testing.T) {
	got := I8Vec3{X: 1, Y: 2, Z: 3}.Add(I8Vec3{X: 4, Y: 5, Z: 6})
	assert.True(t, got.Eq(I8Vec3{X: 5, Y: 7, Z: 9}))
}

func TestI8Vec3Sub(t *testing.T) {
	got := I8Vec3{X: 5, Y: 7, Z: 9}.Sub(I8Vec3{X: 1, Y: 2, Z: 3})
	assert.True(t, got.Eq(I8Vec3{X: 4, Y: 5, Z: 6}))
}

func TestI8Vec3Scale(t *testing.T) {
	got := I8Vec3{X: 1, Y: 2, Z: 3}.Scale(2)
	assert.True(t, got.Eq(I8Vec3{X: 2, Y: 4, Z: 6}))
}

func TestI8Vec3Dot(t *testing.T) {
	assert.Equal(t, int8(32), I8Vec3{X: 1, Y: 2, Z: 3}.Dot(I8Vec3{X: 4, Y: 5, Z: 6}))
}

func TestI8Vec3Cross(t *testing.T) {
	got := I8Vec3{X: 1, Y: 0, Z: 0}.Cross(I8Vec3{X: 0, Y: 1, Z: 0})
	assert.True(t, got.Eq(I8Vec3{X: 0, Y: 0, Z: 1}))
}

func TestI8Vec3LenSq(t *testing.T) {
	assert.Equal(t, int8(14), I8Vec3{X: 1, Y: 2, Z: 3}.LenSq())
}

func TestI8Vec3Len(t *testing.T) {
	assert.Equal(t, float32(7), I8Vec3{X: 2, Y: 3, Z: 6}.Len())
}

func TestI8Vec3Normalize(t *testing.T) {
	got := I8Vec3{X: 0, Y: 0, Z: 5}.Normalize()
	assert.True(t, got.ApproxEq(NewVec3(0, 0, 1), 1e-6))
}

func TestI8Vec3NormalizeZero(t *testing.T) {
	assert.True(t, I8Vec3{}.Normalize().Eq(Vec3{}))
}

func TestI8Vec3Dist(t *testing.T) {
	assert.Equal(t, float32(7), I8Vec3{}.Dist(I8Vec3{X: 2, Y: 3, Z: 6}))
}

func TestI8Vec3Lerp(t *testing.T) {
	got := I8Vec3{}.Lerp(I8Vec3{X: 10, Y: 20, Z: 30}, 0.5)
	assert.True(t, got.ApproxEq(NewVec3(5, 10, 15), 1e-6))
}

func TestI8Vec3Eq(t *testing.T) {
	assert.True(t, I8Vec3{X: 1, Y: 2, Z: 3}.Eq(I8Vec3{X: 1, Y: 2, Z: 3}))
	assert.False(t, I8Vec3{X: 1, Y: 2, Z: 3}.Eq(I8Vec3{X: 1, Y: 2, Z: 4}))
}

func TestI8Vec3Float32(t *testing.T) {
	assert.True(t, I8Vec3{X: 1, Y: 2, Z: 3}.Float32().Eq(NewVec3(1, 2, 3)))
}

func TestI8Vec3XY(t *testing.T) {
	assert.True(t, I8Vec3{X: 1, Y: 2, Z: 3}.XY().Eq(I8Vec2{X: 1, Y: 2}))
}

// ---------------------------------------------------------------------------
// I8Vec4
// ---------------------------------------------------------------------------

func TestI8Vec4Constructor(t *testing.T) {
	v := NewI8Vec4(1, 2, 3, 4)
	assert.Equal(t, int8(1), v.X)
	assert.Equal(t, int8(4), v.W)
}

func TestI8Vec4Add(t *testing.T) {
	got := I8Vec4{X: 1, Y: 2, Z: 3, W: 4}.Add(I8Vec4{X: 5, Y: 6, Z: 7, W: 8})
	assert.True(t, got.Eq(I8Vec4{X: 6, Y: 8, Z: 10, W: 12}))
}

func TestI8Vec4Sub(t *testing.T) {
	got := I8Vec4{X: 5, Y: 7, Z: 9, W: 11}.Sub(I8Vec4{X: 1, Y: 2, Z: 3, W: 4})
	assert.True(t, got.Eq(I8Vec4{X: 4, Y: 5, Z: 6, W: 7}))
}

func TestI8Vec4Scale(t *testing.T) {
	got := I8Vec4{X: 1, Y: 2, Z: 3, W: 4}.Scale(2)
	assert.True(t, got.Eq(I8Vec4{X: 2, Y: 4, Z: 6, W: 8}))
}

func TestI8Vec4Dot(t *testing.T) {
	assert.Equal(t, int8(70), I8Vec4{X: 1, Y: 2, Z: 3, W: 4}.Dot(I8Vec4{X: 5, Y: 6, Z: 7, W: 8}))
}

func TestI8Vec4LenSq(t *testing.T) {
	assert.Equal(t, int8(25), I8Vec4{X: 1, Y: 2, Z: 2, W: 4}.LenSq())
}

func TestI8Vec4Len(t *testing.T) {
	assert.Equal(t, float32(5), I8Vec4{X: 1, Y: 2, Z: 2, W: 4}.Len())
}

func TestI8Vec4Normalize(t *testing.T) {
	got := I8Vec4{X: 0, Y: 0, Z: 0, W: 5}.Normalize()
	assert.True(t, got.ApproxEq(NewVec4(0, 0, 0, 1), 1e-6))
}

func TestI8Vec4NormalizeZero(t *testing.T) {
	assert.True(t, I8Vec4{}.Normalize().Eq(Vec4{}))
}

func TestI8Vec4Dist(t *testing.T) {
	assert.Equal(t, float32(5), I8Vec4{}.Dist(I8Vec4{X: 1, Y: 2, Z: 2, W: 4}))
}

func TestI8Vec4Lerp(t *testing.T) {
	got := I8Vec4{}.Lerp(I8Vec4{X: 10, Y: 20, Z: 30, W: 40}, 0.5)
	assert.True(t, got.Eq(NewVec4(5, 10, 15, 20)))
}

func TestI8Vec4Eq(t *testing.T) {
	assert.True(t, I8Vec4{X: 1, Y: 2, Z: 3, W: 4}.Eq(I8Vec4{X: 1, Y: 2, Z: 3, W: 4}))
	assert.False(t, I8Vec4{X: 1, Y: 2, Z: 3, W: 4}.Eq(I8Vec4{X: 1, Y: 2, Z: 3, W: 5}))
}

func TestI8Vec4Float32(t *testing.T) {
	assert.True(t, I8Vec4{X: 1, Y: 2, Z: 3, W: 4}.Float32().Eq(NewVec4(1, 2, 3, 4)))
}

func TestI8Vec4XYZ(t *testing.T) {
	assert.True(t, I8Vec4{X: 1, Y: 2, Z: 3, W: 4}.XYZ().Eq(I8Vec3{X: 1, Y: 2, Z: 3}))
}

func TestI8Vec4XY(t *testing.T) {
	assert.True(t, I8Vec4{X: 1, Y: 2, Z: 3, W: 4}.XY().Eq(I8Vec2{X: 1, Y: 2}))
}

// ---------------------------------------------------------------------------
// I8Mat2
// ---------------------------------------------------------------------------

func TestI8Mat2Constructor(t *testing.T) {
	m := NewI8Mat2(1, 2, 3, 4)
	assert.Equal(t, int8(1), m.At(0, 0))
	assert.Equal(t, int8(2), m.At(0, 1))
	assert.Equal(t, int8(3), m.At(1, 0))
	assert.Equal(t, int8(4), m.At(1, 1))
}

func TestI8Mat2Identity(t *testing.T) {
	m := I8Mat2Identity()
	assert.Equal(t, int8(1), m.At(0, 0))
	assert.Equal(t, int8(0), m.At(0, 1))
	assert.Equal(t, int8(0), m.At(1, 0))
	assert.Equal(t, int8(1), m.At(1, 1))
}

func TestI8Mat2Col(t *testing.T) {
	m := NewI8Mat2(1, 2, 3, 4)
	assert.True(t, m.Col(0).Eq(I8Vec2{X: 1, Y: 3}))
	assert.True(t, m.Col(1).Eq(I8Vec2{X: 2, Y: 4}))
}

func TestI8Mat2Row(t *testing.T) {
	m := NewI8Mat2(1, 2, 3, 4)
	assert.True(t, m.Row(0).Eq(I8Vec2{X: 1, Y: 2}))
	assert.True(t, m.Row(1).Eq(I8Vec2{X: 3, Y: 4}))
}

func TestI8Mat2Add(t *testing.T) {
	a := NewI8Mat2(1, 2, 3, 4)
	b := NewI8Mat2(5, 6, 7, 8)
	got := a.Add(b)
	assert.True(t, got.Eq(NewI8Mat2(6, 8, 10, 12)))
}

func TestI8Mat2Sub(t *testing.T) {
	a := NewI8Mat2(5, 6, 7, 8)
	b := NewI8Mat2(1, 2, 3, 4)
	got := a.Sub(b)
	assert.True(t, got.Eq(NewI8Mat2(4, 4, 4, 4)))
}

func TestI8Mat2Scale(t *testing.T) {
	got := NewI8Mat2(1, 2, 3, 4).Scale(2)
	assert.True(t, got.Eq(NewI8Mat2(2, 4, 6, 8)))
}

func TestI8Mat2Mul(t *testing.T) {
	a := NewI8Mat2(1, 2, 3, 4)
	b := NewI8Mat2(5, 6, 7, 8)
	got := a.Mul(b)
	assert.True(t, got.Eq(NewI8Mat2(19, 22, 43, 50)))
}

func TestI8Mat2MulIdentity(t *testing.T) {
	m := NewI8Mat2(1, 2, 3, 4)
	assert.True(t, m.Mul(I8Mat2Identity()).Eq(m))
}

func TestI8Mat2MulVec2(t *testing.T) {
	m := NewI8Mat2(1, 2, 3, 4)
	v := NewI8Vec2(5, 6)
	got := m.MulVec2(v)
	assert.True(t, got.Eq(NewI8Vec2(17, 39)))
}

func TestI8Mat2Transpose(t *testing.T) {
	m := NewI8Mat2(1, 2, 3, 4)
	assert.True(t, m.Transpose().Eq(NewI8Mat2(1, 3, 2, 4)))
}

func TestI8Mat2Det(t *testing.T) {
	// Use 1*4 - 2*3 = -2
	assert.Equal(t, int8(-2), NewI8Mat2(1, 2, 3, 4).Det())
}

func TestI8Mat2Inverse(t *testing.T) {
	m := NewI8Mat2(1, 2, 3, 4)
	inv := m.Inverse()
	product := m.Float32().Mul(inv)
	identity := Mat2Identity()
	for r := 0; r < 2; r++ {
		for c := 0; c < 2; c++ {
			diff := product.At(r, c) - identity.At(r, c)
			assert.False(t, diff > 1e-5 || diff < -1e-5)
		}
	}
}

func TestI8Mat2InverseSingular(t *testing.T) {
	assert.Equal(t, Mat2{}, NewI8Mat2(1, 2, 2, 4).Inverse())
}

func TestI8Mat2Eq(t *testing.T) {
	a := NewI8Mat2(1, 2, 3, 4)
	assert.True(t, a.Eq(NewI8Mat2(1, 2, 3, 4)))
	assert.False(t, a.Eq(NewI8Mat2(1, 2, 3, 5)))
}

func TestI8Mat2Float32(t *testing.T) {
	got := NewI8Mat2(1, 2, 3, 4).Float32()
	assert.Equal(t, NewMat2(1, 2, 3, 4), got)
}

// ---------------------------------------------------------------------------
// I8Mat3
// ---------------------------------------------------------------------------

func TestI8Mat3Constructor(t *testing.T) {
	m := NewI8Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.Equal(t, int8(1), m.At(0, 0))
	assert.Equal(t, int8(9), m.At(2, 2))
}

func TestI8Mat3Identity(t *testing.T) {
	m := I8Mat3Identity()
	for r := 0; r < 3; r++ {
		for c := 0; c < 3; c++ {
			var want int8
			if r == c {
				want = 1
			}
			assert.Equal(t, want, m.At(r, c))
		}
	}
}

func TestI8Mat3Col(t *testing.T) {
	m := NewI8Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Col(1).Eq(I8Vec3{X: 2, Y: 5, Z: 8}))
}

func TestI8Mat3Row(t *testing.T) {
	m := NewI8Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Row(1).Eq(I8Vec3{X: 4, Y: 5, Z: 6}))
}

func TestI8Mat3Add(t *testing.T) {
	a := NewI8Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	b := NewI8Mat3(9, 8, 7, 6, 5, 4, 3, 2, 1)
	assert.True(t, a.Add(b).Eq(NewI8Mat3(10, 10, 10, 10, 10, 10, 10, 10, 10)))
}

func TestI8Mat3Sub(t *testing.T) {
	a := NewI8Mat3(9, 8, 7, 6, 5, 4, 3, 2, 1)
	b := NewI8Mat3(1, 2, 3, 4, 5, 4, 3, 2, 1)
	got := a.Sub(b)
	assert.True(t, got.Eq(NewI8Mat3(8, 6, 4, 2, 0, 0, 0, 0, 0)))
}

func TestI8Mat3Scale(t *testing.T) {
	got := NewI8Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9).Scale(2)
	assert.True(t, got.Eq(NewI8Mat3(2, 4, 6, 8, 10, 12, 14, 16, 18)))
}

func TestI8Mat3Mul(t *testing.T) {
	m := NewI8Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Mul(I8Mat3Identity()).Eq(m))
}

func TestI8Mat3MulNonTrivial(t *testing.T) {
	a := NewI8Mat3(1, 2, 0, 0, 1, 1, 1, 0, 1)
	b := NewI8Mat3(1, 0, 1, 0, 1, 0, 1, 1, 0)
	assert.True(t, a.Mul(b).Eq(NewI8Mat3(1, 2, 1, 1, 2, 0, 2, 1, 1)))
}

func TestI8Mat3MulVec3(t *testing.T) {
	m := I8Mat3Identity()
	v := I8Vec3{X: 3, Y: 4, Z: 5}
	assert.True(t, m.MulVec3(v).Eq(v))
}

func TestI8Mat3Transpose(t *testing.T) {
	m := NewI8Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Transpose().Eq(NewI8Mat3(1, 4, 7, 2, 5, 8, 3, 6, 9)))
}

func TestI8Mat3Det(t *testing.T) {
	// Diagonal: det = 1*2*3 = 6
	m := NewI8Mat3(1, 0, 0, 0, 2, 0, 0, 0, 3)
	assert.Equal(t, int8(6), m.Det())
}

func TestI8Mat3Inverse(t *testing.T) {
	m := NewI8Mat3(1, 0, 0, 0, 2, 0, 0, 0, 3)
	inv := m.Inverse()
	product := m.Float32().Mul(inv)
	identity := Mat3Identity()
	for r := 0; r < 3; r++ {
		for c := 0; c < 3; c++ {
			diff := product.At(r, c) - identity.At(r, c)
			assert.False(t, diff > 1e-4 || diff < -1e-4)
		}
	}
}

func TestI8Mat3InverseSingular(t *testing.T) {
	assert.Equal(t, Mat3{}, NewI8Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9).Inverse())
}

func TestI8Mat3Eq(t *testing.T) {
	a := NewI8Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, a.Eq(NewI8Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)))
	assert.False(t, a.Eq(I8Mat3Identity()))
}

func TestI8Mat3Float32(t *testing.T) {
	got := NewI8Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9).Float32()
	assert.Equal(t, NewMat3(1, 2, 3, 4, 5, 6, 7, 8, 9), got)
}

// ---------------------------------------------------------------------------
// I8Mat4
// ---------------------------------------------------------------------------

func TestI8Mat4Constructor(t *testing.T) {
	m := NewI8Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.Equal(t, int8(1), m.At(0, 0))
	assert.Equal(t, int8(16), m.At(3, 3))
}

func TestI8Mat4Identity(t *testing.T) {
	m := I8Mat4Identity()
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			var want int8
			if r == c {
				want = 1
			}
			assert.Equal(t, want, m.At(r, c))
		}
	}
}

func TestI8Mat4Col(t *testing.T) {
	m := NewI8Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Col(2).Eq(I8Vec4{X: 3, Y: 7, Z: 11, W: 15}))
}

func TestI8Mat4Row(t *testing.T) {
	m := NewI8Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Row(2).Eq(I8Vec4{X: 9, Y: 10, Z: 11, W: 12}))
}

func TestI8Mat4Add(t *testing.T) {
	a := I8Mat4Identity()
	got := a.Add(a)
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			assert.Equal(t, a.At(r, c)*2, got.At(r, c))
		}
	}
}

func TestI8Mat4Sub(t *testing.T) {
	a := I8Mat4Identity()
	assert.True(t, a.Sub(a).Eq(I8Mat4{}))
}

func TestI8Mat4Scale(t *testing.T) {
	m := I8Mat4Identity()
	got := m.Scale(3)
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			assert.Equal(t, m.At(r, c)*3, got.At(r, c))
		}
	}
}

func TestI8Mat4Mul(t *testing.T) {
	m := NewI8Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Mul(I8Mat4Identity()).Eq(m))
}

func TestI8Mat4MulVec4(t *testing.T) {
	v := I8Vec4{X: 1, Y: 2, Z: 3, W: 4}
	assert.True(t, I8Mat4Identity().MulVec4(v).Eq(v))
}

func TestI8Mat4Transpose(t *testing.T) {
	m := NewI8Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	want := NewI8Mat4(1, 5, 9, 13, 2, 6, 10, 14, 3, 7, 11, 15, 4, 8, 12, 16)
	assert.True(t, m.Transpose().Eq(want))
}

func TestI8Mat4TransposeDouble(t *testing.T) {
	m := NewI8Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Transpose().Transpose().Eq(m))
}

func TestI8Mat4Det(t *testing.T) {
	m := NewI8Mat4(1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4)
	assert.Equal(t, int8(24), m.Det())
}

func TestI8Mat4Inverse(t *testing.T) {
	m := NewI8Mat4(1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 1)
	inv := m.Inverse()
	product := m.Float32().Mul(inv)
	identity := Mat4Identity()
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			diff := product.At(r, c) - identity.At(r, c)
			assert.False(t, diff > 1e-4 || diff < -1e-4)
		}
	}
}

func TestI8Mat4InverseSingular(t *testing.T) {
	m := NewI8Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.Equal(t, Mat4{}, m.Inverse())
}

func TestI8Mat4Mat3(t *testing.T) {
	m := NewI8Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Mat3().Eq(NewI8Mat3(1, 2, 3, 5, 6, 7, 9, 10, 11)))
}

func TestI8Mat4Eq(t *testing.T) {
	assert.True(t, I8Mat4Identity().Eq(I8Mat4Identity()))
	assert.False(t, I8Mat4Identity().Eq(I8Mat4{}))
}

func TestI8Mat4Float32(t *testing.T) {
	assert.Equal(t, Mat4Identity(), I8Mat4Identity().Float32())
}
