// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// I8Vec3 is a 3-component int8 vector.
type I8Vec3 struct {
	X int8
	Y int8
	Z int8
}

func NewI8Vec3(x int8, y int8, z int8) I8Vec3 {
	return I8Vec3{X: x, Y: y, Z: z}
}

func (a I8Vec3) Add(b I8Vec3) I8Vec3 {
	return I8Vec3{
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
	}
}

func (a I8Vec3) Sub(b I8Vec3) I8Vec3 {
	return I8Vec3{
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
	}
}

func (v I8Vec3) Scale(s int8) I8Vec3 {
	return I8Vec3{
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
	}
}

func (a I8Vec3) Dot(b I8Vec3) int8 {
	return a.X*b.X + a.Y*b.Y + a.Z*b.Z
}

func (a I8Vec3) Cross(b I8Vec3) I8Vec3 {
	return I8Vec3{
		X: a.Y*b.Z - a.Z*b.Y,
		Y: a.Z*b.X - a.X*b.Z,
		Z: a.X*b.Y - a.Y*b.X,
	}
}

func (v I8Vec3) LenSq() int8 {
	return v.Dot(v)
}

func (v I8Vec3) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y) + float64(v.Z)*float64(v.Z)))
}

func (v I8Vec3) Normalize() Vec3 {
	l := v.Len()
	if l == 0 {
		return Vec3{}
	}
	return Vec3{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
		Z: float32(v.Z) / l,
	}
}

func (a I8Vec3) Lerp(b I8Vec3, t float32) Vec3 {
	return Vec3{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
		Z: float32(a.Z) + (float32(b.Z)-float32(a.Z))*t,
	}
}

func (a I8Vec3) Dist(b I8Vec3) float32 {
	d := a.Sub(b)
	return d.Len()
}

func (a I8Vec3) Eq(b I8Vec3) bool {
	return a.X == b.X && a.Y == b.Y && a.Z == b.Z
}

func (v I8Vec3) Float32() Vec3 {
	return Vec3{
		X: float32(v.X),
		Y: float32(v.Y),
		Z: float32(v.Z),
	}
}

func (v I8Vec3) XY() I8Vec2 {
	return I8Vec2{X: v.X, Y: v.Y}
}
