// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	"encoding/json"
	"math"
)

// I8Vec4 is a 4-component int8 vector.
type I8Vec4 struct {
	X int8
	Y int8
	Z int8
	W int8
}

func NewI8Vec4(x int8, y int8, z int8, w int8) I8Vec4 {
	return I8Vec4{X: x, Y: y, Z: z, W: w}
}

func (a I8Vec4) Add(b I8Vec4) I8Vec4 {
	return I8Vec4{
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
		W: a.W + b.W,
	}
}

func (a I8Vec4) Sub(b I8Vec4) I8Vec4 {
	return I8Vec4{
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
		W: a.W - b.W,
	}
}

func (v I8Vec4) Scale(s int8) I8Vec4 {
	return I8Vec4{
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
		W: v.W * s,
	}
}

func (a I8Vec4) Dot(b I8Vec4) int8 {
	return a.X*b.X + a.Y*b.Y + a.Z*b.Z + a.W*b.W
}

func (v I8Vec4) LenSq() int8 {
	return v.Dot(v)
}

func (v I8Vec4) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y) + float64(v.Z)*float64(v.Z) + float64(v.W)*float64(v.W)))
}

func (v I8Vec4) Normalize() Vec4 {
	l := v.Len()
	if l == 0 {
		return Vec4{}
	}
	return Vec4{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
		Z: float32(v.Z) / l,
		W: float32(v.W) / l,
	}
}

func (a I8Vec4) Lerp(b I8Vec4, t float32) Vec4 {
	return Vec4{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
		Z: float32(a.Z) + (float32(b.Z)-float32(a.Z))*t,
		W: float32(a.W) + (float32(b.W)-float32(a.W))*t,
	}
}

func (a I8Vec4) Dist(b I8Vec4) float32 {
	return float32(math.Sqrt((float64(a.X)-float64(b.X))*(float64(a.X)-float64(b.X)) + (float64(a.Y)-float64(b.Y))*(float64(a.Y)-float64(b.Y)) + (float64(a.Z)-float64(b.Z))*(float64(a.Z)-float64(b.Z)) + (float64(a.W)-float64(b.W))*(float64(a.W)-float64(b.W))))
}

func (a I8Vec4) Eq(b I8Vec4) bool {
	return a.X == b.X && a.Y == b.Y && a.Z == b.Z && a.W == b.W
}

func (v I8Vec4) Float32() Vec4 {
	return Vec4{
		X: float32(v.X),
		Y: float32(v.Y),
		Z: float32(v.Z),
		W: float32(v.W),
	}
}

func (v I8Vec4) XY() I8Vec2 {
	return I8Vec2{X: v.X, Y: v.Y}
}

func (v I8Vec4) XYZ() I8Vec3 {
	return I8Vec3{X: v.X, Y: v.Y, Z: v.Z}
}

func (v I8Vec4) MarshalJSON() ([]byte, error) {
	return json.Marshal([4]int8{v.X, v.Y, v.Z, v.W})
}

func (v *I8Vec4) UnmarshalJSON(data []byte) error {
	var arr [4]int8
	if err := json.Unmarshal(data, &arr); err != nil {
		return err
	}
	v.X = arr[0]
	v.Y = arr[1]
	v.Z = arr[2]
	v.W = arr[3]
	return nil
}
