// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// I8Vec2 is a 2-component int8 vector.
type I8Vec2 struct {
	X int8
	Y int8
}

func NewI8Vec2(x int8, y int8) I8Vec2 {
	return I8Vec2{X: x, Y: y}
}

func (a I8Vec2) Add(b I8Vec2) I8Vec2 {
	return I8Vec2{
		X: a.X + b.X,
		Y: a.Y + b.Y,
	}
}

func (a I8Vec2) Sub(b I8Vec2) I8Vec2 {
	return I8Vec2{
		X: a.X - b.X,
		Y: a.Y - b.Y,
	}
}

func (v I8Vec2) Scale(s int8) I8Vec2 {
	return I8Vec2{
		X: v.X * s,
		Y: v.Y * s,
	}
}

func (a I8Vec2) Dot(b I8Vec2) int8 {
	return a.X*b.X + a.Y*b.Y
}

func (v I8Vec2) LenSq() int8 {
	return v.Dot(v)
}

func (v I8Vec2) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y)))
}

func (v I8Vec2) Normalize() Vec2 {
	l := v.Len()
	if l == 0 {
		return Vec2{}
	}
	return Vec2{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
	}
}

func (a I8Vec2) Lerp(b I8Vec2, t float32) Vec2 {
	return Vec2{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
	}
}

func (a I8Vec2) Dist(b I8Vec2) float32 {
	return float32(math.Sqrt((float64(a.X)-float64(b.X))*(float64(a.X)-float64(b.X)) + (float64(a.Y)-float64(b.Y))*(float64(a.Y)-float64(b.Y))))
}

func (a I8Vec2) Eq(b I8Vec2) bool {
	return a.X == b.X && a.Y == b.Y
}

func (v I8Vec2) Float32() Vec2 {
	return Vec2{
		X: float32(v.X),
		Y: float32(v.Y),
	}
}
