// Code generated by cmd/gen; DO NOT EDIT.

package math

// TMat3 is a generic 3x3 matrix in column-major order.
type TMat3[T Numeric] struct {
	Data [9]T
}

// NewTMat3 creates a 3x3 matrix from row-major arguments.
func NewTMat3[T Numeric](
	m00, m01, m02 T,
	m10, m11, m12 T,
	m20, m21, m22 T,
) TMat3[T] {
	return TMat3[T]{Data: [9]T{
		m00, m10, m20, // col 0
		m01, m11, m21, // col 1
		m02, m12, m22, // col 2
	}}
}

func (m TMat3[T]) Col(c int) TVec3[T] {
	i := c * 3
	return TVec3[T]{X: m.Data[i+0], Y: m.Data[i+1], Z: m.Data[i+2]}
}

func (m TMat3[T]) Row(r int) TVec3[T] {
	return TVec3[T]{X: m.Data[r+0], Y: m.Data[r+3], Z: m.Data[r+6]}
}

func (m TMat3[T]) At(row, col int) T {
	return m.Data[col*3+row]
}

func (a TMat3[T]) Add(b TMat3[T]) TMat3[T] {
	var out TMat3[T]
	for i := range out.Data {
		out.Data[i] = a.Data[i] + b.Data[i]
	}
	return out
}

func (a TMat3[T]) Sub(b TMat3[T]) TMat3[T] {
	var out TMat3[T]
	for i := range out.Data {
		out.Data[i] = a.Data[i] - b.Data[i]
	}
	return out
}

func (m TMat3[T]) Scale(s T) TMat3[T] {
	var out TMat3[T]
	for i := range out.Data {
		out.Data[i] = m.Data[i] * s
	}
	return out
}

func (a TMat3[T]) Mul(b TMat3[T]) TMat3[T] {
	var out TMat3[T]
	for c := 0; c < 3; c++ {
		bc := b.Col(c)
		for r := 0; r < 3; r++ {
			out.Data[c*3+r] = a.Row(r).Dot(bc)
		}
	}
	return out
}

func (m TMat3[T]) MulVec3(v TVec3[T]) TVec3[T] {
	return TVec3[T]{
		X: m.Row(0).Dot(v),
		Y: m.Row(1).Dot(v),
		Z: m.Row(2).Dot(v),
	}
}

func (m TMat3[T]) Transpose() TMat3[T] {
	var out TMat3[T]
	for r := 0; r < 3; r++ {
		for c := 0; c < 3; c++ {
			out.Data[c*3+r] = m.Data[r*3+c]
		}
	}
	return out
}

func (m TMat3[T]) Det() T {
	return m.At(0, 0)*(m.At(1, 1)*m.At(2, 2)-m.At(1, 2)*m.At(2, 1)) -
		m.At(0, 1)*(m.At(1, 0)*m.At(2, 2)-m.At(1, 2)*m.At(2, 0)) +
		m.At(0, 2)*(m.At(1, 0)*m.At(2, 1)-m.At(1, 1)*m.At(2, 0))
}
func (a TMat3[T]) Eq(b TMat3[T]) bool {
	for i := range a.Data {
		if a.Data[i] != b.Data[i] {
			return false
		}
	}
	return true
}
