// Code generated by cmd/gen; DO NOT EDIT.

package math

// TMat4 is a generic 4x4 matrix in column-major order.
type TMat4[T Numeric] struct {
	Data [16]T
}

// NewTMat4 creates a 4x4 matrix from row-major arguments.
func NewTMat4[T Numeric](
	m00, m01, m02, m03 T,
	m10, m11, m12, m13 T,
	m20, m21, m22, m23 T,
	m30, m31, m32, m33 T,
) TMat4[T] {
	return TMat4[T]{Data: [16]T{
		m00, m10, m20, m30, // col 0
		m01, m11, m21, m31, // col 1
		m02, m12, m22, m32, // col 2
		m03, m13, m23, m33, // col 3
	}}
}

func (m TMat4[T]) Col(c int) TVec4[T] {
	i := c * 4
	return TVec4[T]{X: m.Data[i+0], Y: m.Data[i+1], Z: m.Data[i+2], W: m.Data[i+3]}
}

func (m TMat4[T]) Row(r int) TVec4[T] {
	return TVec4[T]{X: m.Data[r+0], Y: m.Data[r+4], Z: m.Data[r+8], W: m.Data[r+12]}
}

func (m TMat4[T]) At(row, col int) T {
	return m.Data[col*4+row]
}

func (a TMat4[T]) Add(b TMat4[T]) TMat4[T] {
	var out TMat4[T]
	for i := range out.Data {
		out.Data[i] = a.Data[i] + b.Data[i]
	}
	return out
}

func (a TMat4[T]) Sub(b TMat4[T]) TMat4[T] {
	var out TMat4[T]
	for i := range out.Data {
		out.Data[i] = a.Data[i] - b.Data[i]
	}
	return out
}

func (m TMat4[T]) Scale(s T) TMat4[T] {
	var out TMat4[T]
	for i := range out.Data {
		out.Data[i] = m.Data[i] * s
	}
	return out
}

func (a TMat4[T]) Mul(b TMat4[T]) TMat4[T] {
	var out TMat4[T]
	for c := 0; c < 4; c++ {
		bc := b.Col(c)
		for r := 0; r < 4; r++ {
			out.Data[c*4+r] = a.Row(r).Dot(bc)
		}
	}
	return out
}

func (m TMat4[T]) MulVec4(v TVec4[T]) TVec4[T] {
	return TVec4[T]{
		X: m.Row(0).Dot(v),
		Y: m.Row(1).Dot(v),
		Z: m.Row(2).Dot(v),
		W: m.Row(3).Dot(v),
	}
}

func (m TMat4[T]) Transpose() TMat4[T] {
	var out TMat4[T]
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			out.Data[c*4+r] = m.Data[r*4+c]
		}
	}
	return out
}

func (m TMat4[T]) cofactor(row, col int) T {
	var sub [9]T
	idx := 0
	for c := 0; c < 4; c++ {
		if c == col {
			continue
		}
		for r := 0; r < 4; r++ {
			if r == row {
				continue
			}
			sub[idx] = m.At(r, c)
			idx++
		}
	}
	return sub[0]*(sub[4]*sub[8]-sub[5]*sub[7]) -
		sub[3]*(sub[1]*sub[8]-sub[2]*sub[7]) +
		sub[6]*(sub[1]*sub[5]-sub[2]*sub[4])
}

func (m TMat4[T]) Det() T {
	a, b, c, d := m.At(0, 0), m.At(0, 1), m.At(0, 2), m.At(0, 3)
	return a*m.cofactor(0, 0) - b*m.cofactor(0, 1) + c*m.cofactor(0, 2) - d*m.cofactor(0, 3)
}
func (a TMat4[T]) Eq(b TMat4[T]) bool {
	for i := range a.Data {
		if a.Data[i] != b.Data[i] {
			return false
		}
	}
	return true
}
