// Code generated by cmd/gen; DO NOT EDIT.

package math

import "encoding/json"

// TQuat is a generic quaternion with scalar part W and vector part (X, Y, Z).
type TQuat[T Float] struct {
	W T
	X T
	Y T
	Z T
}

func (a TQuat[T]) Add(b TQuat[T]) TQuat[T] {
	return TQuat[T]{
		W: a.W + b.W,
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
	}
}

func (a TQuat[T]) Sub(b TQuat[T]) TQuat[T] {
	return TQuat[T]{
		W: a.W - b.W,
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
	}
}

func (v TQuat[T]) Scale(s T) TQuat[T] {
	return TQuat[T]{
		W: v.W * s,
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
	}
}

func (a TQuat[T]) Dot(b TQuat[T]) T {
	return a.W*b.W + a.X*b.X + a.Y*b.Y + a.Z*b.Z
}

func (v TQuat[T]) LenSq() T {
	return v.Dot(v)
}

func (a TQuat[T]) Eq(b TQuat[T]) bool {
	return a.W == b.W && a.X == b.X && a.Y == b.Y && a.Z == b.Z
}

func (v TQuat[T]) MarshalJSON() ([]byte, error) {
	return json.Marshal([4]T{v.W, v.X, v.Y, v.Z})
}

func (v *TQuat[T]) UnmarshalJSON(data []byte) error {
	var arr [4]T
	if err := json.Unmarshal(data, &arr); err != nil {
		return err
	}
	v.W = arr[0]
	v.X = arr[1]
	v.Y = arr[2]
	v.Z = arr[3]
	return nil
}
