// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	"testing"

	"github.com/wow-look-at-my/testify/assert"
)

// ---------------------------------------------------------------------------
// U16Vec2
// ---------------------------------------------------------------------------

func TestU16Vec2Constructor(t *testing.T) {
	v := NewU16Vec2(3, 4)
	assert.Equal(t, uint16(3), v.X)
	assert.Equal(t, uint16(4), v.Y)
}

func TestU16Vec2Add(t *testing.T) {
	got := U16Vec2{X: 1, Y: 2}.Add(U16Vec2{X: 3, Y: 4})
	assert.True(t, got.Eq(U16Vec2{X: 4, Y: 6}))
}

func TestU16Vec2Sub(t *testing.T) {
	got := U16Vec2{X: 5, Y: 7}.Sub(U16Vec2{X: 2, Y: 3})
	assert.True(t, got.Eq(U16Vec2{X: 3, Y: 4}))
}

func TestU16Vec2Scale(t *testing.T) {
	got := U16Vec2{X: 2, Y: 3}.Scale(3)
	assert.True(t, got.Eq(U16Vec2{X: 6, Y: 9}))
}

func TestU16Vec2Dot(t *testing.T) {
	assert.Equal(t, uint16(11), U16Vec2{X: 1, Y: 2}.Dot(U16Vec2{X: 3, Y: 4}))
}

func TestU16Vec2LenSq(t *testing.T) {
	assert.Equal(t, uint16(25), U16Vec2{X: 3, Y: 4}.LenSq())
}

func TestU16Vec2Len(t *testing.T) {
	assert.Equal(t, float32(5), U16Vec2{X: 3, Y: 4}.Len())
}

func TestU16Vec2Normalize(t *testing.T) {
	got := U16Vec2{X: 3, Y: 4}.Normalize()
	assert.True(t, got.ApproxEq(NewVec2(0.6, 0.8), 1e-6))
}

func TestU16Vec2NormalizeZero(t *testing.T) {
	assert.True(t, U16Vec2{}.Normalize().Eq(Vec2{}))
}

func TestU16Vec2Dist(t *testing.T) {
	assert.Equal(t, float32(5), U16Vec2{}.Dist(U16Vec2{X: 3, Y: 4}))
}

func TestU16Vec2Lerp(t *testing.T) {
	got := U16Vec2{X: 0, Y: 0}.Lerp(U16Vec2{X: 10, Y: 20}, 0.5)
	assert.True(t, got.Eq(NewVec2(5, 10)))
}

func TestU16Vec2Eq(t *testing.T) {
	assert.True(t, U16Vec2{X: 1, Y: 2}.Eq(U16Vec2{X: 1, Y: 2}))
	assert.False(t, U16Vec2{X: 1, Y: 2}.Eq(U16Vec2{X: 1, Y: 3}))
}

func TestU16Vec2Float32(t *testing.T) {
	assert.True(t, U16Vec2{X: 3, Y: 4}.Float32().Eq(NewVec2(3, 4)))
}

// ---------------------------------------------------------------------------
// U16Vec3
// ---------------------------------------------------------------------------

func TestU16Vec3Constructor(t *testing.T) {
	v := NewU16Vec3(1, 2, 3)
	assert.Equal(t, uint16(1), v.X)
	assert.Equal(t, uint16(2), v.Y)
	assert.Equal(t, uint16(3), v.Z)
}

func TestU16Vec3Add(t *testing.T) {
	got := U16Vec3{X: 1, Y: 2, Z: 3}.Add(U16Vec3{X: 4, Y: 5, Z: 6})
	assert.True(t, got.Eq(U16Vec3{X: 5, Y: 7, Z: 9}))
}

func TestU16Vec3Sub(t *testing.T) {
	got := U16Vec3{X: 5, Y: 7, Z: 9}.Sub(U16Vec3{X: 1, Y: 2, Z: 3})
	assert.True(t, got.Eq(U16Vec3{X: 4, Y: 5, Z: 6}))
}

func TestU16Vec3Scale(t *testing.T) {
	got := U16Vec3{X: 1, Y: 2, Z: 3}.Scale(2)
	assert.True(t, got.Eq(U16Vec3{X: 2, Y: 4, Z: 6}))
}

func TestU16Vec3Dot(t *testing.T) {
	assert.Equal(t, uint16(32), U16Vec3{X: 1, Y: 2, Z: 3}.Dot(U16Vec3{X: 4, Y: 5, Z: 6}))
}

func TestU16Vec3Cross(t *testing.T) {
	got := U16Vec3{X: 1, Y: 0, Z: 0}.Cross(U16Vec3{X: 0, Y: 1, Z: 0})
	assert.True(t, got.Eq(U16Vec3{X: 0, Y: 0, Z: 1}))
}

func TestU16Vec3LenSq(t *testing.T) {
	assert.Equal(t, uint16(14), U16Vec3{X: 1, Y: 2, Z: 3}.LenSq())
}

func TestU16Vec3Len(t *testing.T) {
	assert.Equal(t, float32(7), U16Vec3{X: 2, Y: 3, Z: 6}.Len())
}

func TestU16Vec3Normalize(t *testing.T) {
	got := U16Vec3{X: 0, Y: 0, Z: 5}.Normalize()
	assert.True(t, got.ApproxEq(NewVec3(0, 0, 1), 1e-6))
}

func TestU16Vec3NormalizeZero(t *testing.T) {
	assert.True(t, U16Vec3{}.Normalize().Eq(Vec3{}))
}

func TestU16Vec3Dist(t *testing.T) {
	assert.Equal(t, float32(7), U16Vec3{}.Dist(U16Vec3{X: 2, Y: 3, Z: 6}))
}

func TestU16Vec3Lerp(t *testing.T) {
	got := U16Vec3{}.Lerp(U16Vec3{X: 10, Y: 20, Z: 30}, 0.5)
	assert.True(t, got.ApproxEq(NewVec3(5, 10, 15), 1e-6))
}

func TestU16Vec3Eq(t *testing.T) {
	assert.True(t, U16Vec3{X: 1, Y: 2, Z: 3}.Eq(U16Vec3{X: 1, Y: 2, Z: 3}))
	assert.False(t, U16Vec3{X: 1, Y: 2, Z: 3}.Eq(U16Vec3{X: 1, Y: 2, Z: 4}))
}

func TestU16Vec3Float32(t *testing.T) {
	assert.True(t, U16Vec3{X: 1, Y: 2, Z: 3}.Float32().Eq(NewVec3(1, 2, 3)))
}

func TestU16Vec3XY(t *testing.T) {
	assert.True(t, U16Vec3{X: 1, Y: 2, Z: 3}.XY().Eq(U16Vec2{X: 1, Y: 2}))
}

// ---------------------------------------------------------------------------
// U16Vec4
// ---------------------------------------------------------------------------

func TestU16Vec4Constructor(t *testing.T) {
	v := NewU16Vec4(1, 2, 3, 4)
	assert.Equal(t, uint16(1), v.X)
	assert.Equal(t, uint16(4), v.W)
}

func TestU16Vec4Add(t *testing.T) {
	got := U16Vec4{X: 1, Y: 2, Z: 3, W: 4}.Add(U16Vec4{X: 5, Y: 6, Z: 7, W: 8})
	assert.True(t, got.Eq(U16Vec4{X: 6, Y: 8, Z: 10, W: 12}))
}

func TestU16Vec4Sub(t *testing.T) {
	got := U16Vec4{X: 5, Y: 7, Z: 9, W: 11}.Sub(U16Vec4{X: 1, Y: 2, Z: 3, W: 4})
	assert.True(t, got.Eq(U16Vec4{X: 4, Y: 5, Z: 6, W: 7}))
}

func TestU16Vec4Scale(t *testing.T) {
	got := U16Vec4{X: 1, Y: 2, Z: 3, W: 4}.Scale(2)
	assert.True(t, got.Eq(U16Vec4{X: 2, Y: 4, Z: 6, W: 8}))
}

func TestU16Vec4Dot(t *testing.T) {
	assert.Equal(t, uint16(70), U16Vec4{X: 1, Y: 2, Z: 3, W: 4}.Dot(U16Vec4{X: 5, Y: 6, Z: 7, W: 8}))
}

func TestU16Vec4LenSq(t *testing.T) {
	assert.Equal(t, uint16(25), U16Vec4{X: 1, Y: 2, Z: 2, W: 4}.LenSq())
}

func TestU16Vec4Len(t *testing.T) {
	assert.Equal(t, float32(5), U16Vec4{X: 1, Y: 2, Z: 2, W: 4}.Len())
}

func TestU16Vec4Normalize(t *testing.T) {
	got := U16Vec4{X: 0, Y: 0, Z: 0, W: 5}.Normalize()
	assert.True(t, got.ApproxEq(NewVec4(0, 0, 0, 1), 1e-6))
}

func TestU16Vec4NormalizeZero(t *testing.T) {
	assert.True(t, U16Vec4{}.Normalize().Eq(Vec4{}))
}

func TestU16Vec4Dist(t *testing.T) {
	assert.Equal(t, float32(5), U16Vec4{}.Dist(U16Vec4{X: 1, Y: 2, Z: 2, W: 4}))
}

func TestU16Vec4Lerp(t *testing.T) {
	got := U16Vec4{}.Lerp(U16Vec4{X: 10, Y: 20, Z: 30, W: 40}, 0.5)
	assert.True(t, got.Eq(NewVec4(5, 10, 15, 20)))
}

func TestU16Vec4Eq(t *testing.T) {
	assert.True(t, U16Vec4{X: 1, Y: 2, Z: 3, W: 4}.Eq(U16Vec4{X: 1, Y: 2, Z: 3, W: 4}))
	assert.False(t, U16Vec4{X: 1, Y: 2, Z: 3, W: 4}.Eq(U16Vec4{X: 1, Y: 2, Z: 3, W: 5}))
}

func TestU16Vec4Float32(t *testing.T) {
	assert.True(t, U16Vec4{X: 1, Y: 2, Z: 3, W: 4}.Float32().Eq(NewVec4(1, 2, 3, 4)))
}

func TestU16Vec4XYZ(t *testing.T) {
	assert.True(t, U16Vec4{X: 1, Y: 2, Z: 3, W: 4}.XYZ().Eq(U16Vec3{X: 1, Y: 2, Z: 3}))
}

func TestU16Vec4XY(t *testing.T) {
	assert.True(t, U16Vec4{X: 1, Y: 2, Z: 3, W: 4}.XY().Eq(U16Vec2{X: 1, Y: 2}))
}

// ---------------------------------------------------------------------------
// U16Mat2
// ---------------------------------------------------------------------------

func TestU16Mat2Constructor(t *testing.T) {
	m := NewU16Mat2(1, 2, 3, 4)
	assert.Equal(t, uint16(1), m.At(0, 0))
	assert.Equal(t, uint16(2), m.At(0, 1))
	assert.Equal(t, uint16(3), m.At(1, 0))
	assert.Equal(t, uint16(4), m.At(1, 1))
}

func TestU16Mat2Identity(t *testing.T) {
	m := U16Mat2Identity()
	assert.Equal(t, uint16(1), m.At(0, 0))
	assert.Equal(t, uint16(0), m.At(0, 1))
	assert.Equal(t, uint16(0), m.At(1, 0))
	assert.Equal(t, uint16(1), m.At(1, 1))
}

func TestU16Mat2Col(t *testing.T) {
	m := NewU16Mat2(1, 2, 3, 4)
	assert.True(t, m.Col(0).Eq(U16Vec2{X: 1, Y: 3}))
	assert.True(t, m.Col(1).Eq(U16Vec2{X: 2, Y: 4}))
}

func TestU16Mat2Row(t *testing.T) {
	m := NewU16Mat2(1, 2, 3, 4)
	assert.True(t, m.Row(0).Eq(U16Vec2{X: 1, Y: 2}))
	assert.True(t, m.Row(1).Eq(U16Vec2{X: 3, Y: 4}))
}

func TestU16Mat2Add(t *testing.T) {
	a := NewU16Mat2(1, 2, 3, 4)
	b := NewU16Mat2(5, 6, 7, 8)
	got := a.Add(b)
	assert.True(t, got.Eq(NewU16Mat2(6, 8, 10, 12)))
}

func TestU16Mat2Sub(t *testing.T) {
	a := NewU16Mat2(5, 6, 7, 8)
	b := NewU16Mat2(1, 2, 3, 4)
	got := a.Sub(b)
	assert.True(t, got.Eq(NewU16Mat2(4, 4, 4, 4)))
}

func TestU16Mat2Scale(t *testing.T) {
	got := NewU16Mat2(1, 2, 3, 4).Scale(2)
	assert.True(t, got.Eq(NewU16Mat2(2, 4, 6, 8)))
}

func TestU16Mat2Mul(t *testing.T) {
	a := NewU16Mat2(1, 2, 3, 4)
	b := NewU16Mat2(5, 6, 7, 8)
	got := a.Mul(b)
	assert.True(t, got.Eq(NewU16Mat2(19, 22, 43, 50)))
}

func TestU16Mat2MulIdentity(t *testing.T) {
	m := NewU16Mat2(1, 2, 3, 4)
	assert.True(t, m.Mul(U16Mat2Identity()).Eq(m))
}

func TestU16Mat2MulVec2(t *testing.T) {
	m := NewU16Mat2(1, 2, 3, 4)
	v := NewU16Vec2(5, 6)
	got := m.MulVec2(v)
	assert.True(t, got.Eq(NewU16Vec2(17, 39)))
}

func TestU16Mat2Transpose(t *testing.T) {
	m := NewU16Mat2(1, 2, 3, 4)
	assert.True(t, m.Transpose().Eq(NewU16Mat2(1, 3, 2, 4)))
}

func TestU16Mat2Det(t *testing.T) {
	// Use 3*2 - 1*1 = 5
	assert.Equal(t, uint16(5), NewU16Mat2(3, 1, 1, 2).Det())
}

func TestU16Mat2Inverse(t *testing.T) {
	m := NewU16Mat2(3, 1, 1, 2)
	inv := m.Inverse()
	product := m.Float32().Mul(inv)
	identity := Mat2Identity()
	for r := 0; r < 2; r++ {
		for c := 0; c < 2; c++ {
			diff := product.At(r, c) - identity.At(r, c)
			assert.False(t, diff > 1e-5 || diff < -1e-5)
		}
	}
}

func TestU16Mat2InverseSingular(t *testing.T) {
	assert.Equal(t, Mat2{}, NewU16Mat2(2, 4, 1, 2).Inverse())
}

func TestU16Mat2Eq(t *testing.T) {
	a := NewU16Mat2(1, 2, 3, 4)
	assert.True(t, a.Eq(NewU16Mat2(1, 2, 3, 4)))
	assert.False(t, a.Eq(NewU16Mat2(1, 2, 3, 5)))
}

func TestU16Mat2Float32(t *testing.T) {
	got := NewU16Mat2(1, 2, 3, 4).Float32()
	assert.Equal(t, NewMat2(1, 2, 3, 4), got)
}

// ---------------------------------------------------------------------------
// U16Mat3
// ---------------------------------------------------------------------------

func TestU16Mat3Constructor(t *testing.T) {
	m := NewU16Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.Equal(t, uint16(1), m.At(0, 0))
	assert.Equal(t, uint16(9), m.At(2, 2))
}

func TestU16Mat3Identity(t *testing.T) {
	m := U16Mat3Identity()
	for r := 0; r < 3; r++ {
		for c := 0; c < 3; c++ {
			var want uint16
			if r == c {
				want = 1
			}
			assert.Equal(t, want, m.At(r, c))
		}
	}
}

func TestU16Mat3Col(t *testing.T) {
	m := NewU16Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Col(1).Eq(U16Vec3{X: 2, Y: 5, Z: 8}))
}

func TestU16Mat3Row(t *testing.T) {
	m := NewU16Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Row(1).Eq(U16Vec3{X: 4, Y: 5, Z: 6}))
}

func TestU16Mat3Add(t *testing.T) {
	a := NewU16Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	b := NewU16Mat3(9, 8, 7, 6, 5, 4, 3, 2, 1)
	assert.True(t, a.Add(b).Eq(NewU16Mat3(10, 10, 10, 10, 10, 10, 10, 10, 10)))
}

func TestU16Mat3Sub(t *testing.T) {
	a := NewU16Mat3(9, 8, 7, 6, 5, 4, 3, 2, 1)
	b := NewU16Mat3(1, 2, 3, 4, 5, 4, 3, 2, 1)
	got := a.Sub(b)
	assert.True(t, got.Eq(NewU16Mat3(8, 6, 4, 2, 0, 0, 0, 0, 0)))
}

func TestU16Mat3Scale(t *testing.T) {
	got := NewU16Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9).Scale(2)
	assert.True(t, got.Eq(NewU16Mat3(2, 4, 6, 8, 10, 12, 14, 16, 18)))
}

func TestU16Mat3Mul(t *testing.T) {
	m := NewU16Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Mul(U16Mat3Identity()).Eq(m))
}

func TestU16Mat3MulNonTrivial(t *testing.T) {
	a := NewU16Mat3(1, 2, 0, 0, 1, 1, 1, 0, 1)
	b := NewU16Mat3(1, 0, 1, 0, 1, 0, 1, 1, 0)
	assert.True(t, a.Mul(b).Eq(NewU16Mat3(1, 2, 1, 1, 2, 0, 2, 1, 1)))
}

func TestU16Mat3MulVec3(t *testing.T) {
	m := U16Mat3Identity()
	v := U16Vec3{X: 3, Y: 4, Z: 5}
	assert.True(t, m.MulVec3(v).Eq(v))
}

func TestU16Mat3Transpose(t *testing.T) {
	m := NewU16Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, m.Transpose().Eq(NewU16Mat3(1, 4, 7, 2, 5, 8, 3, 6, 9)))
}

func TestU16Mat3Det(t *testing.T) {
	// Diagonal: det = 1*2*3 = 6
	m := NewU16Mat3(1, 0, 0, 0, 2, 0, 0, 0, 3)
	assert.Equal(t, uint16(6), m.Det())
}

func TestU16Mat3Inverse(t *testing.T) {
	m := NewU16Mat3(1, 0, 0, 0, 2, 0, 0, 0, 3)
	inv := m.Inverse()
	product := m.Float32().Mul(inv)
	identity := Mat3Identity()
	for r := 0; r < 3; r++ {
		for c := 0; c < 3; c++ {
			diff := product.At(r, c) - identity.At(r, c)
			assert.False(t, diff > 1e-4 || diff < -1e-4)
		}
	}
}

func TestU16Mat3InverseSingular(t *testing.T) {
	assert.Equal(t, Mat3{}, NewU16Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9).Inverse())
}

func TestU16Mat3Eq(t *testing.T) {
	a := NewU16Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)
	assert.True(t, a.Eq(NewU16Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9)))
	assert.False(t, a.Eq(U16Mat3Identity()))
}

func TestU16Mat3Float32(t *testing.T) {
	got := NewU16Mat3(1, 2, 3, 4, 5, 6, 7, 8, 9).Float32()
	assert.Equal(t, NewMat3(1, 2, 3, 4, 5, 6, 7, 8, 9), got)
}

// ---------------------------------------------------------------------------
// U16Mat4
// ---------------------------------------------------------------------------

func TestU16Mat4Constructor(t *testing.T) {
	m := NewU16Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.Equal(t, uint16(1), m.At(0, 0))
	assert.Equal(t, uint16(16), m.At(3, 3))
}

func TestU16Mat4Identity(t *testing.T) {
	m := U16Mat4Identity()
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			var want uint16
			if r == c {
				want = 1
			}
			assert.Equal(t, want, m.At(r, c))
		}
	}
}

func TestU16Mat4Col(t *testing.T) {
	m := NewU16Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Col(2).Eq(U16Vec4{X: 3, Y: 7, Z: 11, W: 15}))
}

func TestU16Mat4Row(t *testing.T) {
	m := NewU16Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Row(2).Eq(U16Vec4{X: 9, Y: 10, Z: 11, W: 12}))
}

func TestU16Mat4Add(t *testing.T) {
	a := U16Mat4Identity()
	got := a.Add(a)
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			assert.Equal(t, a.At(r, c)*2, got.At(r, c))
		}
	}
}

func TestU16Mat4Sub(t *testing.T) {
	a := U16Mat4Identity()
	assert.True(t, a.Sub(a).Eq(U16Mat4{}))
}

func TestU16Mat4Scale(t *testing.T) {
	m := U16Mat4Identity()
	got := m.Scale(3)
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			assert.Equal(t, m.At(r, c)*3, got.At(r, c))
		}
	}
}

func TestU16Mat4Mul(t *testing.T) {
	m := NewU16Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Mul(U16Mat4Identity()).Eq(m))
}

func TestU16Mat4MulVec4(t *testing.T) {
	v := U16Vec4{X: 1, Y: 2, Z: 3, W: 4}
	assert.True(t, U16Mat4Identity().MulVec4(v).Eq(v))
}

func TestU16Mat4Transpose(t *testing.T) {
	m := NewU16Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	want := NewU16Mat4(1, 5, 9, 13, 2, 6, 10, 14, 3, 7, 11, 15, 4, 8, 12, 16)
	assert.True(t, m.Transpose().Eq(want))
}

func TestU16Mat4TransposeDouble(t *testing.T) {
	m := NewU16Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Transpose().Transpose().Eq(m))
}

func TestU16Mat4Det(t *testing.T) {
	m := NewU16Mat4(1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4)
	assert.Equal(t, uint16(24), m.Det())
}

func TestU16Mat4Inverse(t *testing.T) {
	m := NewU16Mat4(1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 1)
	inv := m.Inverse()
	product := m.Float32().Mul(inv)
	identity := Mat4Identity()
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			diff := product.At(r, c) - identity.At(r, c)
			assert.False(t, diff > 1e-4 || diff < -1e-4)
		}
	}
}

func TestU16Mat4InverseSingular(t *testing.T) {
	m := NewU16Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.Equal(t, Mat4{}, m.Inverse())
}

func TestU16Mat4Mat3(t *testing.T) {
	m := NewU16Mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
	assert.True(t, m.Mat3().Eq(NewU16Mat3(1, 2, 3, 5, 6, 7, 9, 10, 11)))
}

func TestU16Mat4Eq(t *testing.T) {
	assert.True(t, U16Mat4Identity().Eq(U16Mat4Identity()))
	assert.False(t, U16Mat4Identity().Eq(U16Mat4{}))
}

func TestU16Mat4Float32(t *testing.T) {
	assert.Equal(t, Mat4Identity(), U16Mat4Identity().Float32())
}
