// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// U16Mat3 is a 3x3 uint16 matrix in column-major order.
type U16Mat3 struct {
	Data [9]uint16
}

// NewU16Mat3 creates a 3x3 matrix from row-major arguments.
func NewU16Mat3(
	m00, m01, m02 uint16,
	m10, m11, m12 uint16,
	m20, m21, m22 uint16,
) U16Mat3 {
	return U16Mat3{Data: [9]uint16{
		m00, m10, m20, // col 0
		m01, m11, m21, // col 1
		m02, m12, m22, // col 2
	}}
}

func U16Mat3Identity() U16Mat3 {
	return NewU16Mat3(1, 0, 0, 0, 1, 0, 0, 0, 1)
}

func (m U16Mat3) Col(c int) U16Vec3 {
	i := c * 3
	return U16Vec3{X: m.Data[i+0], Y: m.Data[i+1], Z: m.Data[i+2]}
}

func (m U16Mat3) Row(r int) U16Vec3 {
	return U16Vec3{X: m.Data[r+0], Y: m.Data[r+3], Z: m.Data[r+6]}
}

func (m U16Mat3) At(row, col int) uint16 {
	return m.Data[col*3+row]
}

func (a U16Mat3) Add(b U16Mat3) U16Mat3 {
	var out U16Mat3
	for i := range out.Data {
		out.Data[i] = a.Data[i] + b.Data[i]
	}
	return out
}

func (a U16Mat3) Sub(b U16Mat3) U16Mat3 {
	var out U16Mat3
	for i := range out.Data {
		out.Data[i] = a.Data[i] - b.Data[i]
	}
	return out
}

func (m U16Mat3) Scale(s uint16) U16Mat3 {
	var out U16Mat3
	for i := range out.Data {
		out.Data[i] = m.Data[i] * s
	}
	return out
}

func (a U16Mat3) Mul(b U16Mat3) U16Mat3 {
	var out U16Mat3
	for c := 0; c < 3; c++ {
		bc := b.Col(c)
		for r := 0; r < 3; r++ {
			out.Data[c*3+r] = a.Row(r).Dot(bc)
		}
	}
	return out
}

func (m U16Mat3) MulVec3(v U16Vec3) U16Vec3 {
	return U16Vec3{
		X: m.Row(0).Dot(v),
		Y: m.Row(1).Dot(v),
		Z: m.Row(2).Dot(v),
	}
}

func (m U16Mat3) Transpose() U16Mat3 {
	var out U16Mat3
	for r := 0; r < 3; r++ {
		for c := 0; c < 3; c++ {
			out.Data[c*3+r] = m.Data[r*3+c]
		}
	}
	return out
}

func (m U16Mat3) Det() uint16 {
	return m.At(0, 0)*(m.At(1, 1)*m.At(2, 2)-m.At(1, 2)*m.At(2, 1)) -
		m.At(0, 1)*(m.At(1, 0)*m.At(2, 2)-m.At(1, 2)*m.At(2, 0)) +
		m.At(0, 2)*(m.At(1, 0)*m.At(2, 1)-m.At(1, 1)*m.At(2, 0))
}

func (m U16Mat3) Inverse() Mat3 {
	d := float32(m.Det())
	if d == 0 {
		return Mat3{}
	}
	invD := 1.0 / d
	f := func(v uint16) float32 { return float32(v) }

	return NewMat3(
		(f(m.At(1, 1))*f(m.At(2, 2))-f(m.At(1, 2))*f(m.At(2, 1)))*invD,
		(f(m.At(0, 2))*f(m.At(2, 1))-f(m.At(0, 1))*f(m.At(2, 2)))*invD,
		(f(m.At(0, 1))*f(m.At(1, 2))-f(m.At(0, 2))*f(m.At(1, 1)))*invD,

		(f(m.At(1, 2))*f(m.At(2, 0))-f(m.At(1, 0))*f(m.At(2, 2)))*invD,
		(f(m.At(0, 0))*f(m.At(2, 2))-f(m.At(0, 2))*f(m.At(2, 0)))*invD,
		(f(m.At(0, 2))*f(m.At(1, 0))-f(m.At(0, 0))*f(m.At(1, 2)))*invD,

		(f(m.At(1, 0))*f(m.At(2, 1))-f(m.At(1, 1))*f(m.At(2, 0)))*invD,
		(f(m.At(0, 1))*f(m.At(2, 0))-f(m.At(0, 0))*f(m.At(2, 1)))*invD,
		(f(m.At(0, 0))*f(m.At(1, 1))-f(m.At(0, 1))*f(m.At(1, 0)))*invD,
	)
}
func (a U16Mat3) Eq(b U16Mat3) bool {
	for i := range a.Data {
		if a.Data[i] != b.Data[i] {
			return false
		}
	}
	return true
}

func (m U16Mat3) Float32() Mat3 {
	var out Mat3
	for i := range m.Data {
		out.Data[i] = float32(m.Data[i])
	}
	return out
}

// ensure math import is used
var _ = math.Sqrt
