// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// U16Mat4 is a 4x4 uint16 matrix in column-major order.
type U16Mat4 struct {
	Data [16]uint16
}

// NewU16Mat4 creates a 4x4 matrix from row-major arguments.
func NewU16Mat4(
	m00, m01, m02, m03 uint16,
	m10, m11, m12, m13 uint16,
	m20, m21, m22, m23 uint16,
	m30, m31, m32, m33 uint16,
) U16Mat4 {
	return U16Mat4{Data: [16]uint16{
		m00, m10, m20, m30, // col 0
		m01, m11, m21, m31, // col 1
		m02, m12, m22, m32, // col 2
		m03, m13, m23, m33, // col 3
	}}
}

func U16Mat4Identity() U16Mat4 {
	return NewU16Mat4(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1)
}

func (m U16Mat4) Col(c int) U16Vec4 {
	i := c * 4
	return U16Vec4{X: m.Data[i+0], Y: m.Data[i+1], Z: m.Data[i+2], W: m.Data[i+3]}
}

func (m U16Mat4) Row(r int) U16Vec4 {
	return U16Vec4{X: m.Data[r+0], Y: m.Data[r+4], Z: m.Data[r+8], W: m.Data[r+12]}
}

func (m U16Mat4) At(row, col int) uint16 {
	return m.Data[col*4+row]
}

func (a U16Mat4) Add(b U16Mat4) U16Mat4 {
	var out U16Mat4
	for i := range out.Data {
		out.Data[i] = a.Data[i] + b.Data[i]
	}
	return out
}

func (a U16Mat4) Sub(b U16Mat4) U16Mat4 {
	var out U16Mat4
	for i := range out.Data {
		out.Data[i] = a.Data[i] - b.Data[i]
	}
	return out
}

func (m U16Mat4) Scale(s uint16) U16Mat4 {
	var out U16Mat4
	for i := range out.Data {
		out.Data[i] = m.Data[i] * s
	}
	return out
}

func (a U16Mat4) Mul(b U16Mat4) U16Mat4 {
	var out U16Mat4
	for c := 0; c < 4; c++ {
		bc := b.Col(c)
		for r := 0; r < 4; r++ {
			out.Data[c*4+r] = a.Row(r).Dot(bc)
		}
	}
	return out
}

func (m U16Mat4) MulVec4(v U16Vec4) U16Vec4 {
	return U16Vec4{
		X: m.Row(0).Dot(v),
		Y: m.Row(1).Dot(v),
		Z: m.Row(2).Dot(v),
		W: m.Row(3).Dot(v),
	}
}

func (m U16Mat4) Transpose() U16Mat4 {
	var out U16Mat4
	for r := 0; r < 4; r++ {
		for c := 0; c < 4; c++ {
			out.Data[c*4+r] = m.Data[r*4+c]
		}
	}
	return out
}

func (m U16Mat4) cofactor(row, col int) float32 {
	var sub [9]float32
	idx := 0
	for c := 0; c < 4; c++ {
		if c == col {
			continue
		}
		for r := 0; r < 4; r++ {
			if r == row {
				continue
			}
			sub[idx] = float32(m.At(r, c))
			idx++
		}
	}
	return sub[0]*(sub[4]*sub[8]-sub[5]*sub[7]) -
		sub[3]*(sub[1]*sub[8]-sub[2]*sub[7]) +
		sub[6]*(sub[1]*sub[5]-sub[2]*sub[4])
}

func (m U16Mat4) Det() uint16 {
	a, b, c, d := m.At(0, 0), m.At(0, 1), m.At(0, 2), m.At(0, 3)
	return uint16(float32(a)*m.cofactor(0, 0) - float32(b)*m.cofactor(0, 1) + float32(c)*m.cofactor(0, 2) - float32(d)*m.cofactor(0, 3))
}

func (m U16Mat4) Inverse() Mat4 {
	d := float32(m.Det())
	if d == 0 {
		return Mat4{}
	}
	invD := 1.0 / d

	var out Mat4
	for c := 0; c < 4; c++ {
		for r := 0; r < 4; r++ {
			sign := float32(1)
			if (r+c)%2 != 0 {
				sign = -1
			}
			out.Data[c*4+r] = sign * m.cofactor(c, r) * invD
		}
	}
	return out
}

func (m U16Mat4) Mat3() U16Mat3 {
	return U16Mat3{Data: [9]uint16{
		m.Data[0], m.Data[1], m.Data[2],
		m.Data[4], m.Data[5], m.Data[6],
		m.Data[8], m.Data[9], m.Data[10],
	}}
}
func (a U16Mat4) Eq(b U16Mat4) bool {
	for i := range a.Data {
		if a.Data[i] != b.Data[i] {
			return false
		}
	}
	return true
}

func (m U16Mat4) Float32() Mat4 {
	var out Mat4
	for i := range m.Data {
		out.Data[i] = float32(m.Data[i])
	}
	return out
}

// ensure math import is used
var _ = math.Sqrt
