// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	"encoding/json"
	"math"
)

// U16Vec3 is a 3-component uint16 vector.
type U16Vec3 struct {
	X uint16
	Y uint16
	Z uint16
}

func NewU16Vec3(x uint16, y uint16, z uint16) U16Vec3 {
	return U16Vec3{X: x, Y: y, Z: z}
}

func (a U16Vec3) Add(b U16Vec3) U16Vec3 {
	return U16Vec3{
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
	}
}

func (a U16Vec3) Sub(b U16Vec3) U16Vec3 {
	return U16Vec3{
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
	}
}

func (v U16Vec3) Scale(s uint16) U16Vec3 {
	return U16Vec3{
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
	}
}

func (a U16Vec3) Dot(b U16Vec3) uint16 {
	return a.X*b.X + a.Y*b.Y + a.Z*b.Z
}

func (a U16Vec3) Cross(b U16Vec3) U16Vec3 {
	return U16Vec3{
		X: a.Y*b.Z - a.Z*b.Y,
		Y: a.Z*b.X - a.X*b.Z,
		Z: a.X*b.Y - a.Y*b.X,
	}
}

func (v U16Vec3) LenSq() uint16 {
	return v.Dot(v)
}

func (v U16Vec3) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y) + float64(v.Z)*float64(v.Z)))
}

func (v U16Vec3) Normalize() Vec3 {
	l := v.Len()
	if l == 0 {
		return Vec3{}
	}
	return Vec3{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
		Z: float32(v.Z) / l,
	}
}

func (a U16Vec3) Lerp(b U16Vec3, t float32) Vec3 {
	return Vec3{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
		Z: float32(a.Z) + (float32(b.Z)-float32(a.Z))*t,
	}
}

func (a U16Vec3) Dist(b U16Vec3) float32 {
	return float32(math.Sqrt((float64(a.X)-float64(b.X))*(float64(a.X)-float64(b.X)) + (float64(a.Y)-float64(b.Y))*(float64(a.Y)-float64(b.Y)) + (float64(a.Z)-float64(b.Z))*(float64(a.Z)-float64(b.Z))))
}

func (a U16Vec3) Eq(b U16Vec3) bool {
	return a.X == b.X && a.Y == b.Y && a.Z == b.Z
}

func (v U16Vec3) Float32() Vec3 {
	return Vec3{
		X: float32(v.X),
		Y: float32(v.Y),
		Z: float32(v.Z),
	}
}

func (v U16Vec3) XY() U16Vec2 {
	return U16Vec2{X: v.X, Y: v.Y}
}

func (v U16Vec3) MarshalJSON() ([]byte, error) {
	return json.Marshal([3]uint16{v.X, v.Y, v.Z})
}

func (v *U16Vec3) UnmarshalJSON(data []byte) error {
	var arr [3]uint16
	if err := json.Unmarshal(data, &arr); err != nil {
		return err
	}
	v.X = arr[0]
	v.Y = arr[1]
	v.Z = arr[2]
	return nil
}
