// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	"encoding/json"
	"math"
)

// U16Vec4 is a 4-component uint16 vector.
type U16Vec4 struct {
	X uint16
	Y uint16
	Z uint16
	W uint16
}

func NewU16Vec4(x uint16, y uint16, z uint16, w uint16) U16Vec4 {
	return U16Vec4{X: x, Y: y, Z: z, W: w}
}

func (a U16Vec4) Add(b U16Vec4) U16Vec4 {
	return U16Vec4{
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
		W: a.W + b.W,
	}
}

func (a U16Vec4) Sub(b U16Vec4) U16Vec4 {
	return U16Vec4{
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
		W: a.W - b.W,
	}
}

func (v U16Vec4) Scale(s uint16) U16Vec4 {
	return U16Vec4{
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
		W: v.W * s,
	}
}

func (a U16Vec4) Dot(b U16Vec4) uint16 {
	return a.X*b.X + a.Y*b.Y + a.Z*b.Z + a.W*b.W
}

func (v U16Vec4) LenSq() uint16 {
	return v.Dot(v)
}

func (v U16Vec4) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y) + float64(v.Z)*float64(v.Z) + float64(v.W)*float64(v.W)))
}

func (v U16Vec4) Normalize() Vec4 {
	l := v.Len()
	if l == 0 {
		return Vec4{}
	}
	return Vec4{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
		Z: float32(v.Z) / l,
		W: float32(v.W) / l,
	}
}

func (a U16Vec4) Lerp(b U16Vec4, t float32) Vec4 {
	return Vec4{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
		Z: float32(a.Z) + (float32(b.Z)-float32(a.Z))*t,
		W: float32(a.W) + (float32(b.W)-float32(a.W))*t,
	}
}

func (a U16Vec4) Dist(b U16Vec4) float32 {
	return float32(math.Sqrt((float64(a.X)-float64(b.X))*(float64(a.X)-float64(b.X)) + (float64(a.Y)-float64(b.Y))*(float64(a.Y)-float64(b.Y)) + (float64(a.Z)-float64(b.Z))*(float64(a.Z)-float64(b.Z)) + (float64(a.W)-float64(b.W))*(float64(a.W)-float64(b.W))))
}

func (a U16Vec4) Eq(b U16Vec4) bool {
	return a.X == b.X && a.Y == b.Y && a.Z == b.Z && a.W == b.W
}

func (v U16Vec4) Float32() Vec4 {
	return Vec4{
		X: float32(v.X),
		Y: float32(v.Y),
		Z: float32(v.Z),
		W: float32(v.W),
	}
}

func (v U16Vec4) XY() U16Vec2 {
	return U16Vec2{X: v.X, Y: v.Y}
}

func (v U16Vec4) XYZ() U16Vec3 {
	return U16Vec3{X: v.X, Y: v.Y, Z: v.Z}
}

func (v U16Vec4) MarshalJSON() ([]byte, error) {
	return json.Marshal([4]uint16{v.X, v.Y, v.Z, v.W})
}

func (v *U16Vec4) UnmarshalJSON(data []byte) error {
	var arr [4]uint16
	if err := json.Unmarshal(data, &arr); err != nil {
		return err
	}
	v.X = arr[0]
	v.Y = arr[1]
	v.Z = arr[2]
	v.W = arr[3]
	return nil
}
