// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	"encoding/json"
	"math"
)

// U16Vec2 is a 2-component uint16 vector.
type U16Vec2 struct {
	X uint16
	Y uint16
}

func NewU16Vec2(x uint16, y uint16) U16Vec2 {
	return U16Vec2{X: x, Y: y}
}

func (a U16Vec2) Add(b U16Vec2) U16Vec2 {
	return U16Vec2{
		X: a.X + b.X,
		Y: a.Y + b.Y,
	}
}

func (a U16Vec2) Sub(b U16Vec2) U16Vec2 {
	return U16Vec2{
		X: a.X - b.X,
		Y: a.Y - b.Y,
	}
}

func (v U16Vec2) Scale(s uint16) U16Vec2 {
	return U16Vec2{
		X: v.X * s,
		Y: v.Y * s,
	}
}

func (a U16Vec2) Dot(b U16Vec2) uint16 {
	return a.X*b.X + a.Y*b.Y
}

func (v U16Vec2) LenSq() uint16 {
	return v.Dot(v)
}

func (v U16Vec2) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y)))
}

func (v U16Vec2) Normalize() Vec2 {
	l := v.Len()
	if l == 0 {
		return Vec2{}
	}
	return Vec2{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
	}
}

func (a U16Vec2) Lerp(b U16Vec2, t float32) Vec2 {
	return Vec2{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
	}
}

func (a U16Vec2) Dist(b U16Vec2) float32 {
	return float32(math.Sqrt((float64(a.X)-float64(b.X))*(float64(a.X)-float64(b.X)) + (float64(a.Y)-float64(b.Y))*(float64(a.Y)-float64(b.Y))))
}

func (a U16Vec2) Eq(b U16Vec2) bool {
	return a.X == b.X && a.Y == b.Y
}

func (v U16Vec2) Float32() Vec2 {
	return Vec2{
		X: float32(v.X),
		Y: float32(v.Y),
	}
}

func (v U16Vec2) MarshalJSON() ([]byte, error) {
	return json.Marshal([2]uint16{v.X, v.Y})
}

func (v *U16Vec2) UnmarshalJSON(data []byte) error {
	var arr [2]uint16
	if err := json.Unmarshal(data, &arr); err != nil {
		return err
	}
	v.X = arr[0]
	v.Y = arr[1]
	return nil
}
