// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// U32Vec3 is a 3-component uint32 vector.
type U32Vec3 struct {
	X uint32
	Y uint32
	Z uint32
}

func NewU32Vec3(x uint32, y uint32, z uint32) U32Vec3 {
	return U32Vec3{X: x, Y: y, Z: z}
}

func (a U32Vec3) Add(b U32Vec3) U32Vec3 {
	return U32Vec3{
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
	}
}

func (a U32Vec3) Sub(b U32Vec3) U32Vec3 {
	return U32Vec3{
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
	}
}

func (v U32Vec3) Scale(s uint32) U32Vec3 {
	return U32Vec3{
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
	}
}

func (a U32Vec3) Dot(b U32Vec3) uint32 {
	return a.X*b.X + a.Y*b.Y + a.Z*b.Z
}

func (a U32Vec3) Cross(b U32Vec3) U32Vec3 {
	return U32Vec3{
		X: a.Y*b.Z - a.Z*b.Y,
		Y: a.Z*b.X - a.X*b.Z,
		Z: a.X*b.Y - a.Y*b.X,
	}
}

func (v U32Vec3) LenSq() uint32 {
	return v.Dot(v)
}

func (v U32Vec3) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y) + float64(v.Z)*float64(v.Z)))
}

func (v U32Vec3) Normalize() Vec3 {
	l := v.Len()
	if l == 0 {
		return Vec3{}
	}
	return Vec3{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
		Z: float32(v.Z) / l,
	}
}

func (a U32Vec3) Lerp(b U32Vec3, t float32) Vec3 {
	return Vec3{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
		Z: float32(a.Z) + (float32(b.Z)-float32(a.Z))*t,
	}
}

func (a U32Vec3) Dist(b U32Vec3) float32 {
	d := a.Sub(b)
	return d.Len()
}

func (a U32Vec3) Eq(b U32Vec3) bool {
	return a.X == b.X && a.Y == b.Y && a.Z == b.Z
}

func (v U32Vec3) Float32() Vec3 {
	return Vec3{
		X: float32(v.X),
		Y: float32(v.Y),
		Z: float32(v.Z),
	}
}

func (v U32Vec3) XY() U32Vec2 {
	return U32Vec2{X: v.X, Y: v.Y}
}
