// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// U32Vec2 is a 2-component uint32 vector.
type U32Vec2 struct {
	X uint32
	Y uint32
}

func NewU32Vec2(x uint32, y uint32) U32Vec2 {
	return U32Vec2{X: x, Y: y}
}

func (a U32Vec2) Add(b U32Vec2) U32Vec2 {
	return U32Vec2{
		X: a.X + b.X,
		Y: a.Y + b.Y,
	}
}

func (a U32Vec2) Sub(b U32Vec2) U32Vec2 {
	return U32Vec2{
		X: a.X - b.X,
		Y: a.Y - b.Y,
	}
}

func (v U32Vec2) Scale(s uint32) U32Vec2 {
	return U32Vec2{
		X: v.X * s,
		Y: v.Y * s,
	}
}

func (a U32Vec2) Dot(b U32Vec2) uint32 {
	return a.X*b.X + a.Y*b.Y
}

func (v U32Vec2) LenSq() uint32 {
	return v.Dot(v)
}

func (v U32Vec2) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y)))
}

func (v U32Vec2) Normalize() Vec2 {
	l := v.Len()
	if l == 0 {
		return Vec2{}
	}
	return Vec2{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
	}
}

func (a U32Vec2) Lerp(b U32Vec2, t float32) Vec2 {
	return Vec2{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
	}
}

func (a U32Vec2) Dist(b U32Vec2) float32 {
	d := a.Sub(b)
	return d.Len()
}

func (a U32Vec2) Eq(b U32Vec2) bool {
	return a.X == b.X && a.Y == b.Y
}

func (v U32Vec2) Float32() Vec2 {
	return Vec2{
		X: float32(v.X),
		Y: float32(v.Y),
	}
}
