// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// U64Vec3 is a 3-component uint64 vector.
type U64Vec3 struct {
	X uint64
	Y uint64
	Z uint64
}

func NewU64Vec3(x uint64, y uint64, z uint64) U64Vec3 {
	return U64Vec3{X: x, Y: y, Z: z}
}

func (a U64Vec3) Add(b U64Vec3) U64Vec3 {
	return U64Vec3{
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
	}
}

func (a U64Vec3) Sub(b U64Vec3) U64Vec3 {
	return U64Vec3{
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
	}
}

func (v U64Vec3) Scale(s uint64) U64Vec3 {
	return U64Vec3{
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
	}
}

func (a U64Vec3) Dot(b U64Vec3) uint64 {
	return a.X*b.X + a.Y*b.Y + a.Z*b.Z
}

func (a U64Vec3) Cross(b U64Vec3) U64Vec3 {
	return U64Vec3{
		X: a.Y*b.Z - a.Z*b.Y,
		Y: a.Z*b.X - a.X*b.Z,
		Z: a.X*b.Y - a.Y*b.X,
	}
}

func (v U64Vec3) LenSq() uint64 {
	return v.Dot(v)
}

func (v U64Vec3) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y) + float64(v.Z)*float64(v.Z)))
}

func (v U64Vec3) Normalize() Vec3 {
	l := v.Len()
	if l == 0 {
		return Vec3{}
	}
	return Vec3{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
		Z: float32(v.Z) / l,
	}
}

func (a U64Vec3) Lerp(b U64Vec3, t float32) Vec3 {
	return Vec3{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
		Z: float32(a.Z) + (float32(b.Z)-float32(a.Z))*t,
	}
}

func (a U64Vec3) Dist(b U64Vec3) float32 {
	d := a.Sub(b)
	return d.Len()
}

func (a U64Vec3) Eq(b U64Vec3) bool {
	return a.X == b.X && a.Y == b.Y && a.Z == b.Z
}

func (v U64Vec3) Float32() Vec3 {
	return Vec3{
		X: float32(v.X),
		Y: float32(v.Y),
		Z: float32(v.Z),
	}
}

func (v U64Vec3) XY() U64Vec2 {
	return U64Vec2{X: v.X, Y: v.Y}
}
