// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// U64Vec4 is a 4-component uint64 vector.
type U64Vec4 struct {
	X uint64
	Y uint64
	Z uint64
	W uint64
}

func NewU64Vec4(x uint64, y uint64, z uint64, w uint64) U64Vec4 {
	return U64Vec4{X: x, Y: y, Z: z, W: w}
}

func (a U64Vec4) Add(b U64Vec4) U64Vec4 {
	return U64Vec4{
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
		W: a.W + b.W,
	}
}

func (a U64Vec4) Sub(b U64Vec4) U64Vec4 {
	return U64Vec4{
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
		W: a.W - b.W,
	}
}

func (v U64Vec4) Scale(s uint64) U64Vec4 {
	return U64Vec4{
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
		W: v.W * s,
	}
}

func (a U64Vec4) Dot(b U64Vec4) uint64 {
	return a.X*b.X + a.Y*b.Y + a.Z*b.Z + a.W*b.W
}

func (v U64Vec4) LenSq() uint64 {
	return v.Dot(v)
}

func (v U64Vec4) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y) + float64(v.Z)*float64(v.Z) + float64(v.W)*float64(v.W)))
}

func (v U64Vec4) Normalize() Vec4 {
	l := v.Len()
	if l == 0 {
		return Vec4{}
	}
	return Vec4{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
		Z: float32(v.Z) / l,
		W: float32(v.W) / l,
	}
}

func (a U64Vec4) Lerp(b U64Vec4, t float32) Vec4 {
	return Vec4{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
		Z: float32(a.Z) + (float32(b.Z)-float32(a.Z))*t,
		W: float32(a.W) + (float32(b.W)-float32(a.W))*t,
	}
}

func (a U64Vec4) Dist(b U64Vec4) float32 {
	return float32(math.Sqrt((float64(a.X)-float64(b.X))*(float64(a.X)-float64(b.X)) + (float64(a.Y)-float64(b.Y))*(float64(a.Y)-float64(b.Y)) + (float64(a.Z)-float64(b.Z))*(float64(a.Z)-float64(b.Z)) + (float64(a.W)-float64(b.W))*(float64(a.W)-float64(b.W))))
}

func (a U64Vec4) Eq(b U64Vec4) bool {
	return a.X == b.X && a.Y == b.Y && a.Z == b.Z && a.W == b.W
}

func (v U64Vec4) Float32() Vec4 {
	return Vec4{
		X: float32(v.X),
		Y: float32(v.Y),
		Z: float32(v.Z),
		W: float32(v.W),
	}
}

func (v U64Vec4) XY() U64Vec2 {
	return U64Vec2{X: v.X, Y: v.Y}
}

func (v U64Vec4) XYZ() U64Vec3 {
	return U64Vec3{X: v.X, Y: v.Y, Z: v.Z}
}
