// Code generated by cmd/gen; DO NOT EDIT.

package math

import (
	"encoding/json"
	"math"
)

// U64Vec2 is a 2-component uint64 vector.
type U64Vec2 struct {
	X uint64
	Y uint64
}

func NewU64Vec2(x uint64, y uint64) U64Vec2 {
	return U64Vec2{X: x, Y: y}
}

func (a U64Vec2) Add(b U64Vec2) U64Vec2 {
	return U64Vec2{
		X: a.X + b.X,
		Y: a.Y + b.Y,
	}
}

func (a U64Vec2) Sub(b U64Vec2) U64Vec2 {
	return U64Vec2{
		X: a.X - b.X,
		Y: a.Y - b.Y,
	}
}

func (v U64Vec2) Scale(s uint64) U64Vec2 {
	return U64Vec2{
		X: v.X * s,
		Y: v.Y * s,
	}
}

func (a U64Vec2) Dot(b U64Vec2) uint64 {
	return a.X*b.X + a.Y*b.Y
}

func (v U64Vec2) LenSq() uint64 {
	return v.Dot(v)
}

func (v U64Vec2) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y)))
}

func (v U64Vec2) Normalize() Vec2 {
	l := v.Len()
	if l == 0 {
		return Vec2{}
	}
	return Vec2{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
	}
}

func (a U64Vec2) Lerp(b U64Vec2, t float32) Vec2 {
	return Vec2{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
	}
}

func (a U64Vec2) Dist(b U64Vec2) float32 {
	return float32(math.Sqrt((float64(a.X)-float64(b.X))*(float64(a.X)-float64(b.X)) + (float64(a.Y)-float64(b.Y))*(float64(a.Y)-float64(b.Y))))
}

func (a U64Vec2) Eq(b U64Vec2) bool {
	return a.X == b.X && a.Y == b.Y
}

func (v U64Vec2) Float32() Vec2 {
	return Vec2{
		X: float32(v.X),
		Y: float32(v.Y),
	}
}

func (v U64Vec2) MarshalJSON() ([]byte, error) {
	return json.Marshal([2]uint64{v.X, v.Y})
}

func (v *U64Vec2) UnmarshalJSON(data []byte) error {
	var arr [2]uint64
	if err := json.Unmarshal(data, &arr); err != nil {
		return err
	}
	v.X = arr[0]
	v.Y = arr[1]
	return nil
}
