// Code generated by cmd/gen; DO NOT EDIT.

package math

import "math"

// U8Vec2 is a 2-component uint8 vector.
type U8Vec2 struct {
	X uint8
	Y uint8
}

func NewU8Vec2(x uint8, y uint8) U8Vec2 {
	return U8Vec2{X: x, Y: y}
}

func (a U8Vec2) Add(b U8Vec2) U8Vec2 {
	return U8Vec2{
		X: a.X + b.X,
		Y: a.Y + b.Y,
	}
}

func (a U8Vec2) Sub(b U8Vec2) U8Vec2 {
	return U8Vec2{
		X: a.X - b.X,
		Y: a.Y - b.Y,
	}
}

func (v U8Vec2) Scale(s uint8) U8Vec2 {
	return U8Vec2{
		X: v.X * s,
		Y: v.Y * s,
	}
}

func (a U8Vec2) Dot(b U8Vec2) uint8 {
	return a.X*b.X + a.Y*b.Y
}

func (v U8Vec2) LenSq() uint8 {
	return v.Dot(v)
}

func (v U8Vec2) Len() float32 {
	return float32(math.Sqrt(float64(v.X)*float64(v.X) + float64(v.Y)*float64(v.Y)))
}

func (v U8Vec2) Normalize() Vec2 {
	l := v.Len()
	if l == 0 {
		return Vec2{}
	}
	return Vec2{
		X: float32(v.X) / l,
		Y: float32(v.Y) / l,
	}
}

func (a U8Vec2) Lerp(b U8Vec2, t float32) Vec2 {
	return Vec2{
		X: float32(a.X) + (float32(b.X)-float32(a.X))*t,
		Y: float32(a.Y) + (float32(b.Y)-float32(a.Y))*t,
	}
}

func (a U8Vec2) Dist(b U8Vec2) float32 {
	return float32(math.Sqrt((float64(a.X)-float64(b.X))*(float64(a.X)-float64(b.X)) + (float64(a.Y)-float64(b.Y))*(float64(a.Y)-float64(b.Y))))
}

func (a U8Vec2) Eq(b U8Vec2) bool {
	return a.X == b.X && a.Y == b.Y
}

func (v U8Vec2) Float32() Vec2 {
	return Vec2{
		X: float32(v.X),
		Y: float32(v.Y),
	}
}
