// Code generated by cmd/gen; DO NOT EDIT.

package math

import "encoding/json"

// TVec2 is a generic 2-component vector.
type TVec2[T Numeric] struct {
	X T
	Y T
}

func (a TVec2[T]) Add(b TVec2[T]) TVec2[T] {
	return TVec2[T]{
		X: a.X + b.X,
		Y: a.Y + b.Y,
	}
}

func (a TVec2[T]) Sub(b TVec2[T]) TVec2[T] {
	return TVec2[T]{
		X: a.X - b.X,
		Y: a.Y - b.Y,
	}
}

func (v TVec2[T]) Scale(s T) TVec2[T] {
	return TVec2[T]{
		X: v.X * s,
		Y: v.Y * s,
	}
}

func (a TVec2[T]) Dot(b TVec2[T]) T {
	return a.X*b.X + a.Y*b.Y
}

func (v TVec2[T]) LenSq() T {
	return v.Dot(v)
}

func (a TVec2[T]) Eq(b TVec2[T]) bool {
	return a.X == b.X && a.Y == b.Y
}

func (v TVec2[T]) MarshalJSON() ([]byte, error) {
	return json.Marshal([2]T{v.X, v.Y})
}

func (v *TVec2[T]) UnmarshalJSON(data []byte) error {
	var arr [2]T
	if err := json.Unmarshal(data, &arr); err != nil {
		return err
	}
	v.X = arr[0]
	v.Y = arr[1]
	return nil
}
