// Code generated by cmd/gen; DO NOT EDIT.

package math

// TVec3 is a 3-component vector.
type TVec3[T Float] [3]T

// Vec3 is a TVec3 of float32.
type Vec3 = TVec3[float32]

func NewVec3(x float32, y float32, z float32) Vec3 {
	return Vec3{x, y, z}
}

func (v TVec3[T]) X() T { return v[0] }
func (v TVec3[T]) Y() T { return v[1] }
func (v TVec3[T]) Z() T { return v[2] }

func (a TVec3[T]) Add(b TVec3[T]) TVec3[T] {
	return TVec3[T]{a[0] + b[0], a[1] + b[1], a[2] + b[2]}
}

func (a TVec3[T]) Sub(b TVec3[T]) TVec3[T] {
	return TVec3[T]{a[0] - b[0], a[1] - b[1], a[2] - b[2]}
}

func (v TVec3[T]) Scale(s T) TVec3[T] {
	return TVec3[T]{v[0] * s, v[1] * s, v[2] * s}
}

func (a TVec3[T]) Dot(b TVec3[T]) T {
	return a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
}

func (a TVec3[T]) Cross(b TVec3[T]) TVec3[T] {
	return TVec3[T]{
		a[1]*b[2] - a[2]*b[1],
		a[2]*b[0] - a[0]*b[2],
		a[0]*b[1] - a[1]*b[0],
	}
}
func (v TVec3[T]) Len() T {
	return sqrt(v.Dot(v))
}

func (v TVec3[T]) LenSq() T {
	return v.Dot(v)
}

func (v TVec3[T]) Normalize() TVec3[T] {
	l := v.Len()
	if l == 0 {
		return TVec3[T]{}
	}
	return v.Scale(1.0 / l)
}

func (a TVec3[T]) Lerp(b TVec3[T], t T) TVec3[T] {
	return a.Add(b.Sub(a).Scale(t))
}

func (a TVec3[T]) Dist(b TVec3[T]) T {
	return a.Sub(b).Len()
}

func (a TVec3[T]) Eq(b TVec3[T]) bool {
	return a[0] == b[0] && a[1] == b[1] && a[2] == b[2]
}

func (a TVec3[T]) ApproxEq(b TVec3[T], eps T) bool {
	return abs(a[0]-b[0]) <= eps && abs(a[1]-b[1]) <= eps && abs(a[2]-b[2]) <= eps
}

func (v TVec3[T]) XY() TVec2[T] {
	return TVec2[T]{v[0], v[1]}
}
