// Code generated by cmd/gen; DO NOT EDIT.

package math

// TVec3 is a generic 3-component vector.
type TVec3[T Numeric] struct {
	X T
	Y T
	Z T
}

func (a TVec3[T]) Add(b TVec3[T]) TVec3[T] {
	return TVec3[T]{
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
	}
}

func (a TVec3[T]) Sub(b TVec3[T]) TVec3[T] {
	return TVec3[T]{
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
	}
}

func (v TVec3[T]) Scale(s T) TVec3[T] {
	return TVec3[T]{
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
	}
}

func (a TVec3[T]) Dot(b TVec3[T]) T {
	return a.X*b.X + a.Y*b.Y + a.Z*b.Z
}

func (a TVec3[T]) Cross(b TVec3[T]) TVec3[T] {
	return TVec3[T]{
		X: a.Y*b.Z - a.Z*b.Y,
		Y: a.Z*b.X - a.X*b.Z,
		Z: a.X*b.Y - a.Y*b.X,
	}
}

func (v TVec3[T]) LenSq() T {
	return v.Dot(v)
}

func (a TVec3[T]) Eq(b TVec3[T]) bool {
	return a.X == b.X && a.Y == b.Y && a.Z == b.Z
}

func (v TVec3[T]) XY() TVec2[T] {
	return TVec2[T]{X: v.X, Y: v.Y}
}
