// Code generated by cmd/gen; DO NOT EDIT.

package math

// TVec4 is a generic 4-component vector.
type TVec4[T Numeric] struct {
	X T
	Y T
	Z T
	W T
}

func (a TVec4[T]) Add(b TVec4[T]) TVec4[T] {
	return TVec4[T]{
		X: a.X + b.X,
		Y: a.Y + b.Y,
		Z: a.Z + b.Z,
		W: a.W + b.W,
	}
}

func (a TVec4[T]) Sub(b TVec4[T]) TVec4[T] {
	return TVec4[T]{
		X: a.X - b.X,
		Y: a.Y - b.Y,
		Z: a.Z - b.Z,
		W: a.W - b.W,
	}
}

func (v TVec4[T]) Scale(s T) TVec4[T] {
	return TVec4[T]{
		X: v.X * s,
		Y: v.Y * s,
		Z: v.Z * s,
		W: v.W * s,
	}
}

func (a TVec4[T]) Dot(b TVec4[T]) T {
	return a.X*b.X + a.Y*b.Y + a.Z*b.Z + a.W*b.W
}

func (v TVec4[T]) LenSq() T {
	return v.Dot(v)
}

func (a TVec4[T]) Eq(b TVec4[T]) bool {
	return a.X == b.X && a.Y == b.Y && a.Z == b.Z && a.W == b.W
}

func (v TVec4[T]) XY() TVec2[T] {
	return TVec2[T]{X: v.X, Y: v.Y}
}

func (v TVec4[T]) XYZ() TVec3[T] {
	return TVec3[T]{X: v.X, Y: v.Y, Z: v.Z}
}
