name: CI

on:
  push:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clear stale build cache
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh cache delete go-build --repo ${{ github.repository }} || true

      - uses: wow-look-at-my/go-toolchain@latest
        with:
          generate: 8a4f77935fb5
